plugins {
    id 'com.android.application'
}

android {
    namespace 'com.solum.engine'
    compileSdk 34

    defaultConfig {
        applicationId 'com.solum.engine'
        minSdk 26
        targetSdk 34
        versionCode 4
        versionName '0.4.0'
    }
}


dependencies {
    implementation files('libs/filament-solum/filament-android-release.aar')
    implementation files('libs/filament-solum/gltfio-android-release.aar')
    implementation files('libs/filament-solum/filament-utils-android-release.aar')
}
