plugins {
    id 'com.android.application'
}

android {
    namespace 'com.solum.engine'
    compileSdk 34

    defaultConfig {
        applicationId 'com.solum.engine'
        minSdk 26
        targetSdk 34
        versionCode 4
        versionName '0.4.0'
    }
}

dependencies {
    implementation 'com.google.android.filament:filament-android:1.71.4'
    implementation 'com.google.android.filament:gltfio-android:1.71.4'
    implementation 'com.google.android.filament:filament-utils-android:1.71.4'
}
