pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = uri("third_party/filament-solum/maven") }
        google()
        mavenCentral()
    }
}

rootProject.name = "SOLUM-Platform"
include ':apps:engine'
include ':apps:solum-companion'
