#pragma once
#include "renderer_types.hpp"

namespace solum {

enum class RenderLabScene {
    Scene01FoundationCube,
    Scene02ModelImportLab,
    Scene03GlbMeshRenderLab,
    Scene04TextureBindingLab,
    Scene04LightShadowLab,
    Scene05MultiPrimitiveRenderLab,
    Scene06PbrMaterialMapsLab,
    Scene07LightingFoundationLab,
    Scene08TangentNormalExposureLab,
    Scene09BrdfMaterialResponseLab,
    Scene10LightingControlLab,
    Scene11EnvironmentReflectionLab,
    Scene12GroundingInspectorLab,
    Scene13MaterialCalibrationLab,
    Scene14SpecularGlossLab,
    Scene15EnvironmentIblLab,
    Scene16MaterialSlotEditorLab,
    Scene17RuntimeMaterialWorkflowLab,
    Scene18AlphaCutoutMaterialLab,
    Scene19EmissiveMaterialPresetsLab,
    Scene20ClearcoatPaintLayerLab,
    Scene21BetterEnvironmentReflectionLab,
    Scene22GlassMaterialFoundationLab,
    Scene23GlassReflectionPolishLab,
    Scene24TransparentGlassPassLab,
    Scene25GlassVisualQualityLab,
    Scene06PerformanceLab
};

struct RenderLabState {
    RenderLabScene currentScene = RenderLabScene::Scene25GlassVisualQualityLab;
    bool cubeReady = false;
    bool depthReady = false;
    bool cameraReady = false;
    bool cameraMvpReady = false;
    bool cameraControlsReady = false;
    bool materialConstantsReady = false;
    bool meshAttributeLayoutReady = false;
    bool indexBufferReady = false;
    bool uniformOrPushConstantsReady = false;
    bool triangleFallbackAvailable = true;
    bool triangleFallbackEnabled = false;
    uint32_t vertexCount = 0;
    uint32_t indexCount = 0;
    uint32_t vertexStrideBytes = 0;
    float cameraYawDeg = 0.0f;
    float cameraPitchDeg = 0.0f;
    float cameraDistance = 0.0f;
    const char* vertexLayout = "POSITION,NORMAL,TEXCOORD_0,COLOR_0,TANGENT";
    MaterialConstants material;
    uint64_t framesRendered = 0;
    ModelRenderState model;

    const char* sceneId() const {
        switch (currentScene) {
            case RenderLabScene::Scene01FoundationCube: return "scene01_foundation_cube";
            case RenderLabScene::Scene02ModelImportLab: return "scene02_model_import_lab";
            case RenderLabScene::Scene03GlbMeshRenderLab: return "scene03_glb_mesh_render_lab";
            case RenderLabScene::Scene04TextureBindingLab: return "scene04_texture_binding_lab";
            case RenderLabScene::Scene04LightShadowLab: return "scene04_light_shadow_lab";
            case RenderLabScene::Scene05MultiPrimitiveRenderLab: return "scene05_multi_primitive_render_lab";
            case RenderLabScene::Scene06PbrMaterialMapsLab: return "scene06_pbr_material_maps_lab";
            case RenderLabScene::Scene07LightingFoundationLab: return "scene07_lighting_foundation_lab";
            case RenderLabScene::Scene08TangentNormalExposureLab: return "scene08_tangent_normal_exposure_lab";
            case RenderLabScene::Scene09BrdfMaterialResponseLab: return "scene09_brdf_material_response_lab";
            case RenderLabScene::Scene10LightingControlLab: return "scene10_lighting_control_lab";
            case RenderLabScene::Scene11EnvironmentReflectionLab: return "scene11_environment_reflection_lab";
            case RenderLabScene::Scene12GroundingInspectorLab: return "scene12_grounding_inspector_lab";
            case RenderLabScene::Scene13MaterialCalibrationLab: return "scene13_material_calibration_lab";
            case RenderLabScene::Scene14SpecularGlossLab: return "scene14_specular_gloss_lab";
            case RenderLabScene::Scene15EnvironmentIblLab: return "scene15_environment_ibl_lab";
            case RenderLabScene::Scene16MaterialSlotEditorLab: return "scene16_material_slot_editor_lab";
            case RenderLabScene::Scene17RuntimeMaterialWorkflowLab: return "scene17_runtime_material_workflow_lab";
            case RenderLabScene::Scene18AlphaCutoutMaterialLab: return "scene18_alpha_cutout_material_lab";
            case RenderLabScene::Scene19EmissiveMaterialPresetsLab: return "scene19_emissive_material_presets_lab";
            case RenderLabScene::Scene20ClearcoatPaintLayerLab: return "scene20_clearcoat_paint_layer_lab";
            case RenderLabScene::Scene21BetterEnvironmentReflectionLab: return "scene21_better_environment_reflection_lab";
            case RenderLabScene::Scene22GlassMaterialFoundationLab: return "scene22_glass_material_foundation_lab";
            case RenderLabScene::Scene23GlassReflectionPolishLab: return "scene23_glass_reflection_polish_lab";
            case RenderLabScene::Scene24TransparentGlassPassLab: return "scene24_transparent_glass_pass_lab";
            case RenderLabScene::Scene25GlassVisualQualityLab: return "scene25_glass_visual_quality_lab";
            case RenderLabScene::Scene06PerformanceLab: return "scene06_performance_lab";
            default: return "unknown";
        }
    }

    const char* sceneName() const {
        switch (currentScene) {
            case RenderLabScene::Scene01FoundationCube: return "Scene01 Foundation Cube";
            case RenderLabScene::Scene02ModelImportLab: return "Scene02 Model Import Lab";
            case RenderLabScene::Scene03GlbMeshRenderLab: return "Scene03 GLB Mesh Render Lab";
            case RenderLabScene::Scene04TextureBindingLab: return "Scene04 Texture Binding Lab";
            case RenderLabScene::Scene04LightShadowLab: return "Scene04 Light/Shadow Lab";
            case RenderLabScene::Scene05MultiPrimitiveRenderLab: return "Scene05 Multi Primitive Render Lab";
            case RenderLabScene::Scene06PbrMaterialMapsLab: return "Scene06 PBR Material Maps Lab";
            case RenderLabScene::Scene07LightingFoundationLab: return "Scene07 Lighting Foundation Lab";
            case RenderLabScene::Scene08TangentNormalExposureLab: return "Scene08 Tangent Normal Exposure Lab";
            case RenderLabScene::Scene09BrdfMaterialResponseLab: return "Scene09 BRDF Material Response Lab";
            case RenderLabScene::Scene10LightingControlLab: return "Scene10 Lighting Control Lab";
            case RenderLabScene::Scene11EnvironmentReflectionLab: return "Scene11 Environment Reflection Lab";
            case RenderLabScene::Scene12GroundingInspectorLab: return "Scene12 Grounding Inspector Lab";
            case RenderLabScene::Scene13MaterialCalibrationLab: return "Scene13 Material Calibration Lab";
            case RenderLabScene::Scene14SpecularGlossLab: return "Scene14 Specular Gloss Lab";
            case RenderLabScene::Scene15EnvironmentIblLab: return "Scene15 Environment IBL Lab";
            case RenderLabScene::Scene16MaterialSlotEditorLab: return "Scene16 Material Slot Editor Lab";
            case RenderLabScene::Scene17RuntimeMaterialWorkflowLab: return "Scene17 Runtime Material Workflow Lab";
            case RenderLabScene::Scene18AlphaCutoutMaterialLab: return "Scene18 Alpha Cutout Material Lab";
            case RenderLabScene::Scene19EmissiveMaterialPresetsLab: return "Scene19 Emissive Material Presets Lab";
            case RenderLabScene::Scene20ClearcoatPaintLayerLab: return "Scene20 Clearcoat Paint Layer Lab";
            case RenderLabScene::Scene21BetterEnvironmentReflectionLab: return "Scene21 Better Environment Reflection Lab";
            case RenderLabScene::Scene22GlassMaterialFoundationLab: return "Scene22 Glass Material Foundation Lab";
            case RenderLabScene::Scene23GlassReflectionPolishLab: return "Scene23 Glass Reflection Polish Lab";
            case RenderLabScene::Scene24TransparentGlassPassLab: return "Scene24 Transparent Glass Pass Lab";
            case RenderLabScene::Scene25GlassVisualQualityLab: return "Scene25 Glass Visual Quality Lab";
            case RenderLabScene::Scene06PerformanceLab: return "Scene06 Performance Lab";
            default: return "Unknown";
        }
    }

    void writeJsonFields(std::ostream& f, const char* indent = "  ") const {
        f << indent << "\"renderLab\": {\n";
        f << indent << "  \"schema\": \"solum.render_lab_state\",\n";
        f << indent << "  \"schemaVersion\": 1,\n";
        f << indent << "  \"currentScene\": \"" << sceneId() << "\",\n";
        f << indent << "  \"currentLabScene\": \"" << sceneId() << "\",\n";
        f << indent << "  \"currentLabSceneName\": \"" << sceneName() << "\",\n";
        f << indent << "  \"renderingStatus\": \"" << (model.modelReady() ? "multi_primitive_static" : "fallback_cube") << "\",\n";
        f << indent << "  \"assetImportStatus\": \"" << (model.activeModelName == "none" ? "no active model" : "active model") << "\",\n";
        f << indent << "  \"activeModelName\": \"" << escapeJson(model.activeModelName) << "\",\n";
        f << indent << "  \"activeModelPath\": \"" << escapeJson(model.activeModelPath) << "\",\n";
        f << indent << "  \"activePrimitiveIndex\": " << model.activePrimitiveIndex << ",\n";
        f << indent << "  \"gpuUploadStatus\": \"" << escapeJson(model.gpuUploadStatus) << "\",\n";
        f << indent << "  \"drawStatus\": \"" << escapeJson(model.drawStatus) << "\",\n";
        f << indent << "  \"meshDrawStatus\": \"" << escapeJson(model.meshDrawStatus) << "\",\n";
        f << indent << "  \"textureUploadStatus\": \"" << escapeJson(model.textureUploadStatus) << "\",\n";
        f << indent << "  \"baseColorTextureStatus\": \"" << escapeJson(model.baseColorTextureStatus) << "\",\n";
        f << indent << "  \"baseColorTextureName\": \"" << escapeJson(model.baseColorTextureName) << "\",\n";
        f << indent << "  \"baseColorTextureSource\": \"" << escapeJson(model.baseColorTextureSource) << "\",\n";
        f << indent << "  \"baseColorTextureMimeType\": \"" << escapeJson(model.baseColorTextureMimeType) << "\",\n";
        f << indent << "  \"textureWidth\": " << model.textureWidth << ",\n";
        f << indent << "  \"textureHeight\": " << model.textureHeight << ",\n";
        f << indent << "  \"textureBytes\": " << model.textureBytes << ",\n";
        f << indent << "  \"textureFallbackUsed\": " << (model.textureFallbackUsed ? "true" : "false") << ",\n";
        f << indent << "  \"uploadedVertexCount\": " << model.uploadedVertexCount << ",\n";
        f << indent << "  \"uploadedIndexCount\": " << model.uploadedIndexCount << ",\n";
        f << indent << "  \"modelVertexLayout\": \"" << model.modelVertexLayout << "\",\n";
        f << indent << "  \"modelBoundsMin\": [" << model.boundsMin[0] << ", " << model.boundsMin[1] << ", " << model.boundsMin[2] << "],\n";
        f << indent << "  \"modelBoundsMax\": [" << model.boundsMax[0] << ", " << model.boundsMax[1] << ", " << model.boundsMax[2] << "],\n";
        f << indent << "  \"modelBoundsCenter\": [" << model.boundsCenter[0] << ", " << model.boundsCenter[1] << ", " << model.boundsCenter[2] << "],\n";
        f << indent << "  \"modelScale\": " << model.modelScale << ",\n";
        f << indent << "  \"modelRenderMode\": \"" << model.modelRenderMode << "\",\n";
        f << indent << "  \"primitiveCountTotal\": " << model.primitiveCountTotal << ",\n";
        f << indent << "  \"primitiveCountRendered\": " << model.primitiveCountRendered << ",\n";
        f << indent << "  \"primitiveCountSkipped\": " << model.primitiveCountSkipped << ",\n";
        f << indent << "  \"unsupportedPrimitiveCount\": " << model.unsupportedPrimitiveCount << ",\n";
        f << indent << "  \"materialSlotCount\": " << model.materialSlotCount << ",\n";
        f << indent << "  \"materialSlotCountRendered\": " << model.materialSlotCountRendered << ",\n";
        f << indent << "  \"textureSlotCount\": " << model.textureSlotCount << ",\n";
        f << indent << "  \"uploadedTextureCount\": " << model.uploadedTextureCount << ",\n";
        f << indent << "  \"textureFallbackCount\": " << model.textureFallbackCount << ",\n";
        f << indent << "  \"skippedTextureCount\": " << model.skippedTextureCount << ",\n";
        f << indent << "  \"textureSlotLimit\": " << model.textureSlotLimit << ",\n";
        f << indent << "  \"pbrMapsStatus\": \"" << escapeJson(model.pbrMapsStatus) << "\",\n";
        f << indent << "  \"metallicRoughnessStatus\": \"" << escapeJson(model.metallicRoughnessStatus) << "\",\n";
        f << indent << "  \"normalMapStatus\": \"" << escapeJson(model.normalMapStatus) << "\",\n";
        f << indent << "  \"normalMapAppliedStatus\": \"" << escapeJson(model.normalMapAppliedStatus) << "\",\n";
        f << indent << "  \"occlusionMapStatus\": \"" << escapeJson(model.occlusionMapStatus) << "\",\n";
        f << indent << "  \"tangentStatus\": \"" << escapeJson(model.tangentStatus) << "\",\n";
        f << indent << "  \"tangentSource\": \"" << escapeJson(model.tangentSource) << "\",\n";
        f << indent << "  \"tangentGeneratedCount\": " << model.tangentGeneratedCount << ",\n";
        f << indent << "  \"tangentFallbackGeneratedCount\": " << model.tangentFallbackGeneratedCount << ",\n";
        f << indent << "  \"tangentMissingCount\": " << model.tangentMissingCount << ",\n";
        f << indent << "  \"tangentDegenerateTriangleCount\": " << model.tangentDegenerateTriangleCount << ",\n";
        f << indent << "  \"tangentFallbackReason\": \"" << escapeJson(model.tangentFallbackReason) << "\",\n";
        f << indent << "  \"tangentBuildMode\": \"" << escapeJson(model.tangentBuildMode) << "\",\n";
        f << indent << "  \"metallicFactor\": " << model.metallicFactor << ",\n";
        f << indent << "  \"roughnessFactor\": " << model.roughnessFactor << ",\n";
        f << indent << "  \"normalScale\": " << model.normalScale << ",\n";
        f << indent << "  \"occlusionStrength\": " << model.occlusionStrength << ",\n";
        f << indent << "  \"pbrTextureSlotCount\": " << model.pbrTextureSlotCount << ",\n";
        f << indent << "  \"uploadedPbrTextureCount\": " << model.uploadedPbrTextureCount << ",\n";
        f << indent << "  \"skippedPbrTextureCount\": " << model.skippedPbrTextureCount << ",\n";
        f << indent << "  \"pbrTextureFallbackCount\": " << model.pbrTextureFallbackCount << ",\n";
        f << indent << "  \"materialSlotDiagnostics\": " << (model.materialSlotDiagnostics.empty() ? "[]" : model.materialSlotDiagnostics) << ",\n";
        f << indent << "  \"glassVisualQualityStatus\": \"" << escapeJson(model.glassVisualQualityStatus) << "\",\n";
        f << indent << "  \"glassGreyPlateFixStatus\": \"" << escapeJson(model.glassGreyPlateFixStatus) << "\",\n";
        f << indent << "  \"glassClarityStatus\": \"" << escapeJson(model.glassClarityStatus) << "\",\n";
        f << indent << "  \"glassCenterTransparencyStatus\": \"" << escapeJson(model.glassCenterTransparencyStatus) << "\",\n";
        f << indent << "  \"glassEdgeHighlightStatus\": \"" << escapeJson(model.glassEdgeReflectionStatus) << "\",\n";
        f << indent << "  \"glassFakeThicknessStatus\": \"" << escapeJson(model.glassFakeThicknessStatus) << "\",\n";
        f << indent << "  \"glassPresetVisualStatus\": \"" << escapeJson(model.glassPresetVisualStatus) << "\",\n";
        f << indent << "  \"glassFallbackMaterialStatus\": \"" << escapeJson(model.glassFallbackMaterialStatus) << "\",\n";
        f << indent << "  \"glassWeakMaterialFallbackStatus\": \"" << escapeJson(model.glassWeakMaterialFallbackStatus) << "\",\n";
        f << indent << "  \"glassNoAssetHardcodeStatus\": \"" << escapeJson(model.glassNoAssetHardcodeStatus) << "\",\n";
        f << indent << "  \"glassPresetCount\": " << model.glassPresetCount << ",\n";
        f << indent << "  \"activeGlassPreset\": \"" << escapeJson(model.activeGlassPreset) << "\",\n";
        f << indent << "  \"glassPresetClearStatus\": \"" << escapeJson(model.glassPresetClearStatus) << "\",\n";
        f << indent << "  \"glassPresetSmokeStatus\": \"" << escapeJson(model.glassPresetSmokeStatus) << "\",\n";
        f << indent << "  \"glassPresetGreenStatus\": \"" << escapeJson(model.glassPresetGreenStatus) << "\",\n";
        f << indent << "  \"glassPresetCrystalStatus\": \"" << escapeJson(model.glassPresetCrystalStatus) << "\",\n";
        f << indent << "  \"glassPresetWarmStatus\": \"" << escapeJson(model.glassPresetWarmStatus) << "\",\n";
        f << indent << "  \"glassPresetDarkStatus\": \"" << escapeJson(model.glassPresetDarkStatus) << "\",\n";
        f << indent << "  \"glassPresetNoTextureDependencyStatus\": \"" << escapeJson(model.glassPresetNoTextureDependencyStatus) << "\",\n";
        f << indent << "  \"transparentGlassQualityStatus\": \"" << escapeJson(model.transparentGlassQualityStatus) << "\",\n";
        f << indent << "  \"transparentGlassCenterAlphaStatus\": \"" << escapeJson(model.transparentGlassCenterAlphaStatus) << "\",\n";
        f << indent << "  \"transparentGlassEdgeAlphaStatus\": \"" << escapeJson(model.transparentGlassEdgeAlphaStatus) << "\",\n";
        f << indent << "  \"transparentGlassDepthBehaviorStatus\": \"" << escapeJson(model.transparentGlassDepthBehaviorStatus) << "\",\n";
        f << indent << "  \"transparentGlassBackgroundVisibilityStatus\": \"" << escapeJson(model.transparentGlassBackgroundVisibilityStatus) << "\",\n";
        f << indent << "  \"transparentGlassInteriorVisibilityStatus\": \"" << escapeJson(model.transparentGlassInteriorVisibilityStatus) << "\",\n";
        f << indent << "  \"transparentGlassBlendPreservedStatus\": \"" << escapeJson(model.transparentGlassBlendPreservedStatus) << "\",\n";
        f << indent << "  \"transparentGlassPassPreservedStatus\": \"" << escapeJson(model.transparentGlassPassPreservedStatus) << "\",\n";
        f << indent << "  \"glassQualityUiStatus\": \"" << escapeJson(model.glassQualityUiStatus) << "\",\n";
        f << indent << "  \"glassClaritySliderStatus\": \"" << escapeJson(model.glassClaritySliderStatus) << "\",\n";
        f << indent << "  \"glassClarityValue\": " << model.glassClarityValue << ",\n";
        f << indent << "  \"glassThicknessSliderStatus\": \"" << escapeJson(model.glassThicknessSliderStatus) << "\",\n";
        f << indent << "  \"glassThicknessValue\": " << model.glassThicknessValue << ",\n";
        f << indent << "  \"glassQualitySummaryUiStatus\": \"" << escapeJson(model.glassQualitySummaryUiStatus) << "\",\n";
        f << indent << "  \"activeGlassSummaryPreservedStatus\": \"" << escapeJson(model.activeGlassSummaryPreservedStatus) << "\",\n";
        f << indent << "  \"glassCenterAlphaDebugViewStatus\": \"" << escapeJson(model.glassCenterAlphaDebugViewStatus) << "\",\n";
        f << indent << "  \"glassEdgeReflectionDebugViewStatus\": \"" << escapeJson(model.glassEdgeReflectionDebugViewStatus) << "\",\n";
        f << indent << "  \"glassThicknessDebugViewStatus\": \"" << escapeJson(model.glassThicknessDebugViewStatus) << "\",\n";
        f << indent << "  \"glassClarityDebugViewStatus\": \"" << escapeJson(model.glassClarityDebugViewStatus) << "\",\n";
        f << indent << "  \"glassFallbackMaterialDebugViewStatus\": \"" << escapeJson(model.glassFallbackMaterialDebugViewStatus) << "\",\n";
        f << indent << "  \"glassFinalCompositeDebugViewStatus\": \"" << escapeJson(model.glassFinalCompositeDebugViewStatus) << "\",\n";
        f << indent << "  \"glassMissingBaseColorFallbackStatus\": \"" << escapeJson(model.glassMissingBaseColorFallbackStatus) << "\",\n";
        f << indent << "  \"glassMissingRoughnessFallbackStatus\": \"" << escapeJson(model.glassMissingRoughnessFallbackStatus) << "\",\n";
        f << indent << "  \"glassOpaqueAlphaModeOverrideStatus\": \"" << escapeJson(model.glassOpaqueAlphaModeOverrideStatus) << "\",\n";
        f << indent << "  \"glassFallbackOpacityStatus\": \"" << escapeJson(model.glassFallbackOpacityStatus) << "\",\n";
        f << indent << "  \"glassFallbackRoughnessStatus\": \"" << escapeJson(model.glassFallbackRoughnessStatus) << "\",\n";
        f << indent << "  \"glassFallbackTintStatus\": \"" << escapeJson(model.glassFallbackTintStatus) << "\",\n";
        f << indent << "  \"p28VisualGlassStatus\": \"" << escapeJson(model.p28VisualGlassStatus) << "\",\n";
        f << indent << "  \"p27bRoutingPreservedStatus\": \"" << escapeJson(model.p27bRoutingPreservedStatus) << "\",\n";
        f << indent << "  \"p28PerformanceStatus\": \"" << escapeJson(model.p28PerformanceStatus) << "\",\n";
        f << indent << "  \"p28NoRaytraceStatus\": \"" << escapeJson(model.p28NoRaytraceStatus) << "\",\n";
        f << indent << "  \"p28NoSsrStatus\": \"" << escapeJson(model.p28NoSsrStatus) << "\",\n";
        f << indent << "  \"p28NoRealMirrorStatus\": \"" << escapeJson(model.p28NoRealMirrorStatus) << "\",\n";
        f << indent << "  \"p28NoRealRefractionStatus\": \"" << escapeJson(model.p28NoRealRefractionStatus) << "\",\n";
        f << indent << "  \"p28NoShadowStatus\": \"" << escapeJson(model.p28NoShadowStatus) << "\",\n";
        f << indent << "  \"p28NoCsmStatus\": \"" << escapeJson(model.p28NoCsmStatus) << "\",\n";
        f << indent << "  \"p28NoOffscreenCubemapStatus\": \"" << escapeJson(model.p28NoOffscreenCubemapStatus) << "\",\n";
        f << indent << "  \"p28NoTextureRebuildStatus\": \"" << escapeJson(model.p28NoTextureRebuildStatus) << "\",\n";
        f << indent << "  \"p28NoModelReuploadStatus\": \"" << escapeJson(model.p28NoModelReuploadStatus) << "\",\n";
        f << indent << "  \"p28NoFrameGlbParseStatus\": \"" << escapeJson(model.p28NoFrameGlbParseStatus) << "\",\n";
        f << indent << "  \"p28NoFrameFileWriteStatus\": \"" << escapeJson(model.p28NoFrameFileWriteStatus) << "\",\n";
        f << indent << "  \"p28UniformOnlyStatus\": \"" << escapeJson(model.p28UniformOnlyStatus) << "\",\n";
        f << indent << "  \"lightingStatus\": \"" << escapeJson(model.lightingStatus) << "\",\n";
        f << indent << "  \"lightingControlStatus\": \"" << escapeJson(model.lightingControlStatus) << "\",\n";
        f << indent << "  \"lightingUiMode\": \"" << escapeJson(model.lightingUiMode) << "\",\n";
        f << indent << "  \"sunDirection\": [" << model.sunDirection[0] << ", " << model.sunDirection[1] << ", " << model.sunDirection[2] << "],\n";
        f << indent << "  \"sunColor\": [" << model.sunColor[0] << ", " << model.sunColor[1] << ", " << model.sunColor[2] << "],\n";
        f << indent << "  \"sunIntensity\": " << model.sunIntensity << ",\n";
        f << indent << "  \"ambientColor\": [" << model.ambientColor[0] << ", " << model.ambientColor[1] << ", " << model.ambientColor[2] << "],\n";
        f << indent << "  \"ambientIntensity\": " << model.ambientIntensity << ",\n";
        f << indent << "  \"lightPreset\": \"" << escapeJson(model.lightPreset) << "\",\n";
        f << indent << "  \"specularBoost\": " << model.specularBoost << ",\n";
        f << indent << "  \"specularBoostStatus\": \"" << escapeJson(model.specularBoostStatus) << "\",\n";
        f << indent << "  \"reflectionIntensity\": " << model.reflectionIntensity << ",\n";
        f << indent << "  \"iblStatus\": \"" << escapeJson(model.iblStatus) << "\",\n";
        f << indent << "  \"iblMode\": \"" << escapeJson(model.iblMode) << "\",\n";
        f << indent << "  \"environmentIblStatus\": \"" << escapeJson(model.environmentIblStatus) << "\",\n";
        f << indent << "  \"environmentIblMode\": \"" << escapeJson(model.environmentIblMode) << "\",\n";
        f << indent << "  \"environmentSourceStatus\": \"" << escapeJson(model.environmentSourceStatus) << "\",\n";
        f << indent << "  \"environmentSourceType\": \"" << escapeJson(model.environmentSourceType) << "\",\n";
        f << indent << "  \"environmentSkyColorStatus\": \"" << escapeJson(model.environmentSkyColorStatus) << "\",\n";
        f << indent << "  \"environmentGroundColorStatus\": \"" << escapeJson(model.environmentGroundColorStatus) << "\",\n";
        f << indent << "  \"environmentHorizonStatus\": \"" << escapeJson(model.environmentHorizonStatus) << "\",\n";
        f << indent << "  \"environmentPerformanceStatus\": \"" << escapeJson(model.environmentPerformanceStatus) << "\",\n";
        f << indent << "  \"iblDiffuseStatus\": \"" << escapeJson(model.iblDiffuseStatus) << "\",\n";
        f << indent << "  \"iblSpecularStatus\": \"" << escapeJson(model.iblSpecularStatus) << "\",\n";
        f << indent << "  \"iblRoughnessResponseStatus\": \"" << escapeJson(model.iblRoughnessResponseStatus) << "\",\n";
        f << indent << "  \"iblMetallicResponseStatus\": \"" << escapeJson(model.iblMetallicResponseStatus) << "\",\n";
        f << indent << "  \"iblDielectricResponseStatus\": \"" << escapeJson(model.iblDielectricResponseStatus) << "\",\n";
        f << indent << "  \"iblFabricPreserveStatus\": \"" << escapeJson(model.iblFabricPreserveStatus) << "\",\n";
        f << indent << "  \"iblOverbrightGuardStatus\": \"" << escapeJson(model.iblOverbrightGuardStatus) << "\",\n";
        f << indent << "  \"environmentUiStatus\": \"" << escapeJson(model.environmentUiStatus) << "\",\n";
        f << indent << "  \"environmentPreset\": \"" << escapeJson(model.environmentPreset) << "\",\n";
        f << indent << "  \"environmentIntensity\": " << model.environmentIntensity << ",\n";
        f << indent << "  \"environmentSliderStatus\": \"" << escapeJson(model.environmentSliderStatus) << "\",\n";
        f << indent << "  \"skyPresetStatus\": \"" << escapeJson(model.skyPresetStatus) << "\",\n";
        f << indent << "  \"horizonControlStatus\": \"" << escapeJson(model.horizonControlStatus) << "\",\n";
        f << indent << "  \"environmentUniformUpdateStatus\": \"" << escapeJson(model.environmentUniformUpdateStatus) << "\",\n";
        f << indent << "  \"environmentDebugViewStatus\": \"" << escapeJson(model.environmentDebugViewStatus) << "\",\n";
        f << indent << "  \"reflectionDirectionDebugViewStatus\": \"" << escapeJson(model.reflectionDirectionDebugViewStatus) << "\",\n";
        f << indent << "  \"environmentColorDebugViewStatus\": \"" << escapeJson(model.environmentColorDebugViewStatus) << "\",\n";
        f << indent << "  \"iblPerformanceStatus\": \"" << escapeJson(model.iblPerformanceStatus) << "\",\n";
        f << indent << "  \"reflectionFoundationStatus\": \"" << escapeJson(model.reflectionFoundationStatus) << "\",\n";
        f << indent << "  \"reflectionMode\": \"" << escapeJson(model.reflectionMode) << "\",\n";
        f << indent << "  \"environmentReflectionStatus\": \"" << escapeJson(model.environmentReflectionStatus) << "\",\n";
        f << indent << "  \"environmentReflectionMode\": \"" << escapeJson(model.environmentReflectionMode) << "\",\n";
        f << indent << "  \"environmentSource\": \"" << escapeJson(model.environmentSource) << "\",\n";
        f << indent << "  \"reflectionColorStatus\": \"" << escapeJson(model.reflectionColorStatus) << "\",\n";
        f << indent << "  \"reflectionRoughnessResponseStatus\": \"" << escapeJson(model.reflectionRoughnessResponseStatus) << "\",\n";
        f << indent << "  \"metallicReflectionStatus\": \"" << escapeJson(model.metallicReflectionStatus) << "\",\n";
        f << indent << "  \"dielectricReflectionStatus\": \"" << escapeJson(model.dielectricReflectionStatus) << "\",\n";
        f << indent << "  \"reflectionPerformanceStatus\": \"" << escapeJson(model.reflectionPerformanceStatus) << "\",\n";
        f << indent << "  \"inspectorUiStatus\": \"" << escapeJson(model.inspectorUiStatus) << "\",\n";
        f << indent << "  \"inspectorUiMode\": \"" << escapeJson(model.inspectorUiMode) << "\",\n";
        f << indent << "  \"activeInspectorTab\": \"" << escapeJson(model.activeInspectorTab) << "\",\n";
        f << indent << "  \"assetsTabStatus\": \"" << escapeJson(model.assetsTabStatus) << "\",\n";
        f << indent << "  \"cameraTabStatus\": \"" << escapeJson(model.cameraTabStatus) << "\",\n";
        f << indent << "  \"lightingTabStatus\": \"" << escapeJson(model.lightingTabStatus) << "\",\n";
        f << indent << "  \"materialTabStatus\": \"" << escapeJson(model.materialTabStatus) << "\",\n";
        f << indent << "  \"debugTabStatus\": \"" << escapeJson(model.debugTabStatus) << "\",\n";
        f << indent << "  \"contactGroundingStatus\": \"" << escapeJson(model.contactGroundingStatus) << "\",\n";
        f << indent << "  \"contactShadowStatus\": \"" << escapeJson(model.contactShadowStatus) << "\",\n";
        f << indent << "  \"contactShadowMode\": \"" << escapeJson(model.contactShadowMode) << "\",\n";
        f << indent << "  \"contactShadowIntensity\": " << model.contactShadowIntensity << ",\n";
        f << indent << "  \"contactShadowPerformanceStatus\": \"" << escapeJson(model.contactShadowPerformanceStatus) << "\",\n";
        f << indent << "  \"groundingUsesModelBounds\": \"" << escapeJson(model.groundingUsesModelBounds) << "\",\n";
        f << indent << "  \"groundingUniformUpdateStatus\": \"" << escapeJson(model.groundingUniformUpdateStatus) << "\",\n";
        f << indent << "  \"groundSliderStatus\": \"" << escapeJson(model.groundSliderStatus) << "\",\n";
        f << indent << "  \"contactGroundingSliderStatus\": \"" << escapeJson(model.contactGroundingSliderStatus) << "\",\n";
        f << indent << "  \"lightingUniformUpdateStatus\": \"" << escapeJson(model.lightingUniformUpdateStatus) << "\",\n";
        f << indent << "  \"sliderUpdateMode\": \"" << escapeJson(model.sliderUpdateMode) << "\",\n";
        f << indent << "  \"sliderTouchStatus\": \"" << escapeJson(model.sliderTouchStatus) << "\",\n";
        f << indent << "  \"sunSliderStatus\": \"" << escapeJson(model.sunSliderStatus) << "\",\n";
        f << indent << "  \"ambientSliderStatus\": \"" << escapeJson(model.ambientSliderStatus) << "\",\n";
        f << indent << "  \"exposureSliderStatus\": \"" << escapeJson(model.exposureSliderStatus) << "\",\n";
        f << indent << "  \"specularSliderStatus\": \"" << escapeJson(model.specularSliderStatus) << "\",\n";
        f << indent << "  \"reflectionSliderStatus\": \"" << escapeJson(model.reflectionSliderStatus) << "\",\n";
        f << indent << "  \"brdfStatus\": \"" << escapeJson(model.brdfStatus) << "\",\n";
        f << indent << "  \"brdfMode\": \"" << escapeJson(model.brdfMode) << "\",\n";
        f << indent << "  \"diffuseStatus\": \"" << escapeJson(model.diffuseStatus) << "\",\n";
        f << indent << "  \"specularStatus\": \"" << escapeJson(model.specularStatus) << "\",\n";
        f << indent << "  \"fresnelStatus\": \"" << escapeJson(model.fresnelStatus) << "\",\n";
        f << indent << "  \"f0Status\": \"" << escapeJson(model.f0Status) << "\",\n";
        f << indent << "  \"metallicResponseStatus\": \"" << escapeJson(model.metallicResponseStatus) << "\",\n";
        f << indent << "  \"roughnessResponseStatus\": \"" << escapeJson(model.roughnessResponseStatus) << "\",\n";
        f << indent << "  \"directLightingStatus\": \"" << escapeJson(model.directLightingStatus) << "\",\n";
        f << indent << "  \"materialResponseStatus\": \"" << escapeJson(model.materialResponseStatus) << "\",\n";
        f << indent << "  \"pbrQualityTier\": \"" << escapeJson(model.pbrQualityTier) << "\",\n";
        f << indent << "  \"brdfPerformanceStatus\": \"" << escapeJson(model.brdfPerformanceStatus) << "\",\n";
        f << indent << "  \"toneMappingStatus\": \"" << escapeJson(model.toneMappingStatus) << "\",\n";
        f << indent << "  \"toneMappingMode\": \"" << escapeJson(model.toneMappingMode) << "\",\n";
        f << indent << "  \"exposureStatus\": \"" << escapeJson(model.exposureStatus) << "\",\n";
        f << indent << "  \"exposureValue\": " << model.exposureValue << ",\n";
        f << indent << "  \"ambientFloor\": " << model.ambientFloor << ",\n";
        f << indent << "  \"brightnessPreset\": \"" << escapeJson(model.brightnessPreset) << "\",\n";
        f << indent << "  \"activeDebugView\": \"" << escapeJson(model.activeDebugView) << "\",\n";
        f << indent << "  \"debugViewStatus\": \"" << escapeJson(model.debugViewStatus) << "\",\n";
        f << indent << "  \"normalDebugViewStatus\": \"" << escapeJson(model.normalDebugViewStatus) << "\",\n";
        f << indent << "  \"ndotlDebugViewStatus\": \"" << escapeJson(model.ndotlDebugViewStatus) << "\",\n";
        f << indent << "  \"diffuseDebugViewStatus\": \"" << escapeJson(model.diffuseDebugViewStatus) << "\",\n";
        f << indent << "  \"specularDebugViewStatus\": \"" << escapeJson(model.specularDebugViewStatus) << "\",\n";
        f << indent << "  \"f0DebugViewStatus\": \"" << escapeJson(model.f0DebugViewStatus) << "\",\n";
        f << indent << "  \"reflectionDebugViewStatus\": \"" << escapeJson(model.reflectionDebugViewStatus) << "\",\n";
        f << indent << "  \"iblDiffuseDebugViewStatus\": \"" << escapeJson(model.iblDiffuseDebugViewStatus) << "\",\n";
        f << indent << "  \"iblSpecularDebugViewStatus\": \"" << escapeJson(model.iblSpecularDebugViewStatus) << "\",\n";
        f << indent << "  \"brdfStatusDebugViewStatus\": \"" << escapeJson(model.brdfStatusDebugViewStatus) << "\",\n";
        f << indent << "  \"groundingDebugViewStatus\": \"" << escapeJson(model.groundingDebugViewStatus) << "\",\n";
        f << indent << "  \"materialCalibrationStatus\": \"" << escapeJson(model.materialCalibrationStatus) << "\",\n";
        f << indent << "  \"materialCalibrationMode\": \"" << escapeJson(model.materialCalibrationMode) << "\",\n";
        f << indent << "  \"albedoEnergyStatus\": \"" << escapeJson(model.albedoEnergyStatus) << "\",\n";
        f << indent << "  \"albedoClampStatus\": \"" << escapeJson(model.albedoClampStatus) << "\",\n";
        f << indent << "  \"diffuseClampStatus\": \"" << escapeJson(model.diffuseClampStatus) << "\",\n";
        f << indent << "  \"luminanceGuardStatus\": \"" << escapeJson(model.luminanceGuardStatus) << "\",\n";
        f << indent << "  \"aoCalibrationStatus\": \"" << escapeJson(model.aoCalibrationStatus) << "\",\n";
        f << indent << "  \"roughnessRemapStatus\": \"" << escapeJson(model.roughnessRemapStatus) << "\",\n";
        f << indent << "  \"metallicRoughnessClampStatus\": \"" << escapeJson(model.metallicRoughnessClampStatus) << "\",\n";
        f << indent << "  \"emissiveGuardStatus\": \"" << escapeJson(model.emissiveGuardStatus) << "\",\n";
        f << indent << "  \"fabricMattePreserveStatus\": \"" << escapeJson(model.fabricMattePreserveStatus) << "\",\n";
        f << indent << "  \"paintMaterialCalibrationStatus\": \"" << escapeJson(model.paintMaterialCalibrationStatus) << "\",\n";
        f << indent << "  \"metalMaterialCalibrationStatus\": \"" << escapeJson(model.metalMaterialCalibrationStatus) << "\",\n";
        f << indent << "  \"materialTypeHintStatus\": \"" << escapeJson(model.materialTypeHintStatus) << "\",\n";
        f << indent << "  \"materialSlotCalibrationStatus\": \"" << escapeJson(model.materialSlotCalibrationStatus) << "\",\n";
        f << indent << "  \"calibrationUiStatus\": \"" << escapeJson(model.calibrationUiStatus) << "\",\n";
        f << indent << "  \"calibrationPreset\": \"" << escapeJson(model.calibrationPreset) << "\",\n";
        f << indent << "  \"calibrationSliderStatus\": \"" << escapeJson(model.calibrationSliderStatus) << "\",\n";
        f << indent << "  \"calibrationSliderValue\": " << model.calibrationSliderValue << ",\n";
        f << indent << "  \"calibrationUniformUpdateStatus\": \"" << escapeJson(model.calibrationUniformUpdateStatus) << "\",\n";
        f << indent << "  \"calibratedAlbedoDebugViewStatus\": \"" << escapeJson(model.calibratedAlbedoDebugViewStatus) << "\",\n";
        f << indent << "  \"materialTypeDebugViewStatus\": \"" << escapeJson(model.materialTypeDebugViewStatus) << "\",\n";
        f << indent << "  \"aoInfluenceDebugViewStatus\": \"" << escapeJson(model.aoInfluenceDebugViewStatus) << "\",\n";
        f << indent << "  \"luminanceGuardDebugViewStatus\": \"" << escapeJson(model.luminanceGuardDebugViewStatus) << "\",\n";
        f << indent << "  \"calibrationVisualStrength\": " << model.calibrationVisualStrength << ",\n";
        f << indent << "  \"calibrationAffectsAlbedo\": \"" << escapeJson(model.calibrationAffectsAlbedo) << "\",\n";
        f << indent << "  \"calibrationAffectsAo\": \"" << escapeJson(model.calibrationAffectsAo) << "\",\n";
        f << indent << "  \"calibrationAffectsRoughness\": \"" << escapeJson(model.calibrationAffectsRoughness) << "\",\n";
        f << indent << "  \"calibrationVisibleResponseStatus\": \"" << escapeJson(model.calibrationVisibleResponseStatus) << "\",\n";
        f << indent << "  \"materialCalibrationPerformanceStatus\": \"" << escapeJson(model.materialCalibrationPerformanceStatus) << "\",\n";
        f << indent << "  \"specularGlossStatus\": \"" << escapeJson(model.specularGlossStatus) << "\",\n";
        f << indent << "  \"specularGlossMode\": \"" << escapeJson(model.specularGlossMode) << "\",\n";
        f << indent << "  \"specularResponseStatus\": \"" << escapeJson(model.specularResponseStatus) << "\",\n";
        f << indent << "  \"glossResponseStatus\": \"" << escapeJson(model.glossResponseStatus) << "\",\n";
        f << indent << "  \"roughnessRemapV2Status\": \"" << escapeJson(model.roughnessRemapV2Status) << "\",\n";
        f << indent << "  \"metallicSpecularBoostStatus\": \"" << escapeJson(model.metallicSpecularBoostStatus) << "\",\n";
        f << indent << "  \"dielectricGlossStatus\": \"" << escapeJson(model.dielectricGlossStatus) << "\",\n";
        f << indent << "  \"fabricSpecularSuppressStatus\": \"" << escapeJson(model.fabricSpecularSuppressStatus) << "\",\n";
        f << indent << "  \"specularOverbrightGuardStatus\": \"" << escapeJson(model.specularOverbrightGuardStatus) << "\",\n";
        f << indent << "  \"viewDependentHighlightStatus\": \"" << escapeJson(model.viewDependentHighlightStatus) << "\",\n";
        f << indent << "  \"paintGlossLiteStatus\": \"" << escapeJson(model.paintGlossLiteStatus) << "\",\n";
        f << indent << "  \"paintGlossLiteMode\": \"" << escapeJson(model.paintGlossLiteMode) << "\",\n";
        f << indent << "  \"paintGlossIntensity\": " << model.paintGlossIntensity << ",\n";
        f << indent << "  \"paintGlossRoughness\": " << model.paintGlossRoughness << ",\n";
        f << indent << "  \"paintGlossMaterialHintStatus\": \"" << escapeJson(model.paintGlossMaterialHintStatus) << "\",\n";
        f << indent << "  \"paintGlossPerformanceStatus\": \"" << escapeJson(model.paintGlossPerformanceStatus) << "\",\n";
        f << indent << "  \"paintGlossTargetStatus\": \"" << escapeJson(model.paintGlossTargetStatus) << "\",\n";
        f << indent << "  \"paintGlossAppliedMaterialCount\": " << model.paintGlossAppliedMaterialCount << ",\n";
        f << indent << "  \"paintGlossSkippedFabricCount\": " << model.paintGlossSkippedFabricCount << ",\n";
        f << indent << "  \"paintGlossFallbackRouting\": \"" << escapeJson(model.paintGlossFallbackRouting) << "\",\n";
        f << indent << "  \"paintGlossVisibleResponseStatus\": \"" << escapeJson(model.paintGlossVisibleResponseStatus) << "\",\n";
        f << indent << "  \"glossSliderStatus\": \"" << escapeJson(model.glossSliderStatus) << "\",\n";
        f << indent << "  \"glossSliderValue\": " << model.glossSliderValue << ",\n";
        f << indent << "  \"paintGlossSliderStatus\": \"" << escapeJson(model.paintGlossSliderStatus) << "\",\n";
        f << indent << "  \"paintGlossSliderValue\": " << model.paintGlossSliderValue << ",\n";
        f << indent << "  \"glossUniformUpdateStatus\": \"" << escapeJson(model.glossUniformUpdateStatus) << "\",\n";
        f << indent << "  \"glossResponseDebugViewStatus\": \"" << escapeJson(model.glossResponseDebugViewStatus) << "\",\n";
        f << indent << "  \"specularGuardDebugViewStatus\": \"" << escapeJson(model.specularGuardDebugViewStatus) << "\",\n";
        f << indent << "  \"paintGlossDebugViewStatus\": \"" << escapeJson(model.paintGlossDebugViewStatus) << "\",\n";
        f << indent << "  \"metalResponseDebugViewStatus\": \"" << escapeJson(model.metalResponseDebugViewStatus) << "\",\n";
        f << indent << "  \"paintTargetDebugViewStatus\": \"" << escapeJson(model.paintTargetDebugViewStatus) << "\",\n";
        f << indent << "  \"calibrationResponseDebugViewStatus\": \"" << escapeJson(model.calibrationResponseDebugViewStatus) << "\",\n";
        f << indent << "  \"materialTypeSpecularRoutingStatus\": \"" << escapeJson(model.materialTypeSpecularRoutingStatus) << "\",\n";
        f << indent << "  \"paintMaterialGlossStatus\": \"" << escapeJson(model.paintMaterialGlossStatus) << "\",\n";
        f << indent << "  \"metalMaterialGlossStatus\": \"" << escapeJson(model.metalMaterialGlossStatus) << "\",\n";
        f << indent << "  \"rubberMaterialGlossStatus\": \"" << escapeJson(model.rubberMaterialGlossStatus) << "\",\n";
        f << indent << "  \"specularGlossPerformanceStatus\": \"" << escapeJson(model.specularGlossPerformanceStatus) << "\",\n";
        f << indent << "  \"glossVisibleResponseStatus\": \"" << escapeJson(model.glossVisibleResponseStatus) << "\",\n";
        f << indent << "  \"glossAffectsSpecularLobe\": \"" << escapeJson(model.glossAffectsSpecularLobe) << "\",\n";
        f << indent << "  \"glossAffectsReflectionWeight\": \"" << escapeJson(model.glossAffectsReflectionWeight) << "\",\n";
        f << indent << "  \"materialSlotEditorStatus\": \"" << escapeJson(model.materialSlotEditorStatus) << "\",\n";
        f << indent << "  \"selectedMaterialSlot\": " << model.selectedMaterialSlot << ",\n";
        f << indent << "  \"selectedMaterialSlotCount\": " << model.selectedMaterialSlotCount << ",\n";
        f << indent << "  \"selectedMaterialTypeHint\": \"" << escapeJson(model.selectedMaterialTypeHint) << "\",\n";
        f << indent << "  \"selectedMaterialName\": \"" << escapeJson(model.selectedMaterialName) << "\",\n";
        f << indent << "  \"selectedMaterialSummaryStatus\": \"" << escapeJson(model.selectedMaterialSummaryStatus) << "\",\n";
        f << indent << "  \"materialSlotSelectionUiStatus\": \"" << escapeJson(model.materialSlotSelectionUiStatus) << "\",\n";
        f << indent << "  \"perMaterialOverrideStatus\": \"" << escapeJson(model.perMaterialOverrideStatus) << "\",\n";
        f << indent << "  \"perMaterialOverrideMode\": \"" << escapeJson(model.perMaterialOverrideMode) << "\",\n";
        f << indent << "  \"selectedSlotMetallicOverride\": " << model.selectedSlotMetallicOverride << ",\n";
        f << indent << "  \"selectedSlotRoughnessOverride\": " << model.selectedSlotRoughnessOverride << ",\n";
        f << indent << "  \"selectedSlotNormalScaleOverride\": " << model.selectedSlotNormalScaleOverride << ",\n";
        f << indent << "  \"selectedSlotAoOverride\": " << model.selectedSlotAoOverride << ",\n";
        f << indent << "  \"selectedSlotGlossOverride\": " << model.selectedSlotGlossOverride << ",\n";
        f << indent << "  \"selectedSlotCoatOverride\": " << model.selectedSlotCoatOverride << ",\n";
        f << indent << "  \"selectedSlotOverrideApplied\": \"" << escapeJson(model.selectedSlotOverrideApplied) << "\",\n";
        f << indent << "  \"selectedSlotResetStatus\": \"" << escapeJson(model.selectedSlotResetStatus) << "\",\n";
        f << indent << "  \"perMaterialUniformUpdateStatus\": \"" << escapeJson(model.perMaterialUniformUpdateStatus) << "\",\n";
        f << indent << "  \"materialSlotControlsUiStatus\": \"" << escapeJson(model.materialSlotControlsUiStatus) << "\",\n";
        f << indent << "  \"metallicSlotSliderStatus\": \"" << escapeJson(model.metallicSlotSliderStatus) << "\",\n";
        f << indent << "  \"roughnessSlotSliderStatus\": \"" << escapeJson(model.roughnessSlotSliderStatus) << "\",\n";
        f << indent << "  \"normalSlotSliderStatus\": \"" << escapeJson(model.normalSlotSliderStatus) << "\",\n";
        f << indent << "  \"aoSlotSliderStatus\": \"" << escapeJson(model.aoSlotSliderStatus) << "\",\n";
        f << indent << "  \"selectedMaterialDebugViewStatus\": \"" << escapeJson(model.selectedMaterialDebugViewStatus) << "\",\n";
        f << indent << "  \"materialOverrideDebugViewStatus\": \"" << escapeJson(model.materialOverrideDebugViewStatus) << "\",\n";
        f << indent << "  \"slotMetallicDebugViewStatus\": \"" << escapeJson(model.slotMetallicDebugViewStatus) << "\",\n";
        f << indent << "  \"slotRoughnessDebugViewStatus\": \"" << escapeJson(model.slotRoughnessDebugViewStatus) << "\",\n";
        f << indent << "  \"slotAoDebugViewStatus\": \"" << escapeJson(model.slotAoDebugViewStatus) << "\",\n";
        f << indent << "  \"perMaterialOverridePerformanceStatus\": \"" << escapeJson(model.perMaterialOverridePerformanceStatus) << "\",\n";
        f << indent << "  \"alphaMaterialStatus\": \"" << escapeJson(model.alphaMaterialStatus) << "\",\n";
        f << indent << "  \"alphaModeSupportStatus\": \"" << escapeJson(model.alphaModeSupportStatus) << "\",\n";
        f << indent << "  \"alphaMaskStatus\": \"" << escapeJson(model.alphaMaskStatus) << "\",\n";
        f << indent << "  \"alphaBlendStatus\": \"" << escapeJson(model.alphaBlendStatus) << "\",\n";
        f << indent << "  \"alphaCutoffStatus\": \"" << escapeJson(model.alphaCutoffStatus) << "\",\n";
        f << indent << "  \"alphaCutoffValue\": " << model.alphaCutoffValue << ",\n";
        f << indent << "  \"alphaDiscardStatus\": \"" << escapeJson(model.alphaDiscardStatus) << "\",\n";
        f << indent << "  \"alphaTextureChannelStatus\": \"" << escapeJson(model.alphaTextureChannelStatus) << "\",\n";
        f << indent << "  \"alphaFallbackStatus\": \"" << escapeJson(model.alphaFallbackStatus) << "\",\n";
        f << indent << "  \"doubleSidedMaterialStatus\": \"" << escapeJson(model.doubleSidedMaterialStatus) << "\",\n";
        f << indent << "  \"doubleSidedMode\": \"" << escapeJson(model.doubleSidedMode) << "\",\n";
        f << indent << "  \"doubleSidedNormalStatus\": \"" << escapeJson(model.doubleSidedNormalStatus) << "\",\n";
        f << indent << "  \"doubleSidedRasterStatus\": \"" << escapeJson(model.doubleSidedRasterStatus) << "\",\n";
        f << indent << "  \"doubleSidedFallbackStatus\": \"" << escapeJson(model.doubleSidedFallbackStatus) << "\",\n";
        f << indent << "  \"thinMaterialPolishStatus\": \"" << escapeJson(model.thinMaterialPolishStatus) << "\",\n";
        f << indent << "  \"cutoutMaterialHintStatus\": \"" << escapeJson(model.cutoutMaterialHintStatus) << "\",\n";
        f << indent << "  \"fabricEdgeStatus\": \"" << escapeJson(model.fabricEdgeStatus) << "\",\n";
        f << indent << "  \"glassMetadataStatus\": \"" << escapeJson(model.glassMetadataStatus) << "\",\n";
        f << indent << "  \"decalMaterialHintStatus\": \"" << escapeJson(model.decalMaterialHintStatus) << "\",\n";
        f << indent << "  \"transparencyDeferredStatus\": \"" << escapeJson(model.transparencyDeferredStatus) << "\",\n";
        f << indent << "  \"alphaUiStatus\": \"" << escapeJson(model.alphaUiStatus) << "\",\n";
        f << indent << "  \"alphaCutoffSliderStatus\": \"" << escapeJson(model.alphaCutoffSliderStatus) << "\",\n";
        f << indent << "  \"alphaDebugViewStatus\": \"" << escapeJson(model.alphaDebugViewStatus) << "\",\n";
        f << indent << "  \"doubleSidedDebugViewStatus\": \"" << escapeJson(model.doubleSidedDebugViewStatus) << "\",\n";
        f << indent << "  \"alphaResetButtonStatus\": \"" << escapeJson(model.alphaResetButtonStatus) << "\",\n";
        f << indent << "  \"alphaUniformUpdateStatus\": \"" << escapeJson(model.alphaUniformUpdateStatus) << "\",\n";
        f << indent << "  \"alphaSliderUpdateMode\": \"" << escapeJson(model.alphaSliderUpdateMode) << "\",\n";
        f << indent << "  \"alphaMaskDebugViewStatus\": \"" << escapeJson(model.alphaMaskDebugViewStatus) << "\",\n";
        f << indent << "  \"alphaModeDebugViewStatus\": \"" << escapeJson(model.alphaModeDebugViewStatus) << "\",\n";
        f << indent << "  \"cutoutHintDebugViewStatus\": \"" << escapeJson(model.cutoutHintDebugViewStatus) << "\",\n";
        f << indent << "  \"transparencyStatusDebugViewStatus\": \"" << escapeJson(model.transparencyStatusDebugViewStatus) << "\",\n";
        f << indent << "  \"alphaPerformanceStatus\": \"" << escapeJson(model.alphaPerformanceStatus) << "\",\n";
        f << indent << "  \"alphaNoNewPassStatus\": \"" << escapeJson(model.alphaNoNewPassStatus) << "\",\n";
        f << indent << "  \"alphaNoTextureRebuildStatus\": \"" << escapeJson(model.alphaNoTextureRebuildStatus) << "\",\n";
        f << indent << "  \"alphaNoModelReuploadStatus\": \"" << escapeJson(model.alphaNoModelReuploadStatus) << "\",\n";
        f << indent << "  \"p20RuntimeWorkflowPreservedStatus\": \"" << escapeJson(model.p20RuntimeWorkflowPreservedStatus) << "\",\n";
        f << indent << "  \"p19SlotControlsPreservedStatus\": \"" << escapeJson(model.p19SlotControlsPreservedStatus) << "\",\n";
        f << indent << "  \"p21AlphaPreservedStatus\": \"" << escapeJson(model.p21AlphaPreservedStatus) << "\",\n";
        f << indent << "  \"emissiveMaterialStatus\": \"" << escapeJson(model.emissiveMaterialStatus) << "\",\n";
        f << indent << "  \"emissiveMode\": \"" << escapeJson(model.emissiveMode) << "\",\n";
        f << indent << "  \"emissiveFactorStatus\": \"" << escapeJson(model.emissiveFactorStatus) << "\",\n";
        f << indent << "  \"emissiveTextureStatus\": \"" << escapeJson(model.emissiveTextureStatus) << "\",\n";
        f << indent << "  \"emissiveIntensity\": " << model.emissiveIntensity << ",\n";
        f << indent << "  \"emissiveIntensityStatus\": \"" << escapeJson(model.emissiveIntensityStatus) << "\",\n";
        f << indent << "  \"emissiveColorStatus\": \"" << escapeJson(model.emissiveColorStatus) << "\",\n";
        f << indent << "  \"emissiveOverbrightGuardStatus\": \"" << escapeJson(model.emissiveOverbrightGuardStatus) << "\",\n";
        f << indent << "  \"emissiveLightingContributionStatus\": \"" << escapeJson(model.emissiveLightingContributionStatus) << "\",\n";
        f << indent << "  \"emissivePerformanceStatus\": \"" << escapeJson(model.emissivePerformanceStatus) << "\",\n";
        f << indent << "  \"materialPresetStatus\": \"" << escapeJson(model.materialPresetStatus) << "\",\n";
        f << indent << "  \"activeMaterialPreset\": \"" << escapeJson(model.activeMaterialPreset) << "\",\n";
        f << indent << "  \"materialPresetMode\": \"" << escapeJson(model.materialPresetMode) << "\",\n";
        f << indent << "  \"materialPresetAppliedSlot\": " << model.materialPresetAppliedSlot << ",\n";
        f << indent << "  \"materialPresetAppliedStatus\": \"" << escapeJson(model.materialPresetAppliedStatus) << "\",\n";
        f << indent << "  \"materialPresetUiStatus\": \"" << escapeJson(model.materialPresetUiStatus) << "\",\n";
        f << indent << "  \"materialPresetPerformanceStatus\": \"" << escapeJson(model.materialPresetPerformanceStatus) << "\",\n";
        f << indent << "  \"selectedSlotPresetStatus\": \"" << escapeJson(model.selectedSlotPresetStatus) << "\",\n";
        f << indent << "  \"carPaintPresetStatus\": \"" << escapeJson(model.carPaintPresetStatus) << "\",\n";
        f << indent << "  \"metalPresetStatus\": \"" << escapeJson(model.metalPresetStatus) << "\",\n";
        f << indent << "  \"fabricPresetStatus\": \"" << escapeJson(model.fabricPresetStatus) << "\",\n";
        f << indent << "  \"rubberPresetStatus\": \"" << escapeJson(model.rubberPresetStatus) << "\",\n";
        f << indent << "  \"plasticPresetStatus\": \"" << escapeJson(model.plasticPresetStatus) << "\",\n";
        f << indent << "  \"glassMetadataPresetStatus\": \"" << escapeJson(model.glassMetadataPresetStatus) << "\",\n";
        f << indent << "  \"emissivePresetStatus\": \"" << escapeJson(model.emissivePresetStatus) << "\",\n";
        f << indent << "  \"materialPresetGuardStatus\": \"" << escapeJson(model.materialPresetGuardStatus) << "\",\n";
        f << indent << "  \"presetCycleButtonStatus\": \"" << escapeJson(model.presetCycleButtonStatus) << "\",\n";
        f << indent << "  \"presetApplyButtonStatus\": \"" << escapeJson(model.presetApplyButtonStatus) << "\",\n";
        f << indent << "  \"emissiveSliderStatus\": \"" << escapeJson(model.emissiveSliderStatus) << "\",\n";
        f << indent << "  \"emissiveUniformUpdateStatus\": \"" << escapeJson(model.emissiveUniformUpdateStatus) << "\",\n";
        f << indent << "  \"materialResetButtonStatus\": \"" << escapeJson(model.materialResetButtonStatus) << "\",\n";
        f << indent << "  \"materialUiScrollPreservedStatus\": \"" << escapeJson(model.materialUiScrollPreservedStatus) << "\",\n";
        f << indent << "  \"emissiveDebugViewStatus\": \"" << escapeJson(model.emissiveDebugViewStatus) << "\",\n";
        f << indent << "  \"presetTypeDebugViewStatus\": \"" << escapeJson(model.presetTypeDebugViewStatus) << "\",\n";
        f << indent << "  \"presetResponseDebugViewStatus\": \"" << escapeJson(model.presetResponseDebugViewStatus) << "\",\n";
        f << indent << "  \"materialEnergyGuardDebugViewStatus\": \"" << escapeJson(model.materialEnergyGuardDebugViewStatus) << "\",\n";
        f << indent << "  \"selectedSlotPresetDebugViewStatus\": \"" << escapeJson(model.selectedSlotPresetDebugViewStatus) << "\",\n";
        f << indent << "  \"p22PerformanceStatus\": \"" << escapeJson(model.p22PerformanceStatus) << "\",\n";
        f << indent << "  \"emissiveNoBloomStatus\": \"" << escapeJson(model.emissiveNoBloomStatus) << "\",\n";
        f << indent << "  \"emissiveNoNewPassStatus\": \"" << escapeJson(model.emissiveNoNewPassStatus) << "\",\n";
        f << indent << "  \"presetNoModelReuploadStatus\": \"" << escapeJson(model.presetNoModelReuploadStatus) << "\",\n";
        f << indent << "  \"presetNoTextureRebuildStatus\": \"" << escapeJson(model.presetNoTextureRebuildStatus) << "\",\n";
        f << indent << "  \"clearcoatStatus\": \"" << escapeJson(model.clearcoatStatus) << "\",\n";
        f << indent << "  \"clearcoatMode\": \"" << escapeJson(model.clearcoatMode) << "\",\n";
        f << indent << "  \"clearcoatIntensity\": " << model.clearcoatIntensity << ",\n";
        f << indent << "  \"clearcoatRoughness\": " << model.clearcoatRoughness << ",\n";
        f << indent << "  \"clearcoatFresnelStatus\": \"" << escapeJson(model.clearcoatFresnelStatus) << "\",\n";
        f << indent << "  \"clearcoatHighlightStatus\": \"" << escapeJson(model.clearcoatHighlightStatus) << "\",\n";
        f << indent << "  \"clearcoatMaterialRoutingStatus\": \"" << escapeJson(model.clearcoatMaterialRoutingStatus) << "\",\n";
        f << indent << "  \"clearcoatOverbrightGuardStatus\": \"" << escapeJson(model.clearcoatOverbrightGuardStatus) << "\",\n";
        f << indent << "  \"clearcoatPerformanceStatus\": \"" << escapeJson(model.clearcoatPerformanceStatus) << "\",\n";
        f << indent << "  \"carPaintLayerStatus\": \"" << escapeJson(model.carPaintLayerStatus) << "\",\n";
        f << indent << "  \"carPaintPresetV2Status\": \"" << escapeJson(model.carPaintPresetV2Status) << "\",\n";
        f << indent << "  \"carPaintClearcoatStatus\": \"" << escapeJson(model.carPaintClearcoatStatus) << "\",\n";
        f << indent << "  \"paintLayerEnergyGuardStatus\": \"" << escapeJson(model.paintLayerEnergyGuardStatus) << "\",\n";
        f << indent << "  \"paintLayerMaterialHintStatus\": \"" << escapeJson(model.paintLayerMaterialHintStatus) << "\",\n";
        f << indent << "  \"clearcoatSliderStatus\": \"" << escapeJson(model.clearcoatSliderStatus) << "\",\n";
        f << indent << "  \"clearcoatSliderValue\": " << model.clearcoatSliderValue << ",\n";
        f << indent << "  \"clearcoatRoughnessSliderStatus\": \"" << escapeJson(model.clearcoatRoughnessSliderStatus) << "\",\n";
        f << indent << "  \"clearcoatRoughnessSliderValue\": " << model.clearcoatRoughnessSliderValue << ",\n";
        f << indent << "  \"clearcoatUniformUpdateStatus\": \"" << escapeJson(model.clearcoatUniformUpdateStatus) << "\",\n";
        f << indent << "  \"clearcoatUiStatus\": \"" << escapeJson(model.clearcoatUiStatus) << "\",\n";
        f << indent << "  \"clearcoatDebugViewStatus\": \"" << escapeJson(model.clearcoatDebugViewStatus) << "\",\n";
        f << indent << "  \"clearcoatHighlightDebugViewStatus\": \"" << escapeJson(model.clearcoatHighlightDebugViewStatus) << "\",\n";
        f << indent << "  \"paintLayerDebugViewStatus\": \"" << escapeJson(model.paintLayerDebugViewStatus) << "\",\n";
        f << indent << "  \"paintEnergyGuardDebugViewStatus\": \"" << escapeJson(model.paintEnergyGuardDebugViewStatus) << "\",\n";
        f << indent << "  \"p22EmissivePreservedStatus\": \"" << escapeJson(model.p22EmissivePreservedStatus) << "\",\n";
        f << indent << "  \"p22PresetsPreservedStatus\": \"" << escapeJson(model.p22PresetsPreservedStatus) << "\",\n";
        f << indent << "  \"p23PerformanceStatus\": \"" << escapeJson(model.p23PerformanceStatus) << "\",\n";
        f << indent << "  \"clearcoatNoNewPassStatus\": \"" << escapeJson(model.clearcoatNoNewPassStatus) << "\",\n";
        f << indent << "  \"clearcoatNoTextureRebuildStatus\": \"" << escapeJson(model.clearcoatNoTextureRebuildStatus) << "\",\n";
        f << indent << "  \"clearcoatNoModelReuploadStatus\": \"" << escapeJson(model.clearcoatNoModelReuploadStatus) << "\",\n";
        f << indent << "  \"clearcoatNoTransparentSortingStatus\": \"" << escapeJson(model.clearcoatNoTransparentSortingStatus) << "\",\n";
        f << indent << "  \"fakeCubemapStatus\": \"" << escapeJson(model.fakeCubemapStatus) << "\",\n";
        f << indent << "  \"fakeCubemapMode\": \"" << escapeJson(model.fakeCubemapMode) << "\",\n";
        f << indent << "  \"fakeCubemapSourceStatus\": \"" << escapeJson(model.fakeCubemapSourceStatus) << "\",\n";
        f << indent << "  \"environmentZoneStatus\": \"" << escapeJson(model.environmentZoneStatus) << "\",\n";
        f << indent << "  \"skyZoneStatus\": \"" << escapeJson(model.skyZoneStatus) << "\",\n";
        f << indent << "  \"horizonZoneStatus\": \"" << escapeJson(model.horizonZoneStatus) << "\",\n";
        f << indent << "  \"groundZoneStatus\": \"" << escapeJson(model.groundZoneStatus) << "\",\n";
        f << indent << "  \"sideReflectionZoneStatus\": \"" << escapeJson(model.sideReflectionZoneStatus) << "\",\n";
        f << indent << "  \"fakeCubemapPerformanceStatus\": \"" << escapeJson(model.fakeCubemapPerformanceStatus) << "\",\n";
        f << indent << "  \"reflectionQualityStatus\": \"" << escapeJson(model.reflectionQualityStatus) << "\",\n";
        f << indent << "  \"reflectionContrastStatus\": \"" << escapeJson(model.reflectionContrastStatus) << "\",\n";
        f << indent << "  \"reflectionContrastValue\": " << model.reflectionContrastValue << ",\n";
        f << indent << "  \"reflectionSaturationStatus\": \"" << escapeJson(model.reflectionSaturationStatus) << "\",\n";
        f << indent << "  \"reflectionSaturationValue\": " << model.reflectionSaturationValue << ",\n";
        f << indent << "  \"roughnessReflectionBlurStatus\": \"" << escapeJson(model.roughnessReflectionBlurStatus) << "\",\n";
        f << indent << "  \"clearcoatReflectionBoostStatus\": \"" << escapeJson(model.clearcoatReflectionBoostStatus) << "\",\n";
        f << indent << "  \"metalReflectionTintStatus\": \"" << escapeJson(model.metalReflectionTintStatus) << "\",\n";
        f << indent << "  \"fabricReflectionSuppressStatus\": \"" << escapeJson(model.fabricReflectionSuppressStatus) << "\",\n";
        f << indent << "  \"reflectionEnergyGuardStatus\": \"" << escapeJson(model.reflectionEnergyGuardStatus) << "\",\n";
        f << indent << "  \"reflectionOverbrightGuardStatus\": \"" << escapeJson(model.reflectionOverbrightGuardStatus) << "\",\n";
        f << indent << "  \"reflectionQualityUiStatus\": \"" << escapeJson(model.reflectionQualityUiStatus) << "\",\n";
        f << indent << "  \"reflectionContrastSliderStatus\": \"" << escapeJson(model.reflectionContrastSliderStatus) << "\",\n";
        f << indent << "  \"reflectionSaturationSliderStatus\": \"" << escapeJson(model.reflectionSaturationSliderStatus) << "\",\n";
        f << indent << "  \"environmentZonePresetStatus\": \"" << escapeJson(model.environmentZonePresetStatus) << "\",\n";
        f << indent << "  \"environmentZonePreset\": \"" << escapeJson(model.environmentZonePreset) << "\",\n";
        f << indent << "  \"reflectionUniformUpdateStatus\": \"" << escapeJson(model.reflectionUniformUpdateStatus) << "\",\n";
        f << indent << "  \"motionPerformanceGuardStatus\": \"" << escapeJson(model.motionPerformanceGuardStatus) << "\",\n";
        f << indent << "  \"cameraMotionStatus\": \"" << escapeJson(model.cameraMotionStatus) << "\",\n";
        f << indent << "  \"cameraMotionSpeed\": " << model.cameraMotionSpeed << ",\n";
        f << indent << "  \"cameraMotionQualityTier\": \"" << escapeJson(model.cameraMotionQualityTier) << "\",\n";
        f << indent << "  \"cameraMotionQualityBlend\": " << model.cameraMotionQualityBlend << ",\n";
        f << indent << "  \"motionReflectionScale\": " << model.motionReflectionScale << ",\n";
        f << indent << "  \"motionClearcoatScale\": " << model.motionClearcoatScale << ",\n";
        f << indent << "  \"motionDiagnosticsThrottleStatus\": \"" << escapeJson(model.motionDiagnosticsThrottleStatus) << "\",\n";
        f << indent << "  \"motionQualityRestoreStatus\": \"" << escapeJson(model.motionQualityRestoreStatus) << "\",\n";
        f << indent << "  \"motionQualityTransitionMs\": " << model.motionQualityTransitionMs << ",\n";
        f << indent << "  \"cameraMovingFpsLast\": " << model.cameraMovingFpsLast << ",\n";
        f << indent << "  \"cameraStillFpsLast\": " << model.cameraStillFpsLast << ",\n";
        f << indent << "  \"targetMovingFps\": " << model.targetMovingFps << ",\n";
        f << indent << "  \"movingFpsGuardStatus\": \"" << escapeJson(model.movingFpsGuardStatus) << "\",\n";
        f << indent << "  \"carPaintReflectionStatus\": \"" << escapeJson(model.carPaintReflectionStatus) << "\",\n";
        f << indent << "  \"metalReflectionStatus\": \"" << escapeJson(model.metalReflectionStatus) << "\",\n";
        f << indent << "  \"plasticReflectionStatus\": \"" << escapeJson(model.plasticReflectionStatus) << "\",\n";
        f << indent << "  \"rubberReflectionStatus\": \"" << escapeJson(model.rubberReflectionStatus) << "\",\n";
        f << indent << "  \"glassMetadataReflectionStatus\": \"" << escapeJson(model.glassMetadataReflectionStatus) << "\",\n";
        f << indent << "  \"materialPresetReflectionStatus\": \"" << escapeJson(model.materialPresetReflectionStatus) << "\",\n";
        f << indent << "  \"fakeCubemapDebugViewStatus\": \"" << escapeJson(model.fakeCubemapDebugViewStatus) << "\",\n";
        f << indent << "  \"reflectionZonesDebugViewStatus\": \"" << escapeJson(model.reflectionZonesDebugViewStatus) << "\",\n";
        f << indent << "  \"reflectionContrastDebugViewStatus\": \"" << escapeJson(model.reflectionContrastDebugViewStatus) << "\",\n";
        f << indent << "  \"reflectionEnergyGuardDebugViewStatus\": \"" << escapeJson(model.reflectionEnergyGuardDebugViewStatus) << "\",\n";
        f << indent << "  \"clearcoatReflectionDebugViewStatus\": \"" << escapeJson(model.clearcoatReflectionDebugViewStatus) << "\",\n";
        f << indent << "  \"motionQualityDebugViewStatus\": \"" << escapeJson(model.motionQualityDebugViewStatus) << "\",\n";
        f << indent << "  \"p23ClearcoatPreservedStatus\": \"" << escapeJson(model.p23ClearcoatPreservedStatus) << "\",\n";
        f << indent << "  \"p24PerformanceStatus\": \"" << escapeJson(model.p24PerformanceStatus) << "\",\n";
        f << indent << "  \"fakeCubemapNoTextureStatus\": \"" << escapeJson(model.fakeCubemapNoTextureStatus) << "\",\n";
        f << indent << "  \"fakeCubemapNoNewPassStatus\": \"" << escapeJson(model.fakeCubemapNoNewPassStatus) << "\",\n";
        f << indent << "  \"reflectionNoTextureRebuildStatus\": \"" << escapeJson(model.reflectionNoTextureRebuildStatus) << "\",\n";
        f << indent << "  \"reflectionNoModelReuploadStatus\": \"" << escapeJson(model.reflectionNoModelReuploadStatus) << "\",\n";
        f << indent << "  \"noFrameFileWriteStatus\": \"" << escapeJson(model.noFrameFileWriteStatus) << "\",\n";
        f << indent << "  \"noFrameGlbParseStatus\": \"" << escapeJson(model.noFrameGlbParseStatus) << "\",\n";
        f << indent << "  \"p26ReflectionPolishStatus\": \"" << escapeJson(model.p26ReflectionPolishStatus) << "\",\n";
        f << indent << "  \"reflectionZonePolishStatus\": \"" << escapeJson(model.reflectionZonePolishStatus) << "\",\n";
        f << indent << "  \"sideRimReflectionPolishStatus\": \"" << escapeJson(model.sideRimReflectionPolishStatus) << "\",\n";
        f << indent << "  \"roughnessReflectionPolishStatus\": \"" << escapeJson(model.roughnessReflectionPolishStatus) << "\",\n";
        f << indent << "  \"glassReflectionZoneStatus\": \"" << escapeJson(model.glassReflectionZoneStatus) << "\",\n";
        f << indent << "  \"clearcoatReflectionZoneStatus\": \"" << escapeJson(model.clearcoatReflectionZoneStatus) << "\",\n";
        f << indent << "  \"glassMaterialStatus\": \"" << escapeJson(model.glassMaterialStatus) << "\",\n";
        f << indent << "  \"glassMode\": \"" << escapeJson(model.glassMode) << "\",\n";
        f << indent << "  \"glassPolishStatus\": \"" << escapeJson(model.glassPolishStatus) << "\",\n";
        f << indent << "  \"glassPolishMode\": \"" << escapeJson(model.glassPolishMode) << "\",\n";
        f << indent << "  \"glassReadabilityStatus\": \"" << escapeJson(model.glassReadabilityStatus) << "\",\n";
        f << indent << "  \"glassEdgePolishStatus\": \"" << escapeJson(model.glassEdgePolishStatus) << "\",\n";
        f << indent << "  \"glassTintPolishStatus\": \"" << escapeJson(model.glassTintPolishStatus) << "\",\n";
        f << indent << "  \"glassThicknessPolishStatus\": \"" << escapeJson(model.glassThicknessPolishStatus) << "\",\n";
        f << indent << "  \"glassOpacityCurveStatus\": \"" << escapeJson(model.glassOpacityCurveStatus) << "\",\n";
        f << indent << "  \"glassRoughnessPolishStatus\": \"" << escapeJson(model.glassRoughnessPolishStatus) << "\",\n";
        f << indent << "  \"glassReflectionPolishStatus\": \"" << escapeJson(model.glassReflectionPolishStatus) << "\",\n";
        f << indent << "  \"glassOpacity\": " << model.glassOpacity << ",\n";
        f << indent << "  \"glassTintStatus\": \"" << escapeJson(model.glassTintStatus) << "\",\n";
        f << indent << "  \"glassTintColor\": \"" << escapeJson(model.glassTintColor) << "\",\n";
        f << indent << "  \"glassFresnelStatus\": \"" << escapeJson(model.glassFresnelStatus) << "\",\n";
        f << indent << "  \"glassEdgeReflectionStatus\": \"" << escapeJson(model.glassEdgeReflectionStatus) << "\",\n";
        f << indent << "  \"glassReflectionSourceStatus\": \"" << escapeJson(model.glassReflectionSourceStatus) << "\",\n";
        f << indent << "  \"glassRoughnessResponseStatus\": \"" << escapeJson(model.glassRoughnessResponseStatus) << "\",\n";
        f << indent << "  \"glassThicknessFakeStatus\": \"" << escapeJson(model.glassThicknessFakeStatus) << "\",\n";
        f << indent << "  \"glassTransparencyMode\": \"" << escapeJson(model.glassTransparencyMode) << "\",\n";
        f << indent << "  \"glassSortingStatus\": \"" << escapeJson(model.glassSortingStatus) << "\",\n";
        f << indent << "  \"glassRefractionStatus\": \"" << escapeJson(model.glassRefractionStatus) << "\",\n";
        f << indent << "  \"glassStillFakeTransparencyStatus\": \"" << escapeJson(model.glassStillFakeTransparencyStatus) << "\",\n";
        f << indent << "  \"glassPerformanceStatus\": \"" << escapeJson(model.glassPerformanceStatus) << "\",\n";
        f << indent << "  \"glassUiStatus\": \"" << escapeJson(model.glassUiStatus) << "\",\n";
        f << indent << "  \"glassEnableButtonStatus\": \"" << escapeJson(model.glassEnableButtonStatus) << "\",\n";
        f << indent << "  \"glassPresetStatus\": \"" << escapeJson(model.glassPresetStatus) << "\",\n";
        f << indent << "  \"activeGlassPreset\": \"" << escapeJson(model.activeGlassPreset) << "\",\n";
        f << indent << "  \"glassOpacitySliderStatus\": \"" << escapeJson(model.glassOpacitySliderStatus) << "\",\n";
        f << indent << "  \"glassOpacityValue\": " << model.glassOpacityValue << ",\n";
        f << indent << "  \"glassTintPresetStatus\": \"" << escapeJson(model.glassTintPresetStatus) << "\",\n";
        f << indent << "  \"activeGlassTintPreset\": \"" << escapeJson(model.activeGlassTintPreset) << "\",\n";
        f << indent << "  \"glassEdgeSliderStatus\": \"" << escapeJson(model.glassEdgeSliderStatus) << "\",\n";
        f << indent << "  \"glassEdgeValue\": " << model.glassEdgeValue << ",\n";
        f << indent << "  \"glassRoughnessSliderStatus\": \"" << escapeJson(model.glassRoughnessSliderStatus) << "\",\n";
        f << indent << "  \"glassRoughnessValue\": " << model.glassRoughnessValue << ",\n";
        f << indent << "  \"glassUniformUpdateStatus\": \"" << escapeJson(model.glassUniformUpdateStatus) << "\",\n";
        f << indent << "  \"glassPresetIntegrationStatus\": \"" << escapeJson(model.glassPresetIntegrationStatus) << "\",\n";
        f << indent << "  \"glassPresetAppliedSlot\": " << model.glassPresetAppliedSlot << ",\n";
        f << indent << "  \"glassPresetAppliedStatus\": \"" << escapeJson(model.glassPresetAppliedStatus) << "\",\n";
        f << indent << "  \"glassPresetPolishStatus\": \"" << escapeJson(model.glassPresetPolishStatus) << "\",\n";
        f << indent << "  \"clearGlassPresetStatus\": \"" << escapeJson(model.clearGlassPresetStatus) << "\",\n";
        f << indent << "  \"blueGlassPresetStatus\": \"" << escapeJson(model.blueGlassPresetStatus) << "\",\n";
        f << indent << "  \"greenGlassPresetStatus\": \"" << escapeJson(model.greenGlassPresetStatus) << "\",\n";
        f << indent << "  \"smokeGlassPresetStatus\": \"" << escapeJson(model.smokeGlassPresetStatus) << "\",\n";
        f << indent << "  \"warmGlassPresetStatus\": \"" << escapeJson(model.warmGlassPresetStatus) << "\",\n";
        f << indent << "  \"magicGlassPresetStatus\": \"" << escapeJson(model.magicGlassPresetStatus) << "\",\n";
        f << indent << "  \"dirtyGlassLitePresetStatus\": \"" << escapeJson(model.dirtyGlassLitePresetStatus) << "\",\n";
        f << indent << "  \"crystalLitePresetStatus\": \"" << escapeJson(model.crystalLitePresetStatus) << "\",\n";
        f << indent << "  \"glassPresetVisualResponseStatus\": \"" << escapeJson(model.glassPresetVisualResponseStatus) << "\",\n";
        f << indent << "  \"glassSelectedSlotRoutingStatus\": \"" << escapeJson(model.glassSelectedSlotRoutingStatus) << "\",\n";
        f << indent << "  \"glassFabricGuardStatus\": \"" << escapeJson(model.glassFabricGuardStatus) << "\",\n";
        f << indent << "  \"glassMetalGuardStatus\": \"" << escapeJson(model.glassMetalGuardStatus) << "\",\n";
        f << indent << "  \"glassCarPaintGuardStatus\": \"" << escapeJson(model.glassCarPaintGuardStatus) << "\",\n";
        f << indent << "  \"glassVisualResponseStatus\": \"" << escapeJson(model.glassVisualResponseStatus) << "\",\n";
        f << indent << "  \"glassOpacityResponseStatus\": \"" << escapeJson(model.glassOpacityResponseStatus) << "\",\n";
        f << indent << "  \"glassTintResponseStatus\": \"" << escapeJson(model.glassTintResponseStatus) << "\",\n";
        f << indent << "  \"glassFresnelResponseStatus\": \"" << escapeJson(model.glassFresnelResponseStatus) << "\",\n";
        f << indent << "  \"glassReflectionResponseStatus\": \"" << escapeJson(model.glassReflectionResponseStatus) << "\",\n";
        f << indent << "  \"glassEnergyGuardStatus\": \"" << escapeJson(model.glassEnergyGuardStatus) << "\",\n";
        f << indent << "  \"glassOverbrightGuardStatus\": \"" << escapeJson(model.glassOverbrightGuardStatus) << "\",\n";
        f << indent << "  \"glassInvisibleGuardStatus\": \"" << escapeJson(model.glassInvisibleGuardStatus) << "\",\n";
        f << indent << "  \"glassMaskDebugViewStatus\": \"" << escapeJson(model.glassMaskDebugViewStatus) << "\",\n";
        f << indent << "  \"glassOpacityDebugViewStatus\": \"" << escapeJson(model.glassOpacityDebugViewStatus) << "\",\n";
        f << indent << "  \"glassFresnelDebugViewStatus\": \"" << escapeJson(model.glassFresnelDebugViewStatus) << "\",\n";
        f << indent << "  \"glassReflectionDebugViewStatus\": \"" << escapeJson(model.glassReflectionDebugViewStatus) << "\",\n";
        f << indent << "  \"glassTintDebugViewStatus\": \"" << escapeJson(model.glassTintDebugViewStatus) << "\",\n";
        f << indent << "  \"glassSafetyDebugViewStatus\": \"" << escapeJson(model.glassSafetyDebugViewStatus) << "\",\n";
        f << indent << "  \"glassPolishDebugViewStatus\": \"" << escapeJson(model.glassPolishDebugViewStatus) << "\",\n";
        f << indent << "  \"glassEdgeDebugViewStatus\": \"" << escapeJson(model.glassEdgeDebugViewStatus) << "\",\n";
        f << indent << "  \"glassThicknessDebugViewStatus\": \"" << escapeJson(model.glassThicknessDebugViewStatus) << "\",\n";
        f << indent << "  \"glassReflectionPolishDebugViewStatus\": \"" << escapeJson(model.glassReflectionPolishDebugViewStatus) << "\",\n";
        f << indent << "  \"clearcoatPolishDebugViewStatus\": \"" << escapeJson(model.clearcoatPolishDebugViewStatus) << "\",\n";
        f << indent << "  \"paintReflectionDebugViewStatus\": \"" << escapeJson(model.paintReflectionDebugViewStatus) << "\",\n";
        f << indent << "  \"p24ReflectionPreservedStatus\": \"" << escapeJson(model.p24ReflectionPreservedStatus) << "\",\n";
        f << indent << "  \"p25GlassPreservedStatus\": \"" << escapeJson(model.p25GlassPreservedStatus) << "\",\n";
        f << indent << "  \"p26UiChangeStatus\": \"" << escapeJson(model.p26UiChangeStatus) << "\",\n";
        f << indent << "  \"glassSummaryUiStatus\": \"" << escapeJson(model.glassSummaryUiStatus) << "\",\n";
        f << indent << "  \"glassStrengthSliderStatus\": \"" << escapeJson(model.glassStrengthSliderStatus) << "\",\n";
        f << indent << "  \"glassControlsPreservedStatus\": \"" << escapeJson(model.glassControlsPreservedStatus) << "\",\n";
        f << indent << "  \"clearcoatPolishStatus\": \"" << escapeJson(model.clearcoatPolishStatus) << "\",\n";
        f << indent << "  \"clearcoatHighlightPolishStatus\": \"" << escapeJson(model.clearcoatHighlightPolishStatus) << "\",\n";
        f << indent << "  \"clearcoatReflectionSeparationStatus\": \"" << escapeJson(model.clearcoatReflectionSeparationStatus) << "\",\n";
        f << indent << "  \"carPaintPolishStatus\": \"" << escapeJson(model.carPaintPolishStatus) << "\",\n";
        f << indent << "  \"carPaintLayerReadabilityStatus\": \"" << escapeJson(model.carPaintLayerReadabilityStatus) << "\",\n";
        f << indent << "  \"carPaintReflectionSeparationStatus\": \"" << escapeJson(model.carPaintReflectionSeparationStatus) << "\",\n";
        f << indent << "  \"paintOverbrightGuardStatus\": \"" << escapeJson(model.paintOverbrightGuardStatus) << "\",\n";
        f << indent << "  \"p25PerformanceStatus\": \"" << escapeJson(model.p25PerformanceStatus) << "\",\n";
        f << indent << "  \"p26PerformanceStatus\": \"" << escapeJson(model.p26PerformanceStatus) << "\",\n";
        f << indent << "  \"p26NoRealRefractionStatus\": \"" << escapeJson(model.p26NoRealRefractionStatus) << "\",\n";
        f << indent << "  \"p26NoScreenRefractionStatus\": \"" << escapeJson(model.p26NoScreenRefractionStatus) << "\",\n";
        f << indent << "  \"p26NoMirrorPassStatus\": \"" << escapeJson(model.p26NoMirrorPassStatus) << "\",\n";
        f << indent << "  \"p26NoFullSortingStatus\": \"" << escapeJson(model.p26NoFullSortingStatus) << "\",\n";
        f << indent << "  \"p26NoTextureRebuildStatus\": \"" << escapeJson(model.p26NoTextureRebuildStatus) << "\",\n";
        f << indent << "  \"p26NoModelReuploadStatus\": \"" << escapeJson(model.p26NoModelReuploadStatus) << "\",\n";
        f << indent << "  \"p26NoNewShadowPassStatus\": \"" << escapeJson(model.p26NoNewShadowPassStatus) << "\",\n";
        f << indent << "  \"transparentGlassPassStatus\": \"" << escapeJson(model.transparentGlassPassStatus) << "\",\n";
        f << indent << "  \"transparentGlassPassMode\": \"" << escapeJson(model.transparentGlassPassMode) << "\",\n";
        f << indent << "  \"transparentGlassSelectedSlotStatus\": \"" << escapeJson(model.transparentGlassSelectedSlotStatus) << "\",\n";
        f << indent << "  \"transparentGlassDrawOrderStatus\": \"" << escapeJson(model.transparentGlassDrawOrderStatus) << "\",\n";
        f << indent << "  \"transparentGlassBlendStatus\": \"" << escapeJson(model.transparentGlassBlendStatus) << "\",\n";
        f << indent << "  \"transparentGlassOpacityStatus\": \"" << escapeJson(model.transparentGlassOpacityStatus) << "\",\n";
        f << indent << "  \"transparentGlassTintStatus\": \"" << escapeJson(model.transparentGlassTintStatus) << "\",\n";
        f << indent << "  \"transparentGlassFresnelStatus\": \"" << escapeJson(model.transparentGlassFresnelStatus) << "\",\n";
        f << indent << "  \"transparentGlassReflectionStatus\": \"" << escapeJson(model.transparentGlassReflectionStatus) << "\",\n";
        f << indent << "  \"transparentGlassSortingStatus\": \"" << escapeJson(model.transparentGlassSortingStatus) << "\",\n";
        f << indent << "  \"transparentGlassRefractionStatus\": \"" << escapeJson(model.transparentGlassRefractionStatus) << "\",\n";
        f << indent << "  \"transparentGlassFallbackStatus\": \"" << escapeJson(model.transparentGlassFallbackStatus) << "\",\n";
        f << indent << "  \"transparentGlassPerformanceStatus\": \"" << escapeJson(model.transparentGlassPerformanceStatus) << "\",\n";
        f << indent << "  \"transparentGlassUiStatus\": \"" << escapeJson(model.transparentGlassUiStatus) << "\",\n";
        f << indent << "  \"glassRenderModeStatus\": \"" << escapeJson(model.glassRenderModeStatus) << "\",\n";
        f << indent << "  \"activeGlassRenderMode\": \"" << escapeJson(model.activeGlassRenderMode) << "\",\n";
        f << indent << "  \"transparentGlassToggleStatus\": \"" << escapeJson(model.transparentGlassToggleStatus) << "\",\n";
        f << indent << "  \"glassModeSummaryUiStatus\": \"" << escapeJson(model.glassModeSummaryUiStatus) << "\",\n";
        f << indent << "  \"p26GlassPolishPreservedStatus\": \"" << escapeJson(model.p26GlassPolishPreservedStatus) << "\",\n";
        f << indent << "  \"fakeGlassFallbackStatus\": \"" << escapeJson(model.fakeGlassFallbackStatus) << "\",\n";
        f << indent << "  \"glassAutoFallbackStatus\": \"" << escapeJson(model.glassAutoFallbackStatus) << "\",\n";
        f << indent << "  \"glassMotionFallbackStatus\": \"" << escapeJson(model.glassMotionFallbackStatus) << "\",\n";
        f << indent << "  \"transparentGlassMaterialRoutingStatus\": \"" << escapeJson(model.transparentGlassMaterialRoutingStatus) << "\",\n";
        f << indent << "  \"transparentGlassAppliedSlot\": " << model.transparentGlassAppliedSlot << ",\n";
        f << indent << "  \"transparentGlassAppliedMaterialCount\": " << model.transparentGlassAppliedMaterialCount << ",\n";
        f << indent << "  \"transparentGlassSkippedOpaqueCount\": " << model.transparentGlassSkippedOpaqueCount << ",\n";
        f << indent << "  \"materialRoleSystemStatus\": \"" << escapeJson(model.materialRoleSystemStatus) << "\",\n";
        f << indent << "  \"materialRoleDetectionMode\": \"" << escapeJson(model.materialRoleDetectionMode) << "\",\n";
        f << indent << "  \"selectedMaterialRole\": \"" << escapeJson(model.selectedMaterialRole) << "\",\n";
        f << indent << "  \"selectedMaterialRoleConfidence\": " << model.selectedMaterialRoleConfidence << ",\n";
        f << indent << "  \"selectedMaterialRoleSource\": \"" << escapeJson(model.selectedMaterialRoleSource) << "\",\n";
        f << indent << "  \"materialRoleCandidateCount\": " << model.materialRoleCandidateCount << ",\n";
        f << indent << "  \"glassCandidateCount\": " << model.glassCandidateCount << ",\n";
        f << indent << "  \"bestGlassCandidateSlot\": " << model.bestGlassCandidateSlot << ",\n";
        f << indent << "  \"bestGlassCandidateName\": \"" << escapeJson(model.bestGlassCandidateName) << "\",\n";
        f << indent << "  \"bestGlassCandidateConfidence\": " << model.bestGlassCandidateConfidence << ",\n";
        f << indent << "  \"bestGlassCandidateSource\": \"" << escapeJson(model.bestGlassCandidateSource) << "\",\n";
        f << indent << "  \"materialRoleNoHardcodeStatus\": \"" << escapeJson(model.materialRoleNoHardcodeStatus) << "\",\n";
        f << indent << "  \"transparentGlassRoutingStatus\": \"" << escapeJson(model.transparentGlassRoutingStatus) << "\",\n";
        f << indent << "  \"transparentGlassRoutingMode\": \"" << escapeJson(model.transparentGlassRoutingMode) << "\",\n";
        f << indent << "  \"activeTransparentGlassSlot\": " << model.activeTransparentGlassSlot << ",\n";
        f << indent << "  \"activeTransparentGlassMaterialName\": \"" << escapeJson(model.activeTransparentGlassMaterialName) << "\",\n";
        f << indent << "  \"activeTransparentGlassMaterialRole\": \"" << escapeJson(model.activeTransparentGlassMaterialRole) << "\",\n";
        f << indent << "  \"activeTransparentGlassRoleSource\": \"" << escapeJson(model.activeTransparentGlassRoleSource) << "\",\n";
        f << indent << "  \"activeTransparentGlassSlotSource\": \"" << escapeJson(model.activeTransparentGlassSlotSource) << "\",\n";
        f << indent << "  \"transparentGlassSelectedSlotAllowedStatus\": \"" << escapeJson(model.transparentGlassSelectedSlotAllowedStatus) << "\",\n";
        f << indent << "  \"transparentGlassSelectedSlotRejectedStatus\": \"" << escapeJson(model.transparentGlassSelectedSlotRejectedStatus) << "\",\n";
        f << indent << "  \"transparentGlassAutoDetectStatus\": \"" << escapeJson(model.transparentGlassAutoDetectStatus) << "\",\n";
        f << indent << "  \"transparentGlassManualOverrideStatus\": \"" << escapeJson(model.transparentGlassManualOverrideStatus) << "\",\n";
        f << indent << "  \"transparentGlassFallbackReason\": \"" << escapeJson(model.transparentGlassFallbackReason) << "\",\n";
        f << indent << "  \"transparentGlassWrongSlotGuardStatus\": \"" << escapeJson(model.transparentGlassWrongSlotGuardStatus) << "\",\n";
        f << indent << "  \"materialRoleUiStatus\": \"" << escapeJson(model.materialRoleUiStatus) << "\",\n";
        f << indent << "  \"selectedSlotRoleSummaryUiStatus\": \"" << escapeJson(model.selectedSlotRoleSummaryUiStatus) << "\",\n";
        f << indent << "  \"activeGlassSlotSummaryUiStatus\": \"" << escapeJson(model.activeGlassSlotSummaryUiStatus) << "\",\n";
        f << indent << "  \"selectGlassCandidateButtonStatus\": \"" << escapeJson(model.selectGlassCandidateButtonStatus) << "\",\n";
        f << indent << "  \"assignSelectedAsGlassButtonStatus\": \"" << escapeJson(model.assignSelectedAsGlassButtonStatus) << "\",\n";
        f << indent << "  \"clearManualRoleButtonStatus\": \"" << escapeJson(model.clearManualRoleButtonStatus) << "\",\n";
        f << indent << "  \"selectedSlotHighlightToggleStatus\": \"" << escapeJson(model.selectedSlotHighlightToggleStatus) << "\",\n";
        f << indent << "  \"transparentGlassSkippedNonGlassCount\": " << model.transparentGlassSkippedNonGlassCount << ",\n";
        f << indent << "  \"transparentGlassSkippedFabricCount\": " << model.transparentGlassSkippedFabricCount << ",\n";
        f << indent << "  \"transparentGlassSkippedMetalCount\": " << model.transparentGlassSkippedMetalCount << ",\n";
        f << indent << "  \"transparentGlassSkippedPaintCount\": " << model.transparentGlassSkippedPaintCount << ",\n";
        f << indent << "  \"p27TransparentPassPreservedStatus\": \"" << escapeJson(model.p27TransparentPassPreservedStatus) << "\",\n";
        f << indent << "  \"p27bPerformanceStatus\": \"" << escapeJson(model.p27bPerformanceStatus) << "\",\n";
        f << indent << "  \"p27bNoExtraHeavyPassStatus\": \"" << escapeJson(model.p27bNoExtraHeavyPassStatus) << "\",\n";
        f << indent << "  \"p27bNoTextureRebuildStatus\": \"" << escapeJson(model.p27bNoTextureRebuildStatus) << "\",\n";
        f << indent << "  \"p27bNoModelReuploadStatus\": \"" << escapeJson(model.p27bNoModelReuploadStatus) << "\",\n";
        f << indent << "  \"p27bNoFrameGlbParseStatus\": \"" << escapeJson(model.p27bNoFrameGlbParseStatus) << "\",\n";
        f << indent << "  \"p27bNoFrameFileWriteStatus\": \"" << escapeJson(model.p27bNoFrameFileWriteStatus) << "\",\n";
        f << indent << "  \"p27bNoShadowStatus\": \"" << escapeJson(model.p27bNoShadowStatus) << "\",\n";
        f << indent << "  \"p27bNoRealMirrorStatus\": \"" << escapeJson(model.p27bNoRealMirrorStatus) << "\",\n";
        f << indent << "  \"p27bNoSsrStatus\": \"" << escapeJson(model.p27bNoSsrStatus) << "\",\n";
        f << indent << "  \"p27bNoRealRefractionStatus\": \"" << escapeJson(model.p27bNoRealRefractionStatus) << "\",\n";
        f << indent << "  \"materialRoleDebugViewStatus\": \"" << escapeJson(model.materialRoleDebugViewStatus) << "\",\n";
        f << indent << "  \"glassCandidateDebugViewStatus\": \"" << escapeJson(model.glassCandidateDebugViewStatus) << "\",\n";
        f << indent << "  \"activeGlassSlotDebugViewStatus\": \"" << escapeJson(model.activeGlassSlotDebugViewStatus) << "\",\n";
        f << indent << "  \"transparentRoutingDebugViewStatus\": \"" << escapeJson(model.transparentRoutingDebugViewStatus) << "\",\n";
        f << indent << "  \"wrongSlotGuardDebugViewStatus\": \"" << escapeJson(model.wrongSlotGuardDebugViewStatus) << "\",\n";
        f << indent << "  \"transparentGlassFabricGuardStatus\": \"" << escapeJson(model.transparentGlassFabricGuardStatus) << "\",\n";
        f << indent << "  \"transparentGlassMetalGuardStatus\": \"" << escapeJson(model.transparentGlassMetalGuardStatus) << "\",\n";
        f << indent << "  \"transparentGlassCarPaintGuardStatus\": \"" << escapeJson(model.transparentGlassCarPaintGuardStatus) << "\",\n";
        f << indent << "  \"transparentGlassMaskDebugViewStatus\": \"" << escapeJson(model.transparentGlassMaskDebugViewStatus) << "\",\n";
        f << indent << "  \"transparentGlassAlphaDebugViewStatus\": \"" << escapeJson(model.transparentGlassAlphaDebugViewStatus) << "\",\n";
        f << indent << "  \"transparentGlassDrawOrderDebugViewStatus\": \"" << escapeJson(model.transparentGlassDrawOrderDebugViewStatus) << "\",\n";
        f << indent << "  \"transparentGlassFallbackDebugViewStatus\": \"" << escapeJson(model.transparentGlassFallbackDebugViewStatus) << "\",\n";
        f << indent << "  \"transparentGlassSafetyDebugViewStatus\": \"" << escapeJson(model.transparentGlassSafetyDebugViewStatus) << "\",\n";
        f << indent << "  \"p27PerformanceStatus\": \"" << escapeJson(model.p27PerformanceStatus) << "\",\n";
        f << indent << "  \"p27NoShadowStatus\": \"" << escapeJson(model.p27NoShadowStatus) << "\",\n";
        f << indent << "  \"p27NoRaytraceStatus\": \"" << escapeJson(model.p27NoRaytraceStatus) << "\",\n";
        f << indent << "  \"p27NoSsrStatus\": \"" << escapeJson(model.p27NoSsrStatus) << "\",\n";
        f << indent << "  \"p27NoRealMirrorStatus\": \"" << escapeJson(model.p27NoRealMirrorStatus) << "\",\n";
        f << indent << "  \"p27NoScreenRefractionStatus\": \"" << escapeJson(model.p27NoScreenRefractionStatus) << "\",\n";
        f << indent << "  \"p27NoTextureRebuildStatus\": \"" << escapeJson(model.p27NoTextureRebuildStatus) << "\",\n";
        f << indent << "  \"p27NoModelReuploadStatus\": \"" << escapeJson(model.p27NoModelReuploadStatus) << "\",\n";
        f << indent << "  \"glassNoRefractionPassStatus\": \"" << escapeJson(model.glassNoRefractionPassStatus) << "\",\n";
        f << indent << "  \"glassNoScreenRefractionStatus\": \"" << escapeJson(model.glassNoScreenRefractionStatus) << "\",\n";
        f << indent << "  \"glassNoFullSortingStatus\": \"" << escapeJson(model.glassNoFullSortingStatus) << "\",\n";
        f << indent << "  \"glassNoTextureRebuildStatus\": \"" << escapeJson(model.glassNoTextureRebuildStatus) << "\",\n";
        f << indent << "  \"glassNoModelReuploadStatus\": \"" << escapeJson(model.glassNoModelReuploadStatus) << "\",\n";
        f << indent << "  \"glassNoNewShadowPassStatus\": \"" << escapeJson(model.glassNoNewShadowPassStatus) << "\",\n";
        f << indent << "  \"fpsCurrent\": " << model.fpsCurrent << ",\n";
        f << indent << "  \"frameTimeMs\": " << model.frameTimeMs << ",\n";
        f << indent << "  \"fpsSource\": \"" << escapeJson(model.fpsSource) << "\",\n";
        f << indent << "  \"fpsLastStable\": " << model.fpsLastStable << ",\n";
        f << indent << "  \"frameTimeLastStableMs\": " << model.frameTimeLastStableMs << ",\n";
        f << indent << "  \"fpsStatus\": \"" << escapeJson(model.fpsStatus) << "\",\n";
        f << indent << "  \"fpsUpdateMode\": \"" << escapeJson(model.fpsUpdateMode) << "\",\n";
        f << indent << "  \"fpsSampleWindowMs\": " << model.fpsSampleWindowMs << ",\n";
        f << indent << "  \"framesRenderedLive\": " << model.framesRenderedLive << ",\n";
        f << indent << "  \"modelUploadRepeatCount\": " << model.modelUploadRepeatCount << ",\n";
        f << indent << "  \"uploadGenerationId\": " << model.uploadGenerationId << ",\n";
        f << indent << "  \"renderLoopAllocationGuardStatus\": \"" << escapeJson(model.renderLoopAllocationGuardStatus) << "\",\n";
        f << indent << "  \"debugZipStatus\": \"" << escapeJson(model.debugZipStatus) << "\",\n";
        f << indent << "  \"debugZipPath\": \"" << escapeJson(model.debugZipPath) << "\",\n";
        f << indent << "  \"debugZipIncludedFiles\": \"" << escapeJson(model.debugZipIncludedFiles) << "\",\n";
        f << indent << "  \"debugZipReason\": \"" << escapeJson(model.debugZipReason) << "\",\n";
        f << indent << "  \"fallbackCubeVisible\": " << (model.fallbackCubeVisible ? "true" : "false") << ",\n";
        f << indent << "  \"fallbackCubeStatus\": \"" << escapeJson(model.fallbackCubeStatus) << "\",\n";
        f << indent << "  \"reason\": \"" << escapeJson(model.reason) << "\",\n";
        f << indent << "  \"cubeStatus\": \"" << (cubeReady || !model.fallbackCubeVisible ? "ok" : "failed") << "\",\n";
        f << indent << "  \"depthStatus\": \"" << (depthReady ? "ok" : "failed") << "\",\n";
        f << indent << "  \"cameraStatus\": \"" << (cameraReady ? "ok" : "failed") << "\",\n";
        f << indent << "  \"cameraMvpStatus\": \"" << (cameraMvpReady ? "ok" : "failed") << "\",\n";
        f << indent << "  \"cameraControlsStatus\": \"" << (cameraControlsReady ? "ok" : "not_implemented") << "\",\n";
        f << indent << "  \"cameraYawDeg\": " << cameraYawDeg << ",\n";
        f << indent << "  \"cameraPitchDeg\": " << cameraPitchDeg << ",\n";
        f << indent << "  \"cameraDistance\": " << cameraDistance << ",\n";
        f << indent << "  \"indexBufferReady\": " << (indexBufferReady ? "true" : "false") << ",\n";
        f << indent << "  \"uniformOrPushConstantsReady\": " << (uniformOrPushConstantsReady ? "true" : "false") << ",\n";
        f << indent << "  \"materialConstantsReady\": " << (materialConstantsReady ? "true" : "false") << ",\n";
        f << indent << "  \"meshAttributeLayoutReady\": " << (meshAttributeLayoutReady ? "true" : "false") << ",\n";
        f << indent << "  \"vertexLayout\": \"" << vertexLayout << "\",\n";
        f << indent << "  \"vertexStrideBytes\": " << vertexStrideBytes << ",\n";
        f << indent << "  \"material\": {\n";
        f << indent << "    \"materialId\": " << material.materialId << ",\n";
        f << indent << "    \"baseColorFactor\": [" << material.baseColorFactor[0] << ", " << material.baseColorFactor[1] << ", " << material.baseColorFactor[2] << ", " << material.baseColorFactor[3] << "],\n";
        f << indent << "    \"metallicFactor\": " << material.metallicFactor << ",\n";
        f << indent << "    \"roughnessFactor\": " << material.roughnessFactor << ",\n";
        f << indent << "    \"normalScale\": " << material.normalScale << ",\n";
        f << indent << "    \"occlusionStrength\": " << material.occlusionStrength << ",\n";
        f << indent << "    \"emissiveFactor\": [" << material.emissiveFactor[0] << ", " << material.emissiveFactor[1] << ", " << material.emissiveFactor[2] << "],\n";
        f << indent << "    \"emissiveIntensity\": " << material.emissiveIntensity << ",\n";
        f << indent << "    \"materialPresetHint\": " << material.materialPresetHint << ",\n";
        f << indent << "    \"clearcoatIntensity\": " << material.clearcoatIntensity << ",\n";
        f << indent << "    \"clearcoatRoughness\": " << material.clearcoatRoughness << ",\n";
        f << indent << "    \"reflectionContrast\": " << material.reflectionContrast << ",\n";
        f << indent << "    \"reflectionSaturation\": " << material.reflectionSaturation << ",\n";
        f << indent << "    \"motionReflectionScale\": " << material.motionReflectionScale << ",\n";
        f << indent << "    \"motionClearcoatScale\": " << material.motionClearcoatScale << ",\n";
        f << indent << "    \"alphaMode\": \"OPAQUE\",\n";
        f << indent << "    \"alphaCutoff\": " << material.alphaCutoff << "\n";
        f << indent << "  },\n";
        f << indent << "  \"vertexCount\": " << vertexCount << ",\n";
        f << indent << "  \"indexCount\": " << indexCount << ",\n";
        f << indent << "  \"framesRendered\": " << framesRendered << ",\n";
        f << indent << "  \"rendererPath\": \"Android Native Vulkan\",\n";
        f << indent << "  \"triangleFallback\": \"" << (triangleFallbackEnabled ? "enabled" : "available/disabled") << "\",\n";
        f << indent << "  \"screenshot\": { \"status\": \"not_available\", \"reason\": \"renderer_readback_not_implemented\" }\n";
        f << indent << "}";
    }
};

} // namespace solum
