#pragma once
#define VK_USE_PLATFORM_ANDROID_KHR 1
#include <vulkan/vulkan.h>
#include <android/native_window.h>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <cstdint>
#include <sys/stat.h>

namespace solum {

struct Vertex2D { float x; float y; };
struct Vertex3D {
    float px; float py; float pz;
    float nx; float ny; float nz;
    float u; float v;
    float r; float g; float b;
    float tx; float ty; float tz; float tw;
};

struct CameraState {
    float yawDeg = 28.0f;
    float pitchDeg = -18.0f;
    float distance = 4.2f;
    bool controlsActive = false;
};

struct MaterialConstants {
    float baseColorFactor[4] = { 0.92f, 0.78f, 1.0f, 1.0f };
    float metallicFactor = 0.0f;
    float roughnessFactor = 0.65f;
    float normalScale = 1.0f;
    float occlusionStrength = 1.0f;
    float emissiveFactor[3] = { 0.0f, 0.0f, 0.0f };
    int alphaMode = 0;
    int materialId = 1;
    int baseColorTextureReady = 0;
    int metallicRoughnessTextureReady = 0;
    int normalTextureReady = 0;
    int occlusionTextureReady = 0;
    float sunDirection[3] = { -0.35f, -0.82f, -0.45f };
    float sunIntensity = 2.0f;
    float sunColor[3] = { 1.0f, 0.96f, 0.88f };
    float ambientIntensity = 0.80f;
    float ambientColor[3] = { 0.42f, 0.52f, 0.62f };
    int lightPreset = 3;
    int activeDebugView = 0;
    int toneMappingMode = 1;
    float exposureValue = 1.50f;
    float ambientFloor = 0.16f;
    int brightnessPreset = 3;
    float specularBoost = 1.85f;
    float reflectionIntensity = 1.15f;
    float contactShadowIntensity = 0.65f;
    int calibrationPreset = 2;
    float calibrationStrength = 0.65f;
    int materialTypeHint = 4;
    float glossSliderValue = 0.62f;
    float paintGlossSliderValue = 0.55f;
    int paintGlossRouting = 0;
    float environmentIntensity = 1.0f;
    int environmentPreset = 0;
    float horizonStrength = 0.55f;
    float alphaCutoff = 0.5f;
    float emissiveIntensity = 0.0f;
    int materialPresetHint = 0;
    float clearcoatIntensity = 0.72f;
    float clearcoatRoughness = 0.28f;
    float reflectionContrast = 1.18f;
    float reflectionSaturation = 1.12f;
    float motionReflectionScale = 1.0f;
    float motionClearcoatScale = 1.0f;
    int glassEnabled = 0;
    float glassOpacity = 0.56f;
    float glassEdge = 1.55f;
    float glassRoughness = 0.14f;
    int glassTintPreset = 0;
    int glassRenderMode = 2;
    float glassClarity = 0.82f;
    float glassThickness = 0.34f;
    int activeGlassSlotCount = 1;
    int glassTrapMode = 0;
    int glassTrapDrawPass = 0;
};

inline const char* lightPresetName(int preset) {
    if (preset == 1) return "Studio";
    if (preset == 2) return "Outdoor";
    if (preset == 3) return "Bright";
    if (preset == 4) return "Ultra";
    return "Soft";
}

inline const char* environmentPresetName(int preset) {
    if (preset == 1) return "Outdoor";
    if (preset == 2) return "Warm Room";
    if (preset == 3) return "Cold Room";
    if (preset == 4) return "Sunset";
    if (preset == 5) return "Cave";
    return "Studio";
}

inline const char* materialDebugViewName(int view) {
    if (view == 1) return "BaseColor";
    if (view == 2) return "Normal";
    if (view == 3) return "Roughness";
    if (view == 4) return "Metallic";
    if (view == 5) return "AO";
    if (view == 6) return "Diffuse";
    if (view == 7) return "Specular";
    if (view == 8) return "F0";
    if (view == 9) return "Reflection";
    if (view == 10) return "IBL Diffuse";
    if (view == 11) return "IBL Specular";
    if (view == 12) return "BRDF Status";
    if (view == 13) return "Grounding / Contact Shadow";
    if (view == 14) return "Calibrated Albedo";
    if (view == 15) return "Material Type";
    if (view == 16) return "AO Influence";
    if (view == 17) return "Luminance Guard";
    if (view == 18) return "Gloss Response";
    if (view == 19) return "Specular Guard";
    if (view == 20) return "Paint Gloss";
    if (view == 21) return "Metal Response";
    if (view == 22) return "Paint Target";
    if (view == 23) return "Calibration Response";
    if (view == 24) return "Environment";
    if (view == 25) return "Reflection Direction";
    if (view == 26) return "Environment Color";
    if (view == 27) return "Selected Material";
    if (view == 28) return "Material Override";
    if (view == 29) return "Slot Metallic";
    if (view == 30) return "Slot Roughness";
    if (view == 31) return "Slot AO";
    if (view == 32) return "Alpha Mask";
    if (view == 33) return "Alpha Mode";
    if (view == 34) return "Double Sided";
    if (view == 35) return "Cutout Hint";
    if (view == 36) return "Transparency Status";
    if (view == 37) return "Emissive";
    if (view == 38) return "Preset Type";
    if (view == 39) return "Preset Response";
    if (view == 40) return "Material Energy Guard";
    if (view == 41) return "Selected Slot Preset";
    if (view == 42) return "Clearcoat";
    if (view == 43) return "Clearcoat Highlight";
    if (view == 44) return "Paint Layer";
    if (view == 45) return "Paint Energy Guard";
    if (view == 46) return "Fake Cubemap";
    if (view == 47) return "Reflection Zones";
    if (view == 48) return "Reflection Contrast";
    if (view == 49) return "Reflection Energy Guard";
    if (view == 50) return "Clearcoat Reflection";
    if (view == 51) return "Motion Quality";
    if (view == 52) return "Glass Mask";
    if (view == 53) return "Glass Opacity";
    if (view == 54) return "Glass Fresnel";
    if (view == 55) return "Glass Reflection";
    if (view == 56) return "Glass Tint";
    if (view == 57) return "Glass Safety Status";
    if (view == 58) return "Glass Polish";
    if (view == 59) return "Glass Edge";
    if (view == 60) return "Glass Thickness Fake";
    if (view == 61) return "Glass Reflection Polish";
    if (view == 62) return "Clearcoat Polish";
    if (view == 63) return "Paint Reflection";
    if (view == 64) return "Transparent Glass Mask";
    if (view == 65) return "Transparent Glass Alpha";
    if (view == 66) return "Transparent Glass Draw Order";
    if (view == 67) return "Transparent Glass Fallback";
    if (view == 68) return "Transparent Glass Safety";
    if (view == 69) return "Material Role";
    if (view == 70) return "Glass Candidate";
    if (view == 71) return "Active Glass Slot";
    if (view == 72) return "Transparent Routing";
    if (view == 73) return "Wrong Slot Guard";
    if (view == 74) return "Glass Center Alpha";
    if (view == 75) return "Glass Edge Reflection";
    if (view == 76) return "Glass Thickness";
    if (view == 77) return "Glass Clarity";
    if (view == 78) return "Glass Fallback Material";
    if (view == 79) return "Glass Final Composite";
    return "Final Shaded";
}

inline const char* materialPresetName(int preset) {
    if (preset == 1) return "Car Paint";
    if (preset == 2) return "Metal";
    if (preset == 3) return "Fabric";
    if (preset == 4) return "Rubber";
    if (preset == 5) return "Plastic";
    if (preset == 6) return "Glass Foundation";
    if (preset == 7) return "Emissive Safe";
    return "Balanced";
}

inline const char* calibrationPresetName(int preset) {
    if (preset == 1) return "Matte Safe";
    if (preset == 2) return "Balanced";
    if (preset == 3) return "Punchy";
    return "Neutral";
}

inline const char* materialTypeHintName(int hint) {
    if (hint == 0) return "fabric_like";
    if (hint == 1) return "paint_like";
    if (hint == 2) return "metal_like";
    if (hint == 3) return "rubber_like";
    if (hint == 5) return "cutout_like";
    if (hint == 6) return "glass_like";
    if (hint == 7) return "decal_like";
    if (hint == 8) return "emissive_like";
    return "unknown";
}

inline const char* glassTrapModeName(int mode) {
    if (mode == 1) return "Clean Path RED";
    if (mode == 2) return "Old/Fallback GREEN";
    if (mode == 3) return "Active Glass BLUE";
    if (mode == 4) return "Opaque Glass YELLOW";
    if (mode == 5) return "Hide Glass";
    if (mode == 6) return "Hide Non-Glass";
    if (mode == 7) return "Slot Heatmap";
    if (mode == 8) return "Full Shader Test PURPLE";
    if (mode == 9) return "Glass Candidates WHITE";
    if (mode == 10) return "Transparent Draw CYAN";
    return "Off";
}

inline const char* glassTrapPassName(int pass) {
    if (pass == 1) return "transparent";
    return "opaque";
}

inline const char* brightnessPresetName(int preset) {
    if (preset == 0) return "Low";
    if (preset == 2) return "Bright";
    if (preset == 3) return "Bright Preview";
    if (preset == 4) return "Ultra";
    return "Normal";
}

inline const char* toneMappingModeName(int mode) {
    if (mode == 2) return "aces_lite";
    if (mode == 0) return "none";
    return "reinhard";
}

struct PrimitiveDrawRange {
    uint32_t firstIndex = 0;
    uint32_t indexCount = 0;
    uint32_t firstVertex = 0;
    uint32_t vertexCount = 0;
    int materialSlot = 0;
    int textureSlot = -1;
};

struct MaterialSlotState {
    float baseColorFactor[4] = { 1.0f, 1.0f, 1.0f, 1.0f };
    float metallicFactor = 0.0f;
    float roughnessFactor = 1.0f;
    float normalScale = 1.0f;
    float occlusionStrength = 1.0f;
    int alphaMode = 0;
    float alphaCutoff = 0.5f;
    bool doubleSided = false;
    int baseColorTextureSlot = -1;
    int metallicRoughnessTextureSlot = -1;
    int normalTextureSlot = -1;
    int occlusionTextureSlot = -1;
    int materialTypeHint = 4;
    float emissiveFactor[3] = { 0.0f, 0.0f, 0.0f };
    int emissiveTextureSlot = -1;
    int materialPresetHint = 0;
};

enum MaterialRole {
    MaterialRoleOpaque = 0,
    MaterialRoleGlass = 1,
    MaterialRoleCutout = 2,
    MaterialRoleEmissive = 3,
    MaterialRoleHairThin = 4
};

struct ModelRenderState {
    std::string activeModelName = "none";
    std::string activeModelPath;
    int activePrimitiveIndex = 0;
    std::string gpuUploadStatus = "failed";
    std::string drawStatus = "fallback";
    uint32_t uploadedVertexCount = 0;
    uint32_t uploadedIndexCount = 0;
    const char* modelVertexLayout = "POSITION,NORMAL,TEXCOORD_0,COLOR_0,TANGENT";
    float boundsMin[3] = { 0.0f, 0.0f, 0.0f };
    float boundsMax[3] = { 0.0f, 0.0f, 0.0f };
    float boundsCenter[3] = { 0.0f, 0.0f, 0.0f };
    float modelScale = 1.0f;
    const char* modelRenderMode = "multi_primitive_static";
    uint32_t primitiveCountTotal = 0;
    uint32_t primitiveCountRendered = 0;
    uint32_t primitiveCountSkipped = 0;
    uint32_t unsupportedPrimitiveCount = 0;
    uint32_t materialSlotCount = 0;
    uint32_t materialSlotCountRendered = 0;
    uint32_t textureSlotCount = 0;
    uint32_t uploadedTextureCount = 0;
    uint32_t textureFallbackCount = 0;
    uint32_t skippedTextureCount = 0;
    uint32_t textureSlotLimit = 8;
    std::string pbrMapsStatus = "missing";
    std::string metallicRoughnessStatus = "missing";
    std::string normalMapStatus = "missing";
    std::string normalMapAppliedStatus = "missing";
    std::string occlusionMapStatus = "missing";
    std::string tangentStatus = "missing_or_blocked";
    std::string tangentSource = "missing";
    uint32_t tangentGeneratedCount = 0;
    uint32_t tangentFallbackGeneratedCount = 0;
    uint32_t tangentMissingCount = 0;
    uint32_t tangentDegenerateTriangleCount = 0;
    std::string tangentFallbackReason = "not_loaded";
    std::string tangentBuildMode = "once_on_upload";
    float metallicFactor = 0.0f;
    float roughnessFactor = 1.0f;
    float normalScale = 1.0f;
    float occlusionStrength = 1.0f;
    uint32_t pbrTextureSlotCount = 0;
    uint32_t uploadedPbrTextureCount = 0;
    uint32_t skippedPbrTextureCount = 0;
    uint32_t pbrTextureFallbackCount = 0;
    std::string materialSlotDiagnostics = "[]";
    std::string lightingStatus = "ok";
    float sunDirection[3] = { -0.35f, -0.82f, -0.45f };
    float sunColor[3] = { 1.0f, 0.96f, 0.88f };
    float sunIntensity = 2.0f;
    float ambientColor[3] = { 0.42f, 0.52f, 0.62f };
    float ambientIntensity = 0.80f;
    std::string lightPreset = "Bright";
    float specularBoost = 1.85f;
    std::string specularBoostStatus = "ok_uniform_controlled";
    float reflectionIntensity = 1.15f;
    std::string iblStatus = "ok_foundation";
    std::string iblMode = "procedural_directional_probe";
    std::string environmentIblStatus = "ok_foundation";
    std::string environmentIblMode = "procedural_directional_probe";
    std::string environmentSourceStatus = "ok_procedural_no_external_texture";
    std::string environmentSourceType = "procedural_directional_probe";
    std::string environmentSkyColorStatus = "ok_preset_uniform";
    std::string environmentGroundColorStatus = "ok_preset_uniform";
    std::string environmentHorizonStatus = "ok_directional_horizon_blend";
    std::string environmentPerformanceStatus = "ok_no_extra_pass_no_texture_upload";
    std::string iblDiffuseStatus = "ok_directional_sky_ground_diffuse";
    std::string iblSpecularStatus = "ok_reflection_direction_environment";
    std::string iblRoughnessResponseStatus = "ok_roughness_blurs_and_reduces_specular";
    std::string iblMetallicResponseStatus = "ok_metal_tints_reflection";
    std::string iblDielectricResponseStatus = "ok_subtle_f0_reflection";
    std::string iblFabricPreserveStatus = "ok_fabric_matte_preserved";
    std::string iblOverbrightGuardStatus = "ok_luminance_guarded";
    std::string environmentUiStatus = "ok_compact_lighting_controls";
    std::string environmentPreset = "Studio";
    float environmentIntensity = 1.0f;
    std::string environmentSliderStatus = "ok";
    std::string skyPresetStatus = "ok";
    std::string horizonControlStatus = "ok";
    float horizonStrength = 0.55f;
    std::string environmentUniformUpdateStatus = "ok_uniform_only";
    std::string environmentDebugViewStatus = "shader_applied";
    std::string reflectionDirectionDebugViewStatus = "shader_applied";
    std::string environmentColorDebugViewStatus = "shader_applied";
    std::string iblPerformanceStatus = "ok_shader_math_only_no_loops";
    std::string reflectionFoundationStatus = "p24_fake_cubemap_probe_foundation";
    std::string reflectionMode = "procedural_directional_probe";
    std::string environmentReflectionStatus = "p24_fake_cubemap_probe_no_texture";
    std::string environmentReflectionMode = "reflection_direction_sky_horizon_ground_side";
    std::string environmentSource = "procedural_directional_probe";
    std::string reflectionColorStatus = "ok_sky_horizon_ground_side_glint";
    std::string reflectionRoughnessResponseStatus = "ok_roughness_blur_approx";
    std::string metallicReflectionStatus = "ok_metal_tinted_stronger_guarded";
    std::string dielectricReflectionStatus = "ok_subtle_f0_environment";
    std::string reflectionPerformanceStatus = "ok_no_extra_pass_no_texture_rebuild";
    std::string inspectorUiStatus = "ok";
    std::string inspectorUiMode = "tabbed_compact_inspector";
    std::string activeInspectorTab = "Assets";
    std::string assetsTabStatus = "ok_import_scan_export_summary";
    std::string cameraTabStatus = "ok_camera_info_reset_zoom";
    std::string lightingTabStatus = "ok_sliders_environment_controls";
    std::string materialTabStatus = "ok_debug_views";
    std::string debugTabStatus = "ok_fps_zip_status";
    std::string contactGroundingStatus = "foundation_analytic";
    std::string contactShadowStatus = "enabled";
    std::string contactShadowMode = "analytic_blob_or_grounding_approx";
    float contactShadowIntensity = 0.65f;
    std::string contactShadowPerformanceStatus = "ok_uniform_only_no_shadow_pass";
    std::string groundingUsesModelBounds = "yes_upload_bounds_scaled_local";
    std::string groundingUniformUpdateStatus = "ok_uniform_only";
    std::string groundSliderStatus = "ok";
    std::string contactGroundingSliderStatus = "ok";
    std::string lightingControlStatus = "ok";
    std::string lightingUiMode = "compact_sliders";
    std::string lightingUniformUpdateStatus = "ok_uniform_only";
    std::string sliderUpdateMode = "uniform_only";
    std::string sliderTouchStatus = "ok_touch_targets";
    std::string sunSliderStatus = "ok";
    std::string ambientSliderStatus = "ok";
    std::string exposureSliderStatus = "ok";
    std::string specularSliderStatus = "ok";
    std::string reflectionSliderStatus = "ok";
    std::string brdfStatus = "ok";
    std::string brdfMode = "direct_lighting_schlick_mobile";
    std::string diffuseStatus = "ok_non_metal_diffuse";
    std::string specularStatus = "ok_p17_gloss_response_guarded";
    std::string fresnelStatus = "ok_schlick";
    std::string f0Status = "ok_dielectric_0_04_metal_base_color";
    std::string metallicResponseStatus = "ok_diffuse_reduced_f0_tinted";
    std::string roughnessResponseStatus = "ok_gloss_width_energy_remap";
    std::string directLightingStatus = "ok_single_sun_direct_gloss_lobe";
    std::string materialResponseStatus = "p24_fake_cubemap_probe_foundation";
    std::string pbrQualityTier = "mobile_direct_lighting_ibl_v1";
    std::string brdfPerformanceStatus = "ok_mobile_friendly_direct_lighting_ibl";
    std::string toneMappingStatus = "ok";
    std::string toneMappingMode = "reinhard";
    std::string exposureStatus = "ok";
    float exposureValue = 1.50f;
    float ambientFloor = 0.16f;
    std::string brightnessPreset = "Bright Preview";
    std::string activeDebugView = "Final Shaded";
    std::string debugViewStatus = "shader_applied";
    std::string normalDebugViewStatus = "shader_applied";
    std::string ndotlDebugViewStatus = "shader_applied";
    std::string diffuseDebugViewStatus = "shader_applied";
    std::string specularDebugViewStatus = "shader_applied";
    std::string f0DebugViewStatus = "shader_applied";
    std::string reflectionDebugViewStatus = "shader_applied";
    std::string iblDiffuseDebugViewStatus = "shader_applied";
    std::string iblSpecularDebugViewStatus = "shader_applied";
    std::string brdfStatusDebugViewStatus = "shader_applied";
    std::string groundingDebugViewStatus = "shader_applied";
    std::string materialCalibrationStatus = "ok";
    std::string materialCalibrationMode = "shader_uniform_upload_lightweight";
    std::string albedoEnergyStatus = "ok_normalized";
    std::string albedoClampStatus = "ok";
    std::string diffuseClampStatus = "ok";
    std::string luminanceGuardStatus = "ok";
    std::string aoCalibrationStatus = "ok_indirect_weighted";
    std::string roughnessRemapStatus = "ok";
    std::string metallicRoughnessClampStatus = "ok";
    std::string emissiveGuardStatus = "ok";
    std::string fabricMattePreserveStatus = "ok";
    std::string paintMaterialCalibrationStatus = "ok";
    std::string metalMaterialCalibrationStatus = "ok";
    std::string materialTypeHintStatus = "ok";
    std::string materialSlotCalibrationStatus = "ok";
    std::string calibrationUiStatus = "ok_compact_material_tab";
    std::string calibrationPreset = "Balanced";
    std::string calibrationSliderStatus = "ok";
    float calibrationSliderValue = 0.65f;
    std::string calibrationUniformUpdateStatus = "ok_uniform_only";
    std::string calibratedAlbedoDebugViewStatus = "shader_applied";
    std::string materialTypeDebugViewStatus = "shader_applied";
    std::string aoInfluenceDebugViewStatus = "shader_applied";
    std::string luminanceGuardDebugViewStatus = "shader_applied";
    float calibrationVisualStrength = 0.72f;
    std::string calibrationAffectsAlbedo = "yes_guarded_luminance_clamp";
    std::string calibrationAffectsAo = "yes_indirect_occlusion_weight";
    std::string calibrationAffectsRoughness = "yes_material_safe_remap";
    std::string calibrationVisibleResponseStatus = "ok_visible_final_shaded_response";
    std::string materialCalibrationPerformanceStatus = "ok_uniform_shader_no_rebuild";
    std::string specularGlossStatus = "ok";
    std::string specularGlossMode = "uniform_gloss_response_p17b";
    std::string specularResponseStatus = "ok_guarded_dielectric_metal";
    std::string glossResponseStatus = "ok_slider_controls_lobe_width";
    std::string roughnessRemapV2Status = "ok_calib_and_gloss_weighted";
    std::string metallicSpecularBoostStatus = "ok_metal_routed_boost";
    std::string dielectricGlossStatus = "ok_f0_guarded";
    std::string fabricSpecularSuppressStatus = "ok_matte_preserved";
    std::string specularOverbrightGuardStatus = "ok_luminance_guard";
    std::string viewDependentHighlightStatus = "ok_reflection_vector";
    std::string paintGlossLiteStatus = "ok";
    std::string paintGlossLiteMode = "uniform_lite_no_texture_rebuild";
    float paintGlossIntensity = 0.55f;
    float paintGlossRoughness = 0.45f;
    std::string paintGlossMaterialHintStatus = "ok_paint_like_only";
    std::string paintGlossPerformanceStatus = "ok_uniform_only";
    std::string paintGlossTargetStatus = "none";
    uint32_t paintGlossAppliedMaterialCount = 0;
    uint32_t paintGlossSkippedFabricCount = 0;
    std::string paintGlossFallbackRouting = "none";
    std::string paintGlossVisibleResponseStatus = "no_target";
    std::string glossSliderStatus = "ok";
    float glossSliderValue = 0.62f;
    std::string paintGlossSliderStatus = "ok";
    float paintGlossSliderValue = 0.55f;
    std::string glossUniformUpdateStatus = "ok_uniform_only";
    std::string glossResponseDebugViewStatus = "shader_applied";
    std::string specularGuardDebugViewStatus = "shader_applied";
    std::string paintGlossDebugViewStatus = "shader_applied";
    std::string metalResponseDebugViewStatus = "shader_applied";
    std::string paintTargetDebugViewStatus = "shader_applied";
    std::string calibrationResponseDebugViewStatus = "shader_applied";
    std::string materialTypeSpecularRoutingStatus = "ok";
    std::string paintMaterialGlossStatus = "ok_lite_gloss";
    std::string metalMaterialGlossStatus = "ok_stronger_response";
    std::string rubberMaterialGlossStatus = "ok_suppressed";
    std::string specularGlossPerformanceStatus = "ok_no_alloc_no_rebuild";
    std::string glossVisibleResponseStatus = "ok_visible_lobe_and_reflection";
    std::string glossAffectsSpecularLobe = "yes_shader_roughness_distribution";
    std::string glossAffectsReflectionWeight = "yes_shader_environment_weight";
    std::string materialSlotEditorStatus = "ok";
    int selectedMaterialSlot = 0;
    int selectedMaterialSlotCount = 0;
    std::string selectedMaterialTypeHint = "unknown";
    std::string selectedMaterialName = "unknown";
    std::string selectedMaterialSummaryStatus = "empty";
    std::string materialSlotSelectionUiStatus = "ok";
    std::string perMaterialOverrideStatus = "foundation_selected_slot_uniform";
    std::string perMaterialOverrideMode = "cpu_selected_slot_push_constants";
    float selectedSlotMetallicOverride = 0.0f;
    float selectedSlotRoughnessOverride = 1.0f;
    float selectedSlotNormalScaleOverride = 1.0f;
    float selectedSlotAoOverride = 1.0f;
    float selectedSlotGlossOverride = 0.0f;
    float selectedSlotCoatOverride = 0.0f;
    std::string selectedSlotOverrideApplied = "false_no_material_slot";
    std::string selectedSlotResetStatus = "not_run";
    std::string perMaterialUniformUpdateStatus = "ok_uniform_only";
    std::string materialSlotControlsUiStatus = "ok_compact";
    std::string metallicSlotSliderStatus = "ok";
    std::string roughnessSlotSliderStatus = "ok";
    std::string normalSlotSliderStatus = "ok";
    std::string aoSlotSliderStatus = "ok";
    std::string selectedMaterialDebugViewStatus = "shader_applied";
    std::string materialOverrideDebugViewStatus = "shader_applied";
    std::string slotMetallicDebugViewStatus = "shader_applied";
    std::string slotRoughnessDebugViewStatus = "shader_applied";
    std::string slotAoDebugViewStatus = "shader_applied";
    std::string perMaterialOverridePerformanceStatus = "ok_no_extra_pass_no_upload";
    std::string alphaMaterialStatus = "ok_opaque_materials";
    std::string alphaModeSupportStatus = "ok_opaque_mask_blend_metadata";
    std::string alphaMaskStatus = "ok_no_mask_material";
    std::string alphaBlendStatus = "ok_no_blend_material";
    std::string alphaCutoffStatus = "ok_uniform_control";
    float alphaCutoffValue = 0.5f;
    std::string alphaDiscardStatus = "inactive_opaque";
    std::string alphaTextureChannelStatus = "baseColor_alpha_channel_sampled_when_texture_ready";
    std::string alphaFallbackStatus = "none";
    std::string doubleSidedMaterialStatus = "ok_no_double_sided_material";
    std::string doubleSidedMode = "selected_slot_single_sided_or_none";
    std::string doubleSidedNormalStatus = "shader_gl_front_facing_normal_flip";
    std::string doubleSidedRasterStatus = "ok_pipeline_cull_none_no_new_permutation";
    std::string doubleSidedFallbackStatus = "none";
    std::string thinMaterialPolishStatus = "ok_cutout_double_sided_hint_foundation";
    std::string cutoutMaterialHintStatus = "ok_available";
    std::string fabricEdgeStatus = "ok_available";
    std::string glassMetadataStatus = "none";
    std::string decalMaterialHintStatus = "ok_available";
    std::string transparencyDeferredStatus = "ok_no_full_transparent_sorting_or_glass";
    std::string alphaUiStatus = "ok_compact_material_tab";
    std::string alphaCutoffSliderStatus = "ok";
    std::string alphaDebugViewStatus = "shader_applied";
    std::string doubleSidedDebugViewStatus = "shader_applied";
    std::string alphaResetButtonStatus = "ok";
    std::string alphaUniformUpdateStatus = "ok_uniform_only";
    std::string alphaSliderUpdateMode = "uniform_only";
    std::string alphaMaskDebugViewStatus = "shader_applied";
    std::string alphaModeDebugViewStatus = "shader_applied";
    std::string cutoutHintDebugViewStatus = "shader_applied";
    std::string transparencyStatusDebugViewStatus = "shader_applied";
    std::string alphaPerformanceStatus = "ok_no_new_pass_no_sorting_no_reupload";
    std::string alphaNoNewPassStatus = "ok";
    std::string alphaNoTextureRebuildStatus = "ok";
    std::string alphaNoModelReuploadStatus = "ok";
    std::string p20RuntimeWorkflowPreservedStatus = "ok";
    std::string p19SlotControlsPreservedStatus = "ok";
    std::string p18IblPreservedStatus = "ok";
    std::string p21AlphaPreservedStatus = "ok";
    std::string emissiveMaterialStatus = "ok_metadata_supported";
    std::string emissiveMode = "factor_uniform_only_no_light_contribution";
    std::string emissiveFactorStatus = "missing";
    std::string emissiveTextureStatus = "missing";
    float emissiveIntensity = 0.0f;
    std::string emissiveIntensityStatus = "ok_clamped";
    std::string emissiveColorStatus = "ok_guarded";
    std::string emissiveOverbrightGuardStatus = "ok_clamped";
    std::string emissiveLightingContributionStatus = "not_real_light_source";
    std::string emissivePerformanceStatus = "ok_no_bloom_no_new_pass";
    std::string materialPresetStatus = "ok";
    std::string activeMaterialPreset = "Balanced";
    std::string materialPresetMode = "selected_slot_uniform_only";
    int materialPresetAppliedSlot = 0;
    std::string materialPresetAppliedStatus = "not_applied";
    std::string materialPresetUiStatus = "ok_compact_material_tab";
    std::string materialPresetPerformanceStatus = "ok_no_model_reupload_no_texture_rebuild";
    std::string selectedSlotPresetStatus = "ok";
    std::string carPaintPresetStatus = "ok";
    std::string metalPresetStatus = "ok";
    std::string fabricPresetStatus = "ok";
    std::string rubberPresetStatus = "ok";
    std::string plasticPresetStatus = "ok";
    std::string glassMetadataPresetStatus = "glass_foundation_no_refraction";
    std::string emissivePresetStatus = "ok_safe_clamped";
    std::string materialPresetGuardStatus = "ok_energy_guarded";
    std::string presetCycleButtonStatus = "ok";
    std::string presetApplyButtonStatus = "ok";
    std::string emissiveSliderStatus = "ok";
    std::string emissiveUniformUpdateStatus = "ok_uniform_only";
    std::string materialResetButtonStatus = "ok";
    std::string materialUiScrollPreservedStatus = "ok";
    std::string emissiveDebugViewStatus = "shader_applied";
    std::string presetTypeDebugViewStatus = "shader_applied";
    std::string presetResponseDebugViewStatus = "shader_applied";
    std::string materialEnergyGuardDebugViewStatus = "shader_applied";
    std::string selectedSlotPresetDebugViewStatus = "shader_applied";
    std::string p22PerformanceStatus = "ok_no_new_pass_no_bloom_no_reupload";
    std::string emissiveNoBloomStatus = "ok";
    std::string emissiveNoNewPassStatus = "ok";
    std::string presetNoModelReuploadStatus = "ok";
    std::string presetNoTextureRebuildStatus = "ok";
    std::string clearcoatStatus = "available";
    std::string clearcoatMode = "single_pass_uniform_clearcoat";
    float clearcoatIntensity = 0.72f;
    float clearcoatRoughness = 0.28f;
    std::string clearcoatFresnelStatus = "ok_schlick_view_angle";
    std::string clearcoatHighlightStatus = "ok_view_dependent";
    std::string clearcoatMaterialRoutingStatus = "selected_slot_safe";
    std::string clearcoatOverbrightGuardStatus = "ok";
    std::string clearcoatPerformanceStatus = "ok_single_pass_no_texture_no_loop";
    std::string clearcoatAppliedStatus = "not_applied";
    float clearcoatWeight = 0.0f;
    float clearcoatRoughnessApplied = 1.0f;
    std::string clearcoatGuardApplied = "no";
    std::string carPaintLayerStatus = "ok";
    std::string carPaintPresetV2Status = "ok";
    std::string carPaintClearcoatStatus = "available";
    std::string paintLayerEnergyGuardStatus = "ok";
    std::string paintLayerMaterialHintStatus = "selected_slot";
    std::string clearcoatSliderStatus = "ok";
    float clearcoatSliderValue = 0.72f;
    std::string clearcoatRoughnessSliderStatus = "ok";
    float clearcoatRoughnessSliderValue = 0.28f;
    std::string clearcoatUniformUpdateStatus = "ok_uniform_only";
    std::string clearcoatUiStatus = "ok_compact_material_tab";
    std::string clearcoatDebugViewStatus = "shader_applied";
    std::string clearcoatHighlightDebugViewStatus = "shader_applied";
    std::string paintLayerDebugViewStatus = "shader_applied";
    std::string paintEnergyGuardDebugViewStatus = "shader_applied";
    std::string p22EmissivePreservedStatus = "ok";
    std::string p22PresetsPreservedStatus = "ok";
    std::string p23PerformanceStatus = "ok_single_pass_uniform_only";
    std::string clearcoatNoNewPassStatus = "ok";
    std::string clearcoatNoTextureRebuildStatus = "ok";
    std::string clearcoatNoModelReuploadStatus = "ok";
    std::string clearcoatNoTransparentSortingStatus = "ok";
    std::string fakeCubemapStatus = "ok";
    std::string fakeCubemapMode = "procedural_directional_probe";
    std::string fakeCubemapSourceStatus = "procedural_no_texture_no_render_pass";
    std::string environmentZoneStatus = "ok_sky_horizon_ground_side";
    std::string skyZoneStatus = "ok";
    std::string horizonZoneStatus = "ok";
    std::string groundZoneStatus = "ok";
    std::string sideReflectionZoneStatus = "ok";
    std::string fakeCubemapPerformanceStatus = "ok_shader_math_only_no_loops";
    std::string reflectionQualityStatus = "ok_p26_probe_polished";
    std::string reflectionContrastStatus = "ok_uniform_control";
    float reflectionContrastValue = 1.18f;
    std::string reflectionSaturationStatus = "ok_uniform_control";
    float reflectionSaturationValue = 1.12f;
    std::string roughnessReflectionBlurStatus = "ok_direction_blend_approx";
    std::string clearcoatReflectionBoostStatus = "ok_motion_guarded";
    std::string metalReflectionTintStatus = "ok_base_color_tinted";
    std::string fabricReflectionSuppressStatus = "ok_fabric_matte_preserved";
    std::string reflectionEnergyGuardStatus = "ok_luminance_guard";
    std::string reflectionOverbrightGuardStatus = "ok_clamped_before_tonemap";
    std::string reflectionQualityUiStatus = "ok_compact_controls";
    std::string reflectionContrastSliderStatus = "ok";
    std::string reflectionSaturationSliderStatus = "ok";
    std::string environmentZonePresetStatus = "ok";
    std::string environmentZonePreset = "Studio";
    std::string reflectionUniformUpdateStatus = "ok_uniform_only";
    std::string motionPerformanceGuardStatus = "ok";
    std::string cameraMotionStatus = "still";
    float cameraMotionSpeed = 0.0f;
    std::string cameraMotionQualityTier = "full";
    float cameraMotionQualityBlend = 1.0f;
    float motionReflectionScale = 1.0f;
    float motionClearcoatScale = 1.0f;
    std::string motionDiagnosticsThrottleStatus = "ok_ui_fps_only_no_export";
    std::string motionQualityRestoreStatus = "ok_smooth_restore";
    uint32_t motionQualityTransitionMs = 520;
    float cameraMovingFpsLast = 0.0f;
    float cameraStillFpsLast = 0.0f;
    float targetMovingFps = 45.0f;
    std::string movingFpsGuardStatus = "monitoring";
    std::string carPaintReflectionStatus = "ok_clearcoat_probe_separation";
    std::string metalReflectionStatus = "ok_tinted_stronger";
    std::string plasticReflectionStatus = "ok_glossy_limited";
    std::string rubberReflectionStatus = "ok_low_reflection";
    std::string glassMetadataReflectionStatus = "foundation_single_pass_fake_transparency";
    std::string materialPresetReflectionStatus = "ok";
    std::string fakeCubemapDebugViewStatus = "shader_applied";
    std::string reflectionZonesDebugViewStatus = "shader_applied";
    std::string reflectionContrastDebugViewStatus = "shader_applied";
    std::string reflectionEnergyGuardDebugViewStatus = "shader_applied";
    std::string clearcoatReflectionDebugViewStatus = "shader_applied";
    std::string motionQualityDebugViewStatus = "shader_applied";
    std::string p23ClearcoatPreservedStatus = "ok";
    std::string p24PerformanceStatus = "ok_no_new_pass_no_texture_no_rebuild";
    std::string fakeCubemapNoTextureStatus = "ok";
    std::string fakeCubemapNoNewPassStatus = "ok";
    std::string reflectionNoTextureRebuildStatus = "ok";
    std::string reflectionNoModelReuploadStatus = "ok";
    std::string noFrameFileWriteStatus = "ok";
    std::string noFrameGlbParseStatus = "ok";
    std::string p26ReflectionPolishStatus = "ok_zone_contrast_rim_roughness_polished";
    std::string reflectionZonePolishStatus = "ok_sky_horizon_ground_contrast_guarded";
    std::string sideRimReflectionPolishStatus = "ok_rim_zone_boost_guarded";
    std::string roughnessReflectionPolishStatus = "ok_smoother_mobile_response";
    std::string glassReflectionZoneStatus = "ok_glass_uses_p26_zone_probe";
    std::string clearcoatReflectionZoneStatus = "ok_clearcoat_uses_p26_zone_probe";
    std::string glassMaterialStatus = "available";
    std::string glassMode = "single_pass_fake_transparency_no_refraction";
    float glassOpacity = 0.56f;
    std::string glassTintStatus = "ok_preset_tint";
    std::string glassTintColor = "0.92,0.98,1.00";
    std::string glassFresnelStatus = "ok_stronger_schlick_edge";
    std::string glassEdgeReflectionStatus = "ok_p26_edge_fresnel_boost";
    std::string glassReflectionSourceStatus = "p24_fake_cubemap_probe";
    std::string glassRoughnessResponseStatus = "ok_clear_vs_rough_distinction";
    std::string glassThicknessFakeStatus = "ok_edge_tint_thickness_fake";
    std::string glassTransparencyMode = "safe_single_pass_fake_opacity";
    std::string glassSortingStatus = "safe_no_full_transparent_sorting";
    std::string glassRefractionStatus = "deferred_not_real_refraction";
    std::string glassPerformanceStatus = "ok_uniform_shader_no_pass_no_sort";
    std::string glassPolishStatus = "ok";
    std::string glassPolishMode = "single_pass_fake_glass_polish";
    std::string glassReadabilityStatus = "state_reported";
    std::string glassEdgePolishStatus = "ok_stronger_fresnel_rim";
    std::string glassTintPolishStatus = "ok_tint_blends_preserve_surface";
    std::string glassThicknessPolishStatus = "ok_fake_thickness_edge_dark_bright";
    std::string glassOpacityCurveStatus = "ok_minimum_surface_curve";
    std::string glassRoughnessPolishStatus = "ok_clear_vs_frosted_response";
    std::string glassReflectionPolishStatus = "ok_p24_probe_boost_guarded";
    std::string glassStillFakeTransparencyStatus = "yes_no_real_transparent_pass";
    std::string glassUiStatus = "ok_compact_material_tab";
    std::string glassEnableButtonStatus = "ok";
    std::string glassPresetStatus = "ok";
    std::string activeGlassPreset = "Clear Glass";
    std::string glassOpacitySliderStatus = "ok";
    float glassOpacityValue = 0.56f;
    std::string glassTintPresetStatus = "ok";
    std::string activeGlassTintPreset = "Clear";
    std::string glassEdgeSliderStatus = "ok";
    float glassEdgeValue = 1.55f;
    std::string glassRoughnessSliderStatus = "ok";
    float glassRoughnessValue = 0.14f;
    std::string glassUniformUpdateStatus = "ok_uniform_only";
    std::string glassPresetIntegrationStatus = "ok_selected_slot_only";
    int glassPresetAppliedSlot = 0;
    std::string glassPresetAppliedStatus = "available";
    std::string glassPresetPolishStatus = "ok";
    std::string clearGlassPresetStatus = "ok";
    std::string blueGlassPresetStatus = "ok";
    std::string greenGlassPresetStatus = "ok";
    std::string smokeGlassPresetStatus = "ok";
    std::string warmGlassPresetStatus = "ok";
    std::string magicGlassPresetStatus = "ok";
    std::string dirtyGlassLitePresetStatus = "ok";
    std::string crystalLitePresetStatus = "ok";
    std::string glassPresetVisualResponseStatus = "formula_attempted";
    std::string glassVisualQualityStatus = "runtime_visual_pending";
    std::string glassGreyPlateFixStatus = "formula_attempted";
    std::string glassClarityStatus = "state_reported";
    std::string glassCenterTransparencyStatus = "formula_attempted";
    std::string glassFakeThicknessStatus = "formula_attempted_edges_only";
    std::string glassPresetVisualStatus = "state_reported";
    std::string glassFallbackMaterialStatus = "state_reported";
    std::string glassWeakMaterialFallbackStatus = "state_reported";
    std::string glassNoAssetHardcodeStatus = "state_reported_no_model_name_hardcode";
    std::string p28dGlassFoundationRepairStatus = "pending";
    std::string glassVisualTruthStatus = "not_visually_verified";
    std::string glassFinalShadedFormulaStatus = "pending";
    std::string p28bGlassFixStatus = "state_reported";
    std::string p28cTransparentRenderFixStatus = "transparent_pipeline_bound";
    std::string glassDiscardBypassStatus = "state_reported";
    std::string glassFinalShaderAlphaStatus = "formula_attempted";
    std::string glassFinalShaderColorStatus = "formula_attempted";
    std::string glassFinalUsesLiveUniformsStatus = "state_reported";
    std::string transparentPipelineActuallyUsedStatus = "pending";
    std::string glassCutoutDisabledForTransparentStatus = "ok";
    std::string p21AlphaCutoutPreservedStatus = "ok";
    std::string glassCandidateScoringStatus = "ok_name_alpha_transmission_scoring";
    std::string glassBestCandidateStatus = "pending";
    std::string glassUniformAppliedToShaderStatus = "state_reported";
    std::string glassLiveSliderResponseStatus = "state_reported";
    std::string glassPresetLiveApplyStatus = "state_reported";
    std::string materialSlotDiagnosticsTruth = "metadata_only_not_shader_input";
    std::string shaderTruthSource = "push_constants_per_draw";
    std::string debugViewsAreVisualProof = "false";
    std::string pixelReadbackStatus = "not_implemented";
    std::string visualVerificationStatus = "manual_required_no_pixel_readback";
    std::string glassCpuEstimateStatus = "estimate_only_not_pixel_proof";
    std::string glassShaderFinalAlphaReadbackStatus = "not_available_no_pixel_readback";
    float glassCpuEstimatedCenterAlpha = 0.0f;
    float glassCpuEstimatedEdgeAlpha = 0.0f;
    std::string glassProofMode = "transparent_v1_shader_final";
    float shaderFinalGlassCenterAlpha = 0.0f;
    float shaderFinalGlassEdgeAlpha = 0.0f;
    float shaderFinalGlassFinalAlpha = 0.0f;
    float shaderFinalGlassTintStrength = 0.0f;
    std::string shaderFinalGlassRgbMode = "clear_center_visible_edge";
    std::string shaderFinalGlassUsesBaseColorFill = "false";
    std::string shaderFinalGlassCpuMirrorStatus = "mirrors_shader_formula_not_pixel_readback";
    float glassFinalCenterAlpha = 0.0f;
    float glassFinalEdgeAlpha = 0.0f;
    std::string glassFinalTintColor = "0.94,0.99,1.00";
    std::string glassActuallyTransparentStatus = "pending";
    std::string glassGreyPlateStillPossibleStatus = "unknown_until_runtime";
    std::string previousSystemsPreservedStatus = "state_reported";
    std::string selectedSlotDisplay = "none";
    std::string activeGlassSlotDisplay = "none";
    std::string glassApplyTargetStatus = "inactive";
    std::string selectedSlotPurpose = "ui_edit_target";
    std::string activeGlassSlotsPurpose = "transparent_render_routing";
    std::string debugInspectedSlotPurpose = "diagnostics_display_target";
    std::string debugInspectedMaterialSlotMode = "currently_selected_slot_alias";
    std::string selectedVsActiveGlassSlotStatus = "separate_concepts";
    std::string glassDiagnosticsHonestyStatus = "state_reported_no_pixel_readback";
    std::string glassVisualVerificationStatus = "manual_required_no_pixel_readback";
    std::string cameraHotPathDiagnosticsStatus = "not_throttled";
    int glassPresetCount = 7;
    std::string glassPresetClearStatus = "state_reported";
    std::string glassPresetSmokeStatus = "state_reported";
    std::string glassPresetGreenStatus = "state_reported";
    std::string glassPresetCrystalStatus = "state_reported";
    std::string glassPresetWarmStatus = "state_reported";
    std::string glassPresetDarkStatus = "state_reported";
    std::string glassPresetNoTextureDependencyStatus = "state_reported";
    float glassClarityValue = 0.82f;
    std::string glassClaritySliderStatus = "ok";
    float glassThicknessValue = 0.34f;
    std::string glassThicknessSliderStatus = "ok";
    std::string glassQualityUiStatus = "ok_minimal_material_tab";
    std::string glassQualitySummaryUiStatus = "state_reported";
    std::string activeGlassSummaryPreservedStatus = "ok";
    std::string glassCenterAlphaDebugViewStatus = "shader_applied";
    std::string glassEdgeReflectionDebugViewStatus = "shader_applied";
    std::string glassClarityDebugViewStatus = "shader_applied";
    std::string glassFallbackMaterialDebugViewStatus = "shader_applied";
    std::string glassFinalCompositeDebugViewStatus = "shader_applied";
    std::string glassMissingBaseColorFallbackStatus = "state_reported";
    std::string glassMissingRoughnessFallbackStatus = "state_reported";
    std::string glassOpaqueAlphaModeOverrideStatus = "state_reported";
    std::string glassFallbackOpacityStatus = "state_reported";
    std::string glassFallbackRoughnessStatus = "state_reported";
    std::string glassFallbackTintStatus = "state_reported";
    std::string glassSelectedSlotRoutingStatus = "state_reported";
    std::string glassFabricGuardStatus = "state_reported";
    std::string glassMetalGuardStatus = "state_reported";
    std::string glassCarPaintGuardStatus = "state_reported";
    std::string glassVisualResponseStatus = "runtime_visual_pending";
    std::string glassOpacityResponseStatus = "formula_attempted";
    std::string glassTintResponseStatus = "formula_attempted";
    std::string glassFresnelResponseStatus = "formula_attempted";
    std::string glassReflectionResponseStatus = "formula_attempted";
    std::string glassEnergyGuardStatus = "ok_clamped";
    std::string glassOverbrightGuardStatus = "ok";
    std::string glassInvisibleGuardStatus = "ok_minimum_surface_kept";
    std::string glassMaskDebugViewStatus = "shader_applied";
    std::string glassOpacityDebugViewStatus = "shader_applied";
    std::string glassFresnelDebugViewStatus = "shader_applied";
    std::string glassReflectionDebugViewStatus = "shader_applied";
    std::string glassTintDebugViewStatus = "shader_applied";
    std::string glassSafetyDebugViewStatus = "shader_applied";
    std::string glassPolishDebugViewStatus = "shader_applied";
    std::string glassEdgeDebugViewStatus = "shader_applied";
    std::string glassThicknessDebugViewStatus = "shader_applied";
    std::string glassReflectionPolishDebugViewStatus = "shader_applied";
    std::string clearcoatPolishDebugViewStatus = "shader_applied";
    std::string paintReflectionDebugViewStatus = "shader_applied";
    std::string p24ReflectionPreservedStatus = "ok";
    std::string p25GlassPreservedStatus = "ok";
    std::string p26UiChangeStatus = "minimal_material_tab_text_only";
    std::string glassSummaryUiStatus = "ok_compact_summary";
    std::string glassStrengthSliderStatus = "deferred_reusing_edge_opacity_roughness";
    std::string glassControlsPreservedStatus = "ok";
    std::string clearcoatPolishStatus = "ok";
    std::string clearcoatHighlightPolishStatus = "ok_clearer_guarded_highlight";
    std::string clearcoatReflectionSeparationStatus = "ok_layer_separated_from_base";
    std::string carPaintPolishStatus = "ok";
    std::string carPaintLayerReadabilityStatus = "ok_base_coat_reflection_separated";
    std::string carPaintReflectionSeparationStatus = "ok_paint_reflection_layer_readable";
    std::string paintOverbrightGuardStatus = "ok_clamped";
    std::string p25PerformanceStatus = "ok_single_pass_uniform_shader_math";
    std::string p26PerformanceStatus = "ok_single_pass_shader_math_no_rebuild";
    std::string p26NoRealRefractionStatus = "ok_deferred";
    std::string p26NoScreenRefractionStatus = "ok_deferred";
    std::string p26NoMirrorPassStatus = "ok_deferred";
    std::string p26NoFullSortingStatus = "ok_deferred";
    std::string p26NoTextureRebuildStatus = "ok";
    std::string p26NoModelReuploadStatus = "ok";
    std::string p26NoNewShadowPassStatus = "ok";
    std::string transparentGlassPassStatus = "transparent_pipeline_bound";
    std::string transparentGlassPassMode = "opaque_first_selected_glass_after";
    std::string transparentGlassSelectedSlotStatus = "available";
    std::string transparentGlassDrawOrderStatus = "opaque_first_then_selected_glass";
    std::string transparentGlassBlendStatus = "ok_vk_src_alpha_one_minus_src_alpha";
    std::string transparentGlassOpacityStatus = "ok_real_color_blend_alpha";
    std::string transparentGlassTintStatus = "ok_shader_tint";
    std::string transparentGlassFresnelStatus = "ok_edge_reflection_visible";
    std::string transparentGlassReflectionStatus = "ok_p26_fake_probe_preserved";
    std::string transparentGlassSortingStatus = "limited_selected_slot_no_full_sort";
    std::string transparentGlassRefractionStatus = "deferred_no_real_refraction";
    std::string transparentGlassFallbackStatus = "p26_fake_glass_available";
    std::string transparentGlassPerformanceStatus = "ok_one_extra_selected_slot_draw_when_active";
    std::string transparentGlassUiStatus = "ok_minimal_material_tab";
    std::string transparentGlassQualityStatus = "runtime_visual_pending";
    std::string transparentGlassCenterAlphaStatus = "formula_attempted";
    std::string transparentGlassEdgeAlphaStatus = "formula_attempted";
    std::string transparentGlassDepthBehaviorStatus = "transparent_pipeline_bound";
    std::string transparentGlassBackgroundVisibilityStatus = "not_visually_verified";
    std::string transparentGlassInteriorVisibilityStatus = "not_visually_verified";
    std::string transparentGlassBlendPreservedStatus = "ok_vk_src_alpha_one_minus_src_alpha";
    std::string transparentGlassPassPreservedStatus = "ok_opaque_first_active_glass_after";
    std::string glassRenderModeStatus = "state_reported_fake_safe_transparent_v1_auto";
    std::string activeGlassRenderMode = "Auto";
    std::string transparentGlassToggleStatus = "ok";
    std::string glassModeSummaryUiStatus = "ok";
    std::string p26GlassPolishPreservedStatus = "ok";
    std::string fakeGlassFallbackStatus = "available";
    std::string glassAutoFallbackStatus = "available_motion_or_non_glass";
    std::string glassMotionFallbackStatus = "available_motion_guard";
    std::string transparentGlassMaterialRoutingStatus = "selected_slot_only";
    int transparentGlassAppliedSlot = 0;
    uint32_t transparentGlassAppliedMaterialCount = 0;
    uint32_t transparentGlassSkippedOpaqueCount = 0;
    std::string materialRoleSystemStatus = "ok";
    std::string materialRoleDetectionMode = "metadata_name_alpha_hint_factor";
    std::string selectedMaterialRole = "Unknown";
    float selectedMaterialRoleConfidence = 0.0f;
    std::string selectedMaterialRoleSource = "none";
    uint32_t materialRoleCandidateCount = 0;
    uint32_t glassCandidateCount = 0;
    int bestGlassCandidateSlot = -1;
    std::string bestGlassCandidateName = "none";
    float bestGlassCandidateConfidence = 0.0f;
    std::string bestGlassCandidateSource = "none";
    std::string materialRoleNoHardcodeStatus = "ok_no_asset_specific_slot_hardcode";
    std::string transparentGlassRoutingStatus = "available";
    std::string transparentGlassRoutingMode = "auto_best_glass_candidate";
    int activeTransparentGlassSlot = -1;
    uint32_t activeTransparentGlassSlotCount = 0;
    std::string activeTransparentGlassSlotList = "none";
    std::string activeTransparentGlassMaterialName = "none";
    std::string activeTransparentGlassMaterialRole = "Unknown";
    std::string activeTransparentGlassRoleSource = "none";
    std::string activeTransparentGlassSlotSource = "none";
    std::string glassSlotPolicyVersion = "none";
    std::string glassSlotPolicyMode = "none";
    std::string glassSlotPolicyReason = "none";
    std::string activeTransparentGlassSlotIndices = "[]";
    std::string activeTransparentGlassSlotNames = "[]";
    std::string glassSlotRejectedCandidates = "[]";
    uint32_t skippedGlassLikeSlotCount = 0;
    std::string skippedGlassLikeSlotList = "none";
    std::string skippedGlassLikeSlotReasons = "none";
    int selectedMaterialSlotIndex = -1;
    std::string selectedMaterialSlotName = "none";
    std::string selectedMaterialSlotRole = "Unknown";
    int manualGlassSlotIndex = -1;
    std::string manualGlassSlotName = "none";
    std::string opaquePassSkippedGlassSlots = "none";
    std::string transparentPassRenderedGlassSlots = "none";
    std::string duplicateTransmissionVolumeSkipped = "false";
    std::string glassSlotDrawDiagnostics = "[]";
    std::string universalGlassSlotTruthTable = "[]";
    int glassTrapModeIndex = 0;
    std::string glassTrapModeName = "Off";
    std::string glassTrapModeRuntimeEnabled = "false";
    std::string glassTrapLastFrameActive = "false";
    std::string glassTrapLastFrameAnyCleanPath = "false";
    std::string glassTrapLastFrameAnyOldFallback = "false";
    std::string glassTrapLastFrameAnyOpaqueGlass = "false";
    std::string glassTrapLastFrameAnyTransparentGlass = "false";
    std::string glassTrapLastFrameAnyFullShaderTest = "false";
    std::string glassTrapLastFrameAnySlotHeatmap = "false";
    int glassTrapLastDrawSlotIndex = -1;
    std::string glassTrapLastDrawMaterialName = "none";
    std::string glassTrapLastDrawPassName = "none";
    std::string glassTrapLastDrawCleanPathUsed = "false";
    std::string glassTrapLastDrawOldFallbackUsed = "false";
    std::string glassTrapLastDrawOpaqueUsed = "false";
    std::string glassTrapLastDrawTransparentUsed = "false";
    float glassTrapLastDrawOpacity = 0.0f;
    float glassTrapLastDrawEdge = 0.0f;
    int glassTrapLastDrawTintPreset = 0;
    float glassTrapLastDrawClarity = 0.0f;
    float glassTrapLastDrawThickness = 0.0f;
    float glassTrapLastDrawRoughness = 0.0f;
    std::string glassTrapLastDrawFormulaVersion = "not_observed";
    std::string transparentGlassSelectedSlotAllowedStatus = "inactive";
    std::string transparentGlassSelectedSlotRejectedStatus = "inactive";
    std::string transparentGlassAutoDetectStatus = "available";
    std::string transparentGlassManualOverrideStatus = "inactive";
    std::string transparentGlassFallbackReason = "none";
    std::string transparentGlassWrongSlotGuardStatus = "non_glass_slots_not_transparent_by_default";
    uint32_t glassSlotsCount = 0;
    std::string glassSlotsDisplay = "none";
    std::string opaqueSlotsDisplay = "none";
    std::string cutoutSlotsDisplay = "none";
    uint32_t transparentGlassSlotLimit = 4;
    uint32_t transparentGlassSlotsRendered = 0;
    std::string glassSingleSlotDrawRemoved = "yes";
    std::string glassUsesSlotList = "yes";
    std::string glassSlotListStatus = "auto_glass_slots";
    uint32_t glassActiveSlotCount = 0;
    std::string glassActiveSlotList = "none";
    float glassLiveOpacity = 0.0f;
    float glassShaderOpacityInput = 0.0f;
    float glassLiveClarity = 1.0f;
    float glassShaderClarityInput = 1.0f;
    float glassLiveThickness = 0.0f;
    float glassShaderThicknessInput = 0.0f;
    std::string glassPresetMixRemovedStatus = "shader_uses_live_uniforms_directly";
    std::string glassShaderPresetMixStatus = "shader_uses_live_push_constants_directly";
    std::string glassPresetMixInShader = "no";
    std::string glassUsesNormalMaterialRgb = "no";
    std::string glassFinalVisualVerified = "not_available_no_pixel_readback";
    std::string glassEnabledControlsShaderBranch = "yes";
    std::string glassOpacityZeroExpectedCenterClear = "yes";
    std::string glassOpacitySixExpectedCenterDense = "yes";
    std::string glassDebugTruthStatus = "state_reported_not_visual_proof";
    std::string gitCommitContainsP28H = "yes";
    std::string apkBuiltFromCommittedTree = "yes";
    std::string glassCpuGpuMismatchRisk = "medium_no_pixel_readback";
    std::string glassRuntimeTruthSource = "live_push_constants";
    std::string glassVisualFormulaVersion = "P28I_light_center_visible_edge";
    float glassEffectiveCenterAlpha = 0.0f;
    float glassEffectiveEdgeAlpha = 0.0f;
    float glassEffectiveLayerCompensation = 1.0f;
    float glassEffectiveTintStrength = 0.06f;
    std::string glassVisualVerified = "not_available_no_pixel_readback";
    std::string legacyGlassMaterialReportNotShaderTruth = "yes";
    std::string glassRoute = "disabled";
    std::string glassRouteReason = "disabled_by_user";
    std::string glassVisualBranchActive = "no";
    std::string glassTransparentPassActive = "no";
    std::string glassFakeFallbackActive = "no";
    std::string glassRouteIsVisualProof = "false";
    std::string materialPresetRole = "fills_live_sliders";
    std::string materialPresetIsShaderTruth = "false";
    std::string glassLiveControlsAfterPreset = "true";
    std::string glassOpacityTruth = "live_push_constant";
    std::string glassClarityTruth = "live_push_constant";
    std::string glassThicknessTruth = "live_push_constant";
    std::string glassRoughnessTruth = "live_push_constant";
    std::string glassTintPresetShaderUse = "tint_lookup_only";
    std::string materialRoleUiStatus = "ok_minimal_material_tab";
    std::string selectedSlotRoleSummaryUiStatus = "ok";
    std::string activeGlassSlotSummaryUiStatus = "ok";
    std::string selectGlassCandidateButtonStatus = "ok";
    std::string assignSelectedAsGlassButtonStatus = "ok";
    std::string clearManualRoleButtonStatus = "ok";
    std::string selectedSlotHighlightToggleStatus = "diagnostic_only_deferred";
    uint32_t transparentGlassSkippedNonGlassCount = 0;
    uint32_t transparentGlassSkippedFabricCount = 0;
    uint32_t transparentGlassSkippedMetalCount = 0;
    uint32_t transparentGlassSkippedPaintCount = 0;
    std::string p27TransparentPassPreservedStatus = "ok";
    std::string p28VisualGlassStatus = "runtime_visual_pending";
    std::string p27bRoutingPreservedStatus = "ok";
    std::string p28PerformanceStatus = "ok_uniform_shader_math_only";
    std::string p28NoRaytraceStatus = "ok";
    std::string p28NoSsrStatus = "ok";
    std::string p28NoRealMirrorStatus = "ok";
    std::string p28NoRealRefractionStatus = "ok";
    std::string p28NoShadowStatus = "ok";
    std::string p28NoCsmStatus = "ok";
    std::string p28NoOffscreenCubemapStatus = "ok";
    std::string p28NoTextureRebuildStatus = "ok";
    std::string p28NoModelReuploadStatus = "ok";
    std::string p28NoFrameGlbParseStatus = "ok";
    std::string p28NoFrameFileWriteStatus = "ok";
    std::string p28UniformOnlyStatus = "ok";
    std::string p27bPerformanceStatus = "ok_existing_transparent_pass_only";
    std::string p27bNoExtraHeavyPassStatus = "ok";
    std::string p27bNoTextureRebuildStatus = "ok";
    std::string p27bNoModelReuploadStatus = "ok";
    std::string p27bNoFrameGlbParseStatus = "ok";
    std::string p27bNoFrameFileWriteStatus = "ok";
    std::string p27bNoShadowStatus = "ok";
    std::string p27bNoRealMirrorStatus = "ok";
    std::string p27bNoSsrStatus = "ok";
    std::string p27bNoRealRefractionStatus = "ok";
    std::string materialRoleDebugViewStatus = "shader_applied";
    std::string glassCandidateDebugViewStatus = "shader_applied";
    std::string activeGlassSlotDebugViewStatus = "shader_applied";
    std::string transparentRoutingDebugViewStatus = "shader_applied";
    std::string wrongSlotGuardDebugViewStatus = "shader_applied";
    std::string transparentGlassFabricGuardStatus = "ok";
    std::string transparentGlassMetalGuardStatus = "ok";
    std::string transparentGlassCarPaintGuardStatus = "ok";
    std::string transparentGlassMaskDebugViewStatus = "shader_applied";
    std::string transparentGlassAlphaDebugViewStatus = "shader_applied";
    std::string transparentGlassDrawOrderDebugViewStatus = "shader_applied";
    std::string transparentGlassFallbackDebugViewStatus = "shader_applied";
    std::string transparentGlassSafetyDebugViewStatus = "shader_applied";
    std::string p27PerformanceStatus = "ok_selected_slot_extra_draw_only";
    std::string p27NoShadowStatus = "ok";
    std::string p27NoRaytraceStatus = "ok";
    std::string p27NoSsrStatus = "ok";
    std::string p27NoRealMirrorStatus = "ok";
    std::string p27NoScreenRefractionStatus = "ok";
    std::string p27NoTextureRebuildStatus = "ok";
    std::string p27NoModelReuploadStatus = "ok";
    std::string glassNoRefractionPassStatus = "ok";
    std::string glassNoScreenRefractionStatus = "ok";
    std::string glassNoFullSortingStatus = "ok";
    std::string glassNoTextureRebuildStatus = "ok";
    std::string glassNoModelReuploadStatus = "ok";
    std::string glassNoNewShadowPassStatus = "ok";
    float fpsCurrent = 0.0f;
    float frameTimeMs = 0.0f;
    float fpsLastStable = 0.0f;
    float frameTimeLastStableMs = 0.0f;
    std::string fpsSource = "not_ready";
    std::string fpsStatus = "not_ready";
    std::string fpsUpdateMode = "java_choreographer_live";
    uint32_t fpsSampleWindowMs = 1000;
    uint64_t framesRenderedLive = 0;
    uint32_t modelUploadRepeatCount = 0;
    uint32_t uploadGenerationId = 0;
    std::string renderLoopAllocationGuardStatus = "ok_no_java_glb_parse_or_upload_in_frame_callback";
    std::string debugZipStatus = "not_run";
    std::string debugZipPath = "";
    std::string debugZipIncludedFiles = "";
    std::string debugZipReason = "not_run";
    bool fallbackCubeVisible = true;
    std::string meshDrawStatus = "fallback";
    std::string fallbackCubeStatus = "on";
    std::string textureUploadStatus = "missing";
    std::string baseColorTextureStatus = "missing";
    std::string baseColorTextureName = "none";
    std::string baseColorTextureSource = "none";
    std::string baseColorTextureMimeType = "none";
    uint32_t textureWidth = 0;
    uint32_t textureHeight = 0;
    uint32_t textureBytes = 0;
    bool textureFallbackUsed = true;
    std::string reason = "no active model";

    bool modelReady() const {
        return gpuUploadStatus == "ok" && (drawStatus == "ok" || drawStatus == "partial_ok") && uploadedVertexCount > 0 && primitiveCountRendered > 0;
    }
};

struct Mat4 {
    float m[16]{};

    static Mat4 identity() {
        Mat4 out{};
        out.m[0] = 1.0f;
        out.m[5] = 1.0f;
        out.m[10] = 1.0f;
        out.m[15] = 1.0f;
        return out;
    }
};

struct PushConstants {
    Mat4 mvp;
    MaterialConstants material;
};

inline Mat4 multiply(const Mat4& a, const Mat4& b) {
    Mat4 out{};
    for (int col = 0; col < 4; ++col) {
        for (int row = 0; row < 4; ++row) {
            out.m[col * 4 + row] =
                a.m[0 * 4 + row] * b.m[col * 4 + 0] +
                a.m[1 * 4 + row] * b.m[col * 4 + 1] +
                a.m[2 * 4 + row] * b.m[col * 4 + 2] +
                a.m[3 * 4 + row] * b.m[col * 4 + 3];
        }
    }
    return out;
}

inline Mat4 translation(float x, float y, float z) {
    Mat4 out = Mat4::identity();
    out.m[12] = x;
    out.m[13] = y;
    out.m[14] = z;
    return out;
}

inline Mat4 rotationY(float radians) {
    Mat4 out = Mat4::identity();
    const float c = std::cos(radians);
    const float s = std::sin(radians);
    out.m[0] = c;
    out.m[2] = -s;
    out.m[8] = s;
    out.m[10] = c;
    return out;
}

inline Mat4 rotationX(float radians) {
    Mat4 out = Mat4::identity();
    const float c = std::cos(radians);
    const float s = std::sin(radians);
    out.m[5] = c;
    out.m[6] = s;
    out.m[9] = -s;
    out.m[10] = c;
    return out;
}

inline Mat4 perspective(float fovyRadians, float aspect, float nearPlane, float farPlane) {
    Mat4 out{};
    const float f = 1.0f / std::tan(fovyRadians * 0.5f);
    out.m[0] = f / aspect;
    out.m[5] = -f;
    out.m[10] = farPlane / (farPlane - nearPlane);
    out.m[11] = 1.0f;
    out.m[14] = -(farPlane * nearPlane) / (farPlane - nearPlane);
    return out;
}

inline std::string vkResultName(VkResult r) {
    switch (r) {
        case VK_SUCCESS: return "VK_SUCCESS";
        case VK_NOT_READY: return "VK_NOT_READY";
        case VK_TIMEOUT: return "VK_TIMEOUT";
        case VK_EVENT_SET: return "VK_EVENT_SET";
        case VK_EVENT_RESET: return "VK_EVENT_RESET";
        case VK_INCOMPLETE: return "VK_INCOMPLETE";
        case VK_ERROR_OUT_OF_HOST_MEMORY: return "VK_ERROR_OUT_OF_HOST_MEMORY";
        case VK_ERROR_OUT_OF_DEVICE_MEMORY: return "VK_ERROR_OUT_OF_DEVICE_MEMORY";
        case VK_ERROR_INITIALIZATION_FAILED: return "VK_ERROR_INITIALIZATION_FAILED";
        case VK_ERROR_DEVICE_LOST: return "VK_ERROR_DEVICE_LOST";
        case VK_ERROR_MEMORY_MAP_FAILED: return "VK_ERROR_MEMORY_MAP_FAILED";
        case VK_ERROR_LAYER_NOT_PRESENT: return "VK_ERROR_LAYER_NOT_PRESENT";
        case VK_ERROR_EXTENSION_NOT_PRESENT: return "VK_ERROR_EXTENSION_NOT_PRESENT";
        case VK_ERROR_FEATURE_NOT_PRESENT: return "VK_ERROR_FEATURE_NOT_PRESENT";
        case VK_ERROR_INCOMPATIBLE_DRIVER: return "VK_ERROR_INCOMPATIBLE_DRIVER";
        case VK_ERROR_TOO_MANY_OBJECTS: return "VK_ERROR_TOO_MANY_OBJECTS";
        case VK_ERROR_FORMAT_NOT_SUPPORTED: return "VK_ERROR_FORMAT_NOT_SUPPORTED";
        case VK_ERROR_SURFACE_LOST_KHR: return "VK_ERROR_SURFACE_LOST_KHR";
        case VK_ERROR_NATIVE_WINDOW_IN_USE_KHR: return "VK_ERROR_NATIVE_WINDOW_IN_USE_KHR";
        case VK_SUBOPTIMAL_KHR: return "VK_SUBOPTIMAL_KHR";
        case VK_ERROR_OUT_OF_DATE_KHR: return "VK_ERROR_OUT_OF_DATE_KHR";
        default: { char b[64]; std::snprintf(b, sizeof(b), "VkResult(%d)", (int)r); return b; }
    }
}

inline const char* deviceTypeName(VkPhysicalDeviceType t) {
    switch (t) {
        case VK_PHYSICAL_DEVICE_TYPE_OTHER: return "OTHER";
        case VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU: return "INTEGRATED_GPU";
        case VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU: return "DISCRETE_GPU";
        case VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU: return "VIRTUAL_GPU";
        case VK_PHYSICAL_DEVICE_TYPE_CPU: return "CPU";
        default: return "UNKNOWN";
    }
}

inline void ensureDir(const std::string& path) {
    std::string cur;
    for (char c : path) { cur.push_back(c); if (c == '/') mkdir(cur.c_str(), 0775); }
    mkdir(path.c_str(), 0775);
}

inline bool endsWith(const std::string& s, const std::string& suffix) {
    return s.size() >= suffix.size() && s.compare(s.size() - suffix.size(), suffix.size(), suffix) == 0;
}

inline std::string escapeJson(const std::string& s) {
    std::ostringstream o;
    for (char c : s) {
        switch (c) {
            case '\\': o << "\\\\"; break;
            case '"': o << "\\\""; break;
            case '\n': o << "\\n"; break;
            case '\r': o << "\\r"; break;
            case '\t': o << "\\t"; break;
            default: o << c;
        }
    }
    return o.str();
}

inline std::string reportDirFor(const std::string& outputRoot) {
    std::string root = outputRoot.empty() ? "/storage/emulated/0/SOLUMCreative" : outputRoot;
    if (endsWith(root, "/diagnostics/latest") || endsWith(root, "/solum_diagnostics")) return root;
    return root + "/diagnostics/latest";
}

} // namespace solum
