#pragma once
#include "render_lab.hpp"
#include "renderer_types.hpp"

namespace solum {

struct RuntimeDiagnostics {
    std::string outputRoot;
    std::string status = "created";
    std::string reason;
    std::string gpuName = "unknown";
    std::string gpuType = "unknown";
    std::string apiVersion = "unknown";
    VkFormat swapchainFormat = VK_FORMAT_UNDEFINED;
    VkExtent2D extent{};
    bool rendererCoreReady = false;
    bool vertexBufferReady = false;
    bool indexBufferReady = false;
    bool cubeReady = false;
    bool depthReady = false;
    bool cameraReady = false;
    bool cameraMvpReady = false;
    bool cameraControlsReady = false;
    bool uniformOrPushConstantsReady = false;
    bool materialConstantsReady = false;
    bool meshAttributeLayoutReady = false;
    bool triangleDrawn = false;
    uint32_t vertexCount = 0;
    uint32_t indexCount = 0;
    uint32_t vertexStrideBytes = 0;
    CameraState camera;
    MaterialConstants material;
    uint64_t framesRendered = 0;
    RenderLabState renderLab;
    ModelRenderState model;

    void write(const std::string& newStatus, const std::string& newReason) {
        status = newStatus;
        reason = newReason;
        std::string dir = reportDirFor(outputRoot);
        ensureDir(dir + "/");
        std::ofstream f(dir + "/runtime_vulkan_caps.json");
        f << "{\n";
        f << "  \"schema\": \"solum.runtime_vulkan_caps\",\n";
        f << "  \"schemaVersion\": 2,\n";
        f << "  \"status\": \"" << escapeJson(status) << "\",\n";
        f << "  \"reason\": \"" << escapeJson(reason) << "\",\n";
        f << "  \"rendererPath\": \"Android Native Vulkan\",\n";
        f << "  \"rendererCoreReady\": " << (rendererCoreReady ? "true" : "false") << ",\n";
        f << "  \"assetImportStatus\": \"" << (model.activeModelName == "none" ? "no active model" : "active model") << "\",\n";
        f << "  \"activeModelName\": \"" << escapeJson(model.activeModelName) << "\",\n";
        f << "  \"activeModelPath\": \"" << escapeJson(model.activeModelPath) << "\",\n";
        f << "  \"activePrimitiveIndex\": " << model.activePrimitiveIndex << ",\n";
        f << "  \"gpuUploadStatus\": \"" << escapeJson(model.gpuUploadStatus) << "\",\n";
        f << "  \"drawStatus\": \"" << escapeJson(model.drawStatus) << "\",\n";
        f << "  \"meshDrawStatus\": \"" << escapeJson(model.meshDrawStatus) << "\",\n";
        f << "  \"textureUploadStatus\": \"" << escapeJson(model.textureUploadStatus) << "\",\n";
        f << "  \"baseColorTextureStatus\": \"" << escapeJson(model.baseColorTextureStatus) << "\",\n";
        f << "  \"baseColorTextureName\": \"" << escapeJson(model.baseColorTextureName) << "\",\n";
        f << "  \"baseColorTextureSource\": \"" << escapeJson(model.baseColorTextureSource) << "\",\n";
        f << "  \"baseColorTextureMimeType\": \"" << escapeJson(model.baseColorTextureMimeType) << "\",\n";
        f << "  \"textureWidth\": " << model.textureWidth << ",\n";
        f << "  \"textureHeight\": " << model.textureHeight << ",\n";
        f << "  \"textureBytes\": " << model.textureBytes << ",\n";
        f << "  \"textureFallbackUsed\": " << (model.textureFallbackUsed ? "true" : "false") << ",\n";
        f << "  \"uploadedVertexCount\": " << model.uploadedVertexCount << ",\n";
        f << "  \"uploadedIndexCount\": " << model.uploadedIndexCount << ",\n";
        f << "  \"modelVertexLayout\": \"" << model.modelVertexLayout << "\",\n";
        f << "  \"modelBoundsMin\": [" << model.boundsMin[0] << ", " << model.boundsMin[1] << ", " << model.boundsMin[2] << "],\n";
        f << "  \"modelBoundsMax\": [" << model.boundsMax[0] << ", " << model.boundsMax[1] << ", " << model.boundsMax[2] << "],\n";
        f << "  \"modelBoundsCenter\": [" << model.boundsCenter[0] << ", " << model.boundsCenter[1] << ", " << model.boundsCenter[2] << "],\n";
        f << "  \"modelScale\": " << model.modelScale << ",\n";
        f << "  \"modelRenderMode\": \"" << model.modelRenderMode << "\",\n";
        f << "  \"primitiveCountTotal\": " << model.primitiveCountTotal << ",\n";
        f << "  \"primitiveCountRendered\": " << model.primitiveCountRendered << ",\n";
        f << "  \"primitiveCountSkipped\": " << model.primitiveCountSkipped << ",\n";
        f << "  \"unsupportedPrimitiveCount\": " << model.unsupportedPrimitiveCount << ",\n";
        f << "  \"materialSlotCount\": " << model.materialSlotCount << ",\n";
        f << "  \"materialSlotCountRendered\": " << model.materialSlotCountRendered << ",\n";
        f << "  \"textureSlotCount\": " << model.textureSlotCount << ",\n";
        f << "  \"uploadedTextureCount\": " << model.uploadedTextureCount << ",\n";
        f << "  \"textureFallbackCount\": " << model.textureFallbackCount << ",\n";
        f << "  \"skippedTextureCount\": " << model.skippedTextureCount << ",\n";
        f << "  \"textureSlotLimit\": " << model.textureSlotLimit << ",\n";
        f << "  \"pbrMapsStatus\": \"" << escapeJson(model.pbrMapsStatus) << "\",\n";
        f << "  \"metallicRoughnessStatus\": \"" << escapeJson(model.metallicRoughnessStatus) << "\",\n";
        f << "  \"normalMapStatus\": \"" << escapeJson(model.normalMapStatus) << "\",\n";
        f << "  \"normalMapAppliedStatus\": \"" << escapeJson(model.normalMapAppliedStatus) << "\",\n";
        f << "  \"occlusionMapStatus\": \"" << escapeJson(model.occlusionMapStatus) << "\",\n";
        f << "  \"tangentStatus\": \"" << escapeJson(model.tangentStatus) << "\",\n";
        f << "  \"tangentSource\": \"" << escapeJson(model.tangentSource) << "\",\n";
        f << "  \"tangentGeneratedCount\": " << model.tangentGeneratedCount << ",\n";
        f << "  \"tangentMissingCount\": " << model.tangentMissingCount << ",\n";
        f << "  \"tangentFallbackReason\": \"" << escapeJson(model.tangentFallbackReason) << "\",\n";
        f << "  \"metallicFactor\": " << model.metallicFactor << ",\n";
        f << "  \"roughnessFactor\": " << model.roughnessFactor << ",\n";
        f << "  \"normalScale\": " << model.normalScale << ",\n";
        f << "  \"occlusionStrength\": " << model.occlusionStrength << ",\n";
        f << "  \"pbrTextureSlotCount\": " << model.pbrTextureSlotCount << ",\n";
        f << "  \"uploadedPbrTextureCount\": " << model.uploadedPbrTextureCount << ",\n";
        f << "  \"skippedPbrTextureCount\": " << model.skippedPbrTextureCount << ",\n";
        f << "  \"pbrTextureFallbackCount\": " << model.pbrTextureFallbackCount << ",\n";
        f << "  \"materialSlotDiagnostics\": " << (model.materialSlotDiagnostics.empty() ? "[]" : model.materialSlotDiagnostics) << ",\n";
        f << "  \"lightingStatus\": \"" << escapeJson(model.lightingStatus) << "\",\n";
        f << "  \"sunDirection\": [" << model.sunDirection[0] << ", " << model.sunDirection[1] << ", " << model.sunDirection[2] << "],\n";
        f << "  \"sunColor\": [" << model.sunColor[0] << ", " << model.sunColor[1] << ", " << model.sunColor[2] << "],\n";
        f << "  \"sunIntensity\": " << model.sunIntensity << ",\n";
        f << "  \"ambientColor\": [" << model.ambientColor[0] << ", " << model.ambientColor[1] << ", " << model.ambientColor[2] << "],\n";
        f << "  \"ambientIntensity\": " << model.ambientIntensity << ",\n";
        f << "  \"lightPreset\": \"" << escapeJson(model.lightPreset) << "\",\n";
        f << "  \"materialResponseStatus\": \"" << escapeJson(model.materialResponseStatus) << "\",\n";
        f << "  \"toneMappingStatus\": \"" << escapeJson(model.toneMappingStatus) << "\",\n";
        f << "  \"toneMappingMode\": \"" << escapeJson(model.toneMappingMode) << "\",\n";
        f << "  \"exposureStatus\": \"" << escapeJson(model.exposureStatus) << "\",\n";
        f << "  \"exposureValue\": " << model.exposureValue << ",\n";
        f << "  \"ambientFloor\": " << model.ambientFloor << ",\n";
        f << "  \"brightnessPreset\": \"" << escapeJson(model.brightnessPreset) << "\",\n";
        f << "  \"activeDebugView\": \"" << escapeJson(model.activeDebugView) << "\",\n";
        f << "  \"debugViewStatus\": \"" << escapeJson(model.debugViewStatus) << "\",\n";
        f << "  \"normalDebugViewStatus\": \"" << escapeJson(model.normalDebugViewStatus) << "\",\n";
        f << "  \"ndotlDebugViewStatus\": \"" << escapeJson(model.ndotlDebugViewStatus) << "\",\n";
        f << "  \"fpsCurrent\": " << model.fpsCurrent << ",\n";
        f << "  \"frameTimeMs\": " << model.frameTimeMs << ",\n";
        f << "  \"fpsSource\": \"" << model.fpsSource << "\",\n";
        f << "  \"debugZipStatus\": \"" << escapeJson(model.debugZipStatus) << "\",\n";
        f << "  \"debugZipPath\": \"" << escapeJson(model.debugZipPath) << "\",\n";
        f << "  \"debugZipIncludedFiles\": \"" << escapeJson(model.debugZipIncludedFiles) << "\",\n";
        f << "  \"debugZipReason\": \"" << escapeJson(model.debugZipReason) << "\",\n";
        f << "  \"fallbackCubeVisible\": " << (model.fallbackCubeVisible ? "true" : "false") << ",\n";
        f << "  \"fallbackCubeStatus\": \"" << escapeJson(model.fallbackCubeStatus) << "\",\n";
        f << "  \"deviceName\": \"" << escapeJson(gpuName) << "\",\n";
        f << "  \"deviceType\": \"" << escapeJson(gpuType) << "\",\n";
        f << "  \"apiVersion\": \"" << escapeJson(apiVersion) << "\",\n";
        f << "  \"swapchainFormat\": " << (int)swapchainFormat << ",\n";
        f << "  \"extent\": { \"width\": " << extent.width << ", \"height\": " << extent.height << " },\n";
        f << "  \"vertexBufferReady\": " << (vertexBufferReady ? "true" : "false") << ",\n";
        f << "  \"indexBufferReady\": " << (indexBufferReady ? "true" : "false") << ",\n";
        f << "  \"uniformOrPushConstantsReady\": " << (uniformOrPushConstantsReady ? "true" : "false") << ",\n";
        f << "  \"vertexCount\": " << vertexCount << ",\n";
        f << "  \"indexCount\": " << indexCount << ",\n";
        f << "  \"framesRendered\": " << framesRendered << ",\n";
        f << "  \"cubeStatus\": \"" << (cubeReady || !model.fallbackCubeVisible ? "ok" : "failed") << "\",\n";
        f << "  \"depthStatus\": \"" << (depthReady ? "ok" : "failed") << "\",\n";
        f << "  \"cameraStatus\": \"" << (cameraReady ? "ok" : "failed") << "\",\n";
        f << "  \"cameraMvpStatus\": \"" << (cameraMvpReady ? "ok" : "failed") << "\",\n";
        f << "  \"cameraControlsStatus\": \"" << (cameraControlsReady ? "ok" : "not_implemented") << "\",\n";
        f << "  \"cameraYawDeg\": " << camera.yawDeg << ",\n";
        f << "  \"cameraPitchDeg\": " << camera.pitchDeg << ",\n";
        f << "  \"cameraDistance\": " << camera.distance << ",\n";
        f << "  \"materialConstantsReady\": " << (materialConstantsReady ? "true" : "false") << ",\n";
        f << "  \"meshAttributeLayoutReady\": " << (meshAttributeLayoutReady ? "true" : "false") << ",\n";
        f << "  \"vertexLayout\": \"POSITION,NORMAL,TEXCOORD_0,COLOR_0,TANGENT\",\n";
        f << "  \"vertexStrideBytes\": " << vertexStrideBytes << ",\n";
        f << "  \"material\": {\n";
        f << "    \"materialId\": " << material.materialId << ",\n";
        f << "    \"baseColorFactor\": [" << material.baseColorFactor[0] << ", " << material.baseColorFactor[1] << ", " << material.baseColorFactor[2] << ", " << material.baseColorFactor[3] << "],\n";
        f << "    \"metallicFactor\": " << material.metallicFactor << ",\n";
        f << "    \"roughnessFactor\": " << material.roughnessFactor << ",\n";
        f << "    \"normalScale\": " << material.normalScale << ",\n";
        f << "    \"occlusionStrength\": " << material.occlusionStrength << ",\n";
        f << "    \"emissiveFactor\": [" << material.emissiveFactor[0] << ", " << material.emissiveFactor[1] << ", " << material.emissiveFactor[2] << "],\n";
        f << "    \"alphaMode\": \"OPAQUE\"\n";
        f << "  },\n";
        f << "  \"screenshot\": { \"status\": \"not_available\", \"reason\": \"renderer_readback_not_implemented\" },\n";
        f << "  \"triangleDrawn\": " << (triangleDrawn ? "true" : "false") << ",\n";
        renderLab.writeJsonFields(f);
        f << "\n";
        f << "}\n";
    }
};

} // namespace solum
