#pragma once
#include "render_lab.hpp"
#include "renderer_types.hpp"

namespace solum {

struct RuntimeDiagnostics {
    std::string outputRoot;
    std::string status = "created";
    std::string reason;
    std::string gpuName = "unknown";
    std::string gpuType = "unknown";
    std::string apiVersion = "unknown";
    VkFormat swapchainFormat = VK_FORMAT_UNDEFINED;
    VkExtent2D extent{};
    bool rendererCoreReady = false;
    bool vertexBufferReady = false;
    bool indexBufferReady = false;
    bool cubeReady = false;
    bool depthReady = false;
    bool cameraReady = false;
    bool cameraMvpReady = false;
    bool cameraControlsReady = false;
    bool uniformOrPushConstantsReady = false;
    bool materialConstantsReady = false;
    bool meshAttributeLayoutReady = false;
    bool triangleDrawn = false;
    uint32_t vertexCount = 0;
    uint32_t indexCount = 0;
    uint32_t vertexStrideBytes = 0;
    CameraState camera;
    MaterialConstants material;
    uint64_t framesRendered = 0;
    RenderLabState renderLab;
    ModelRenderState model;

    void write(const std::string& newStatus, const std::string& newReason) {
        status = newStatus;
        reason = newReason;
        std::string dir = reportDirFor(outputRoot);
        ensureDir(dir + "/");
        std::ofstream f(dir + "/runtime_vulkan_caps.json");
        f << "{\n";
        f << "  \"schema\": \"solum.runtime_vulkan_caps\",\n";
        f << "  \"schemaVersion\": 2,\n";
        f << "  \"status\": \"" << escapeJson(status) << "\",\n";
        f << "  \"reason\": \"" << escapeJson(reason) << "\",\n";
        f << "  \"rendererPath\": \"Android Native Vulkan\",\n";
        f << "  \"rendererCoreReady\": " << (rendererCoreReady ? "true" : "false") << ",\n";
        f << "  \"assetImportStatus\": \"" << (model.activeModelName == "none" ? "no active model" : "active model") << "\",\n";
        f << "  \"activeModelName\": \"" << escapeJson(model.activeModelName) << "\",\n";
        f << "  \"activeModelPath\": \"" << escapeJson(model.activeModelPath) << "\",\n";
        f << "  \"activePrimitiveIndex\": " << model.activePrimitiveIndex << ",\n";
        f << "  \"gpuUploadStatus\": \"" << escapeJson(model.gpuUploadStatus) << "\",\n";
        f << "  \"drawStatus\": \"" << escapeJson(model.drawStatus) << "\",\n";
        f << "  \"meshDrawStatus\": \"" << escapeJson(model.meshDrawStatus) << "\",\n";
        f << "  \"textureUploadStatus\": \"" << escapeJson(model.textureUploadStatus) << "\",\n";
        f << "  \"baseColorTextureStatus\": \"" << escapeJson(model.baseColorTextureStatus) << "\",\n";
        f << "  \"baseColorTextureName\": \"" << escapeJson(model.baseColorTextureName) << "\",\n";
        f << "  \"baseColorTextureSource\": \"" << escapeJson(model.baseColorTextureSource) << "\",\n";
        f << "  \"baseColorTextureMimeType\": \"" << escapeJson(model.baseColorTextureMimeType) << "\",\n";
        f << "  \"textureWidth\": " << model.textureWidth << ",\n";
        f << "  \"textureHeight\": " << model.textureHeight << ",\n";
        f << "  \"textureBytes\": " << model.textureBytes << ",\n";
        f << "  \"textureFallbackUsed\": " << (model.textureFallbackUsed ? "true" : "false") << ",\n";
        f << "  \"uploadedVertexCount\": " << model.uploadedVertexCount << ",\n";
        f << "  \"uploadedIndexCount\": " << model.uploadedIndexCount << ",\n";
        f << "  \"modelVertexLayout\": \"" << model.modelVertexLayout << "\",\n";
        f << "  \"modelBoundsMin\": [" << model.boundsMin[0] << ", " << model.boundsMin[1] << ", " << model.boundsMin[2] << "],\n";
        f << "  \"modelBoundsMax\": [" << model.boundsMax[0] << ", " << model.boundsMax[1] << ", " << model.boundsMax[2] << "],\n";
        f << "  \"modelBoundsCenter\": [" << model.boundsCenter[0] << ", " << model.boundsCenter[1] << ", " << model.boundsCenter[2] << "],\n";
        f << "  \"modelScale\": " << model.modelScale << ",\n";
        f << "  \"modelRenderMode\": \"" << model.modelRenderMode << "\",\n";
        f << "  \"primitiveCountTotal\": " << model.primitiveCountTotal << ",\n";
        f << "  \"primitiveCountRendered\": " << model.primitiveCountRendered << ",\n";
        f << "  \"primitiveCountSkipped\": " << model.primitiveCountSkipped << ",\n";
        f << "  \"unsupportedPrimitiveCount\": " << model.unsupportedPrimitiveCount << ",\n";
        f << "  \"materialSlotCount\": " << model.materialSlotCount << ",\n";
        f << "  \"materialSlotCountRendered\": " << model.materialSlotCountRendered << ",\n";
        f << "  \"textureSlotCount\": " << model.textureSlotCount << ",\n";
        f << "  \"uploadedTextureCount\": " << model.uploadedTextureCount << ",\n";
        f << "  \"textureFallbackCount\": " << model.textureFallbackCount << ",\n";
        f << "  \"skippedTextureCount\": " << model.skippedTextureCount << ",\n";
        f << "  \"textureSlotLimit\": " << model.textureSlotLimit << ",\n";
        f << "  \"pbrMapsStatus\": \"" << escapeJson(model.pbrMapsStatus) << "\",\n";
        f << "  \"metallicRoughnessStatus\": \"" << escapeJson(model.metallicRoughnessStatus) << "\",\n";
        f << "  \"normalMapStatus\": \"" << escapeJson(model.normalMapStatus) << "\",\n";
        f << "  \"normalMapAppliedStatus\": \"" << escapeJson(model.normalMapAppliedStatus) << "\",\n";
        f << "  \"occlusionMapStatus\": \"" << escapeJson(model.occlusionMapStatus) << "\",\n";
        f << "  \"tangentStatus\": \"" << escapeJson(model.tangentStatus) << "\",\n";
        f << "  \"tangentSource\": \"" << escapeJson(model.tangentSource) << "\",\n";
        f << "  \"tangentGeneratedCount\": " << model.tangentGeneratedCount << ",\n";
        f << "  \"tangentFallbackGeneratedCount\": " << model.tangentFallbackGeneratedCount << ",\n";
        f << "  \"tangentMissingCount\": " << model.tangentMissingCount << ",\n";
        f << "  \"tangentDegenerateTriangleCount\": " << model.tangentDegenerateTriangleCount << ",\n";
        f << "  \"tangentFallbackReason\": \"" << escapeJson(model.tangentFallbackReason) << "\",\n";
        f << "  \"tangentBuildMode\": \"" << escapeJson(model.tangentBuildMode) << "\",\n";
        f << "  \"metallicFactor\": " << model.metallicFactor << ",\n";
        f << "  \"roughnessFactor\": " << model.roughnessFactor << ",\n";
        f << "  \"normalScale\": " << model.normalScale << ",\n";
        f << "  \"occlusionStrength\": " << model.occlusionStrength << ",\n";
        f << "  \"pbrTextureSlotCount\": " << model.pbrTextureSlotCount << ",\n";
        f << "  \"uploadedPbrTextureCount\": " << model.uploadedPbrTextureCount << ",\n";
        f << "  \"skippedPbrTextureCount\": " << model.skippedPbrTextureCount << ",\n";
        f << "  \"pbrTextureFallbackCount\": " << model.pbrTextureFallbackCount << ",\n";
        f << "  \"materialSlotDiagnostics\": " << (model.materialSlotDiagnostics.empty() ? "[]" : model.materialSlotDiagnostics) << ",\n";
        f << "  \"lightingStatus\": \"" << escapeJson(model.lightingStatus) << "\",\n";
        f << "  \"lightingControlStatus\": \"" << escapeJson(model.lightingControlStatus) << "\",\n";
        f << "  \"lightingUiMode\": \"" << escapeJson(model.lightingUiMode) << "\",\n";
        f << "  \"sunDirection\": [" << model.sunDirection[0] << ", " << model.sunDirection[1] << ", " << model.sunDirection[2] << "],\n";
        f << "  \"sunColor\": [" << model.sunColor[0] << ", " << model.sunColor[1] << ", " << model.sunColor[2] << "],\n";
        f << "  \"sunIntensity\": " << model.sunIntensity << ",\n";
        f << "  \"ambientColor\": [" << model.ambientColor[0] << ", " << model.ambientColor[1] << ", " << model.ambientColor[2] << "],\n";
        f << "  \"ambientIntensity\": " << model.ambientIntensity << ",\n";
        f << "  \"lightPreset\": \"" << escapeJson(model.lightPreset) << "\",\n";
        f << "  \"specularBoost\": " << model.specularBoost << ",\n";
        f << "  \"specularBoostStatus\": \"" << escapeJson(model.specularBoostStatus) << "\",\n";
        f << "  \"reflectionIntensity\": " << model.reflectionIntensity << ",\n";
        f << "  \"iblStatus\": \"" << escapeJson(model.iblStatus) << "\",\n";
        f << "  \"iblMode\": \"" << escapeJson(model.iblMode) << "\",\n";
        f << "  \"environmentIblStatus\": \"" << escapeJson(model.environmentIblStatus) << "\",\n";
        f << "  \"environmentIblMode\": \"" << escapeJson(model.environmentIblMode) << "\",\n";
        f << "  \"environmentSourceStatus\": \"" << escapeJson(model.environmentSourceStatus) << "\",\n";
        f << "  \"environmentSourceType\": \"" << escapeJson(model.environmentSourceType) << "\",\n";
        f << "  \"environmentSkyColorStatus\": \"" << escapeJson(model.environmentSkyColorStatus) << "\",\n";
        f << "  \"environmentGroundColorStatus\": \"" << escapeJson(model.environmentGroundColorStatus) << "\",\n";
        f << "  \"environmentHorizonStatus\": \"" << escapeJson(model.environmentHorizonStatus) << "\",\n";
        f << "  \"environmentPerformanceStatus\": \"" << escapeJson(model.environmentPerformanceStatus) << "\",\n";
        f << "  \"iblDiffuseStatus\": \"" << escapeJson(model.iblDiffuseStatus) << "\",\n";
        f << "  \"iblSpecularStatus\": \"" << escapeJson(model.iblSpecularStatus) << "\",\n";
        f << "  \"iblRoughnessResponseStatus\": \"" << escapeJson(model.iblRoughnessResponseStatus) << "\",\n";
        f << "  \"iblMetallicResponseStatus\": \"" << escapeJson(model.iblMetallicResponseStatus) << "\",\n";
        f << "  \"iblDielectricResponseStatus\": \"" << escapeJson(model.iblDielectricResponseStatus) << "\",\n";
        f << "  \"iblFabricPreserveStatus\": \"" << escapeJson(model.iblFabricPreserveStatus) << "\",\n";
        f << "  \"iblOverbrightGuardStatus\": \"" << escapeJson(model.iblOverbrightGuardStatus) << "\",\n";
        f << "  \"environmentUiStatus\": \"" << escapeJson(model.environmentUiStatus) << "\",\n";
        f << "  \"environmentPreset\": \"" << escapeJson(model.environmentPreset) << "\",\n";
        f << "  \"environmentIntensity\": " << model.environmentIntensity << ",\n";
        f << "  \"environmentSliderStatus\": \"" << escapeJson(model.environmentSliderStatus) << "\",\n";
        f << "  \"skyPresetStatus\": \"" << escapeJson(model.skyPresetStatus) << "\",\n";
        f << "  \"horizonControlStatus\": \"" << escapeJson(model.horizonControlStatus) << "\",\n";
        f << "  \"environmentUniformUpdateStatus\": \"" << escapeJson(model.environmentUniformUpdateStatus) << "\",\n";
        f << "  \"environmentDebugViewStatus\": \"" << escapeJson(model.environmentDebugViewStatus) << "\",\n";
        f << "  \"reflectionDirectionDebugViewStatus\": \"" << escapeJson(model.reflectionDirectionDebugViewStatus) << "\",\n";
        f << "  \"environmentColorDebugViewStatus\": \"" << escapeJson(model.environmentColorDebugViewStatus) << "\",\n";
        f << "  \"iblPerformanceStatus\": \"" << escapeJson(model.iblPerformanceStatus) << "\",\n";
        f << "  \"reflectionFoundationStatus\": \"" << escapeJson(model.reflectionFoundationStatus) << "\",\n";
        f << "  \"reflectionMode\": \"" << escapeJson(model.reflectionMode) << "\",\n";
        f << "  \"environmentReflectionStatus\": \"" << escapeJson(model.environmentReflectionStatus) << "\",\n";
        f << "  \"environmentReflectionMode\": \"" << escapeJson(model.environmentReflectionMode) << "\",\n";
        f << "  \"environmentSource\": \"" << escapeJson(model.environmentSource) << "\",\n";
        f << "  \"reflectionColorStatus\": \"" << escapeJson(model.reflectionColorStatus) << "\",\n";
        f << "  \"reflectionRoughnessResponseStatus\": \"" << escapeJson(model.reflectionRoughnessResponseStatus) << "\",\n";
        f << "  \"metallicReflectionStatus\": \"" << escapeJson(model.metallicReflectionStatus) << "\",\n";
        f << "  \"dielectricReflectionStatus\": \"" << escapeJson(model.dielectricReflectionStatus) << "\",\n";
        f << "  \"reflectionPerformanceStatus\": \"" << escapeJson(model.reflectionPerformanceStatus) << "\",\n";
        f << "  \"inspectorUiStatus\": \"" << escapeJson(model.inspectorUiStatus) << "\",\n";
        f << "  \"inspectorUiMode\": \"" << escapeJson(model.inspectorUiMode) << "\",\n";
        f << "  \"activeInspectorTab\": \"" << escapeJson(model.activeInspectorTab) << "\",\n";
        f << "  \"assetsTabStatus\": \"" << escapeJson(model.assetsTabStatus) << "\",\n";
        f << "  \"cameraTabStatus\": \"" << escapeJson(model.cameraTabStatus) << "\",\n";
        f << "  \"lightingTabStatus\": \"" << escapeJson(model.lightingTabStatus) << "\",\n";
        f << "  \"materialTabStatus\": \"" << escapeJson(model.materialTabStatus) << "\",\n";
        f << "  \"debugTabStatus\": \"" << escapeJson(model.debugTabStatus) << "\",\n";
        f << "  \"contactGroundingStatus\": \"" << escapeJson(model.contactGroundingStatus) << "\",\n";
        f << "  \"contactShadowStatus\": \"" << escapeJson(model.contactShadowStatus) << "\",\n";
        f << "  \"contactShadowMode\": \"" << escapeJson(model.contactShadowMode) << "\",\n";
        f << "  \"contactShadowIntensity\": " << model.contactShadowIntensity << ",\n";
        f << "  \"contactShadowPerformanceStatus\": \"" << escapeJson(model.contactShadowPerformanceStatus) << "\",\n";
        f << "  \"groundingUsesModelBounds\": \"" << escapeJson(model.groundingUsesModelBounds) << "\",\n";
        f << "  \"groundingUniformUpdateStatus\": \"" << escapeJson(model.groundingUniformUpdateStatus) << "\",\n";
        f << "  \"groundSliderStatus\": \"" << escapeJson(model.groundSliderStatus) << "\",\n";
        f << "  \"contactGroundingSliderStatus\": \"" << escapeJson(model.contactGroundingSliderStatus) << "\",\n";
        f << "  \"lightingUniformUpdateStatus\": \"" << escapeJson(model.lightingUniformUpdateStatus) << "\",\n";
        f << "  \"sliderUpdateMode\": \"" << escapeJson(model.sliderUpdateMode) << "\",\n";
        f << "  \"sliderTouchStatus\": \"" << escapeJson(model.sliderTouchStatus) << "\",\n";
        f << "  \"sunSliderStatus\": \"" << escapeJson(model.sunSliderStatus) << "\",\n";
        f << "  \"ambientSliderStatus\": \"" << escapeJson(model.ambientSliderStatus) << "\",\n";
        f << "  \"exposureSliderStatus\": \"" << escapeJson(model.exposureSliderStatus) << "\",\n";
        f << "  \"specularSliderStatus\": \"" << escapeJson(model.specularSliderStatus) << "\",\n";
        f << "  \"reflectionSliderStatus\": \"" << escapeJson(model.reflectionSliderStatus) << "\",\n";
        f << "  \"materialResponseStatus\": \"" << escapeJson(model.materialResponseStatus) << "\",\n";
        f << "  \"toneMappingStatus\": \"" << escapeJson(model.toneMappingStatus) << "\",\n";
        f << "  \"toneMappingMode\": \"" << escapeJson(model.toneMappingMode) << "\",\n";
        f << "  \"exposureStatus\": \"" << escapeJson(model.exposureStatus) << "\",\n";
        f << "  \"exposureValue\": " << model.exposureValue << ",\n";
        f << "  \"ambientFloor\": " << model.ambientFloor << ",\n";
        f << "  \"brightnessPreset\": \"" << escapeJson(model.brightnessPreset) << "\",\n";
        f << "  \"activeDebugView\": \"" << escapeJson(model.activeDebugView) << "\",\n";
        f << "  \"debugViewStatus\": \"" << escapeJson(model.debugViewStatus) << "\",\n";
        f << "  \"normalDebugViewStatus\": \"" << escapeJson(model.normalDebugViewStatus) << "\",\n";
        f << "  \"ndotlDebugViewStatus\": \"" << escapeJson(model.ndotlDebugViewStatus) << "\",\n";
        f << "  \"diffuseDebugViewStatus\": \"" << escapeJson(model.diffuseDebugViewStatus) << "\",\n";
        f << "  \"specularDebugViewStatus\": \"" << escapeJson(model.specularDebugViewStatus) << "\",\n";
        f << "  \"f0DebugViewStatus\": \"" << escapeJson(model.f0DebugViewStatus) << "\",\n";
        f << "  \"reflectionDebugViewStatus\": \"" << escapeJson(model.reflectionDebugViewStatus) << "\",\n";
        f << "  \"iblDiffuseDebugViewStatus\": \"" << escapeJson(model.iblDiffuseDebugViewStatus) << "\",\n";
        f << "  \"iblSpecularDebugViewStatus\": \"" << escapeJson(model.iblSpecularDebugViewStatus) << "\",\n";
        f << "  \"brdfStatusDebugViewStatus\": \"" << escapeJson(model.brdfStatusDebugViewStatus) << "\",\n";
        f << "  \"groundingDebugViewStatus\": \"" << escapeJson(model.groundingDebugViewStatus) << "\",\n";
        f << "  \"materialCalibrationStatus\": \"" << escapeJson(model.materialCalibrationStatus) << "\",\n";
        f << "  \"materialCalibrationMode\": \"" << escapeJson(model.materialCalibrationMode) << "\",\n";
        f << "  \"albedoEnergyStatus\": \"" << escapeJson(model.albedoEnergyStatus) << "\",\n";
        f << "  \"albedoClampStatus\": \"" << escapeJson(model.albedoClampStatus) << "\",\n";
        f << "  \"diffuseClampStatus\": \"" << escapeJson(model.diffuseClampStatus) << "\",\n";
        f << "  \"luminanceGuardStatus\": \"" << escapeJson(model.luminanceGuardStatus) << "\",\n";
        f << "  \"aoCalibrationStatus\": \"" << escapeJson(model.aoCalibrationStatus) << "\",\n";
        f << "  \"roughnessRemapStatus\": \"" << escapeJson(model.roughnessRemapStatus) << "\",\n";
        f << "  \"metallicRoughnessClampStatus\": \"" << escapeJson(model.metallicRoughnessClampStatus) << "\",\n";
        f << "  \"emissiveGuardStatus\": \"" << escapeJson(model.emissiveGuardStatus) << "\",\n";
        f << "  \"fabricMattePreserveStatus\": \"" << escapeJson(model.fabricMattePreserveStatus) << "\",\n";
        f << "  \"paintMaterialCalibrationStatus\": \"" << escapeJson(model.paintMaterialCalibrationStatus) << "\",\n";
        f << "  \"metalMaterialCalibrationStatus\": \"" << escapeJson(model.metalMaterialCalibrationStatus) << "\",\n";
        f << "  \"materialTypeHintStatus\": \"" << escapeJson(model.materialTypeHintStatus) << "\",\n";
        f << "  \"materialSlotCalibrationStatus\": \"" << escapeJson(model.materialSlotCalibrationStatus) << "\",\n";
        f << "  \"calibrationUiStatus\": \"" << escapeJson(model.calibrationUiStatus) << "\",\n";
        f << "  \"calibrationPreset\": \"" << escapeJson(model.calibrationPreset) << "\",\n";
        f << "  \"calibrationSliderStatus\": \"" << escapeJson(model.calibrationSliderStatus) << "\",\n";
        f << "  \"calibrationSliderValue\": " << model.calibrationSliderValue << ",\n";
        f << "  \"calibrationUniformUpdateStatus\": \"" << escapeJson(model.calibrationUniformUpdateStatus) << "\",\n";
        f << "  \"calibratedAlbedoDebugViewStatus\": \"" << escapeJson(model.calibratedAlbedoDebugViewStatus) << "\",\n";
        f << "  \"materialTypeDebugViewStatus\": \"" << escapeJson(model.materialTypeDebugViewStatus) << "\",\n";
        f << "  \"aoInfluenceDebugViewStatus\": \"" << escapeJson(model.aoInfluenceDebugViewStatus) << "\",\n";
        f << "  \"luminanceGuardDebugViewStatus\": \"" << escapeJson(model.luminanceGuardDebugViewStatus) << "\",\n";
        f << "  \"calibrationVisualStrength\": " << model.calibrationVisualStrength << ",\n";
        f << "  \"calibrationAffectsAlbedo\": \"" << escapeJson(model.calibrationAffectsAlbedo) << "\",\n";
        f << "  \"calibrationAffectsAo\": \"" << escapeJson(model.calibrationAffectsAo) << "\",\n";
        f << "  \"calibrationAffectsRoughness\": \"" << escapeJson(model.calibrationAffectsRoughness) << "\",\n";
        f << "  \"calibrationVisibleResponseStatus\": \"" << escapeJson(model.calibrationVisibleResponseStatus) << "\",\n";
        f << "  \"materialCalibrationPerformanceStatus\": \"" << escapeJson(model.materialCalibrationPerformanceStatus) << "\",\n";
        f << "  \"specularGlossStatus\": \"" << escapeJson(model.specularGlossStatus) << "\",\n";
        f << "  \"specularGlossMode\": \"" << escapeJson(model.specularGlossMode) << "\",\n";
        f << "  \"specularResponseStatus\": \"" << escapeJson(model.specularResponseStatus) << "\",\n";
        f << "  \"glossResponseStatus\": \"" << escapeJson(model.glossResponseStatus) << "\",\n";
        f << "  \"roughnessRemapV2Status\": \"" << escapeJson(model.roughnessRemapV2Status) << "\",\n";
        f << "  \"metallicSpecularBoostStatus\": \"" << escapeJson(model.metallicSpecularBoostStatus) << "\",\n";
        f << "  \"dielectricGlossStatus\": \"" << escapeJson(model.dielectricGlossStatus) << "\",\n";
        f << "  \"fabricSpecularSuppressStatus\": \"" << escapeJson(model.fabricSpecularSuppressStatus) << "\",\n";
        f << "  \"specularOverbrightGuardStatus\": \"" << escapeJson(model.specularOverbrightGuardStatus) << "\",\n";
        f << "  \"viewDependentHighlightStatus\": \"" << escapeJson(model.viewDependentHighlightStatus) << "\",\n";
        f << "  \"paintGlossLiteStatus\": \"" << escapeJson(model.paintGlossLiteStatus) << "\",\n";
        f << "  \"paintGlossLiteMode\": \"" << escapeJson(model.paintGlossLiteMode) << "\",\n";
        f << "  \"paintGlossIntensity\": " << model.paintGlossIntensity << ",\n";
        f << "  \"paintGlossRoughness\": " << model.paintGlossRoughness << ",\n";
        f << "  \"paintGlossMaterialHintStatus\": \"" << escapeJson(model.paintGlossMaterialHintStatus) << "\",\n";
        f << "  \"paintGlossPerformanceStatus\": \"" << escapeJson(model.paintGlossPerformanceStatus) << "\",\n";
        f << "  \"paintGlossTargetStatus\": \"" << escapeJson(model.paintGlossTargetStatus) << "\",\n";
        f << "  \"paintGlossAppliedMaterialCount\": " << model.paintGlossAppliedMaterialCount << ",\n";
        f << "  \"paintGlossSkippedFabricCount\": " << model.paintGlossSkippedFabricCount << ",\n";
        f << "  \"paintGlossFallbackRouting\": \"" << escapeJson(model.paintGlossFallbackRouting) << "\",\n";
        f << "  \"paintGlossVisibleResponseStatus\": \"" << escapeJson(model.paintGlossVisibleResponseStatus) << "\",\n";
        f << "  \"glossSliderStatus\": \"" << escapeJson(model.glossSliderStatus) << "\",\n";
        f << "  \"glossSliderValue\": " << model.glossSliderValue << ",\n";
        f << "  \"paintGlossSliderStatus\": \"" << escapeJson(model.paintGlossSliderStatus) << "\",\n";
        f << "  \"paintGlossSliderValue\": " << model.paintGlossSliderValue << ",\n";
        f << "  \"glossUniformUpdateStatus\": \"" << escapeJson(model.glossUniformUpdateStatus) << "\",\n";
        f << "  \"glossResponseDebugViewStatus\": \"" << escapeJson(model.glossResponseDebugViewStatus) << "\",\n";
        f << "  \"specularGuardDebugViewStatus\": \"" << escapeJson(model.specularGuardDebugViewStatus) << "\",\n";
        f << "  \"paintGlossDebugViewStatus\": \"" << escapeJson(model.paintGlossDebugViewStatus) << "\",\n";
        f << "  \"metalResponseDebugViewStatus\": \"" << escapeJson(model.metalResponseDebugViewStatus) << "\",\n";
        f << "  \"paintTargetDebugViewStatus\": \"" << escapeJson(model.paintTargetDebugViewStatus) << "\",\n";
        f << "  \"calibrationResponseDebugViewStatus\": \"" << escapeJson(model.calibrationResponseDebugViewStatus) << "\",\n";
        f << "  \"materialTypeSpecularRoutingStatus\": \"" << escapeJson(model.materialTypeSpecularRoutingStatus) << "\",\n";
        f << "  \"paintMaterialGlossStatus\": \"" << escapeJson(model.paintMaterialGlossStatus) << "\",\n";
        f << "  \"metalMaterialGlossStatus\": \"" << escapeJson(model.metalMaterialGlossStatus) << "\",\n";
        f << "  \"rubberMaterialGlossStatus\": \"" << escapeJson(model.rubberMaterialGlossStatus) << "\",\n";
        f << "  \"specularGlossPerformanceStatus\": \"" << escapeJson(model.specularGlossPerformanceStatus) << "\",\n";
        f << "  \"glossVisibleResponseStatus\": \"" << escapeJson(model.glossVisibleResponseStatus) << "\",\n";
        f << "  \"glossAffectsSpecularLobe\": \"" << escapeJson(model.glossAffectsSpecularLobe) << "\",\n";
        f << "  \"glossAffectsReflectionWeight\": \"" << escapeJson(model.glossAffectsReflectionWeight) << "\",\n";
        f << "  \"materialSlotEditorStatus\": \"" << escapeJson(model.materialSlotEditorStatus) << "\",\n";
        f << "  \"selectedMaterialSlot\": " << model.selectedMaterialSlot << ",\n";
        f << "  \"selectedMaterialSlotCount\": " << model.selectedMaterialSlotCount << ",\n";
        f << "  \"selectedMaterialTypeHint\": \"" << escapeJson(model.selectedMaterialTypeHint) << "\",\n";
        f << "  \"selectedMaterialName\": \"" << escapeJson(model.selectedMaterialName) << "\",\n";
        f << "  \"selectedMaterialSummaryStatus\": \"" << escapeJson(model.selectedMaterialSummaryStatus) << "\",\n";
        f << "  \"materialSlotSelectionUiStatus\": \"" << escapeJson(model.materialSlotSelectionUiStatus) << "\",\n";
        f << "  \"perMaterialOverrideStatus\": \"" << escapeJson(model.perMaterialOverrideStatus) << "\",\n";
        f << "  \"perMaterialOverrideMode\": \"" << escapeJson(model.perMaterialOverrideMode) << "\",\n";
        f << "  \"selectedSlotMetallicOverride\": " << model.selectedSlotMetallicOverride << ",\n";
        f << "  \"selectedSlotRoughnessOverride\": " << model.selectedSlotRoughnessOverride << ",\n";
        f << "  \"selectedSlotNormalScaleOverride\": " << model.selectedSlotNormalScaleOverride << ",\n";
        f << "  \"selectedSlotAoOverride\": " << model.selectedSlotAoOverride << ",\n";
        f << "  \"selectedSlotGlossOverride\": " << model.selectedSlotGlossOverride << ",\n";
        f << "  \"selectedSlotCoatOverride\": " << model.selectedSlotCoatOverride << ",\n";
        f << "  \"selectedSlotOverrideApplied\": \"" << escapeJson(model.selectedSlotOverrideApplied) << "\",\n";
        f << "  \"selectedSlotResetStatus\": \"" << escapeJson(model.selectedSlotResetStatus) << "\",\n";
        f << "  \"perMaterialUniformUpdateStatus\": \"" << escapeJson(model.perMaterialUniformUpdateStatus) << "\",\n";
        f << "  \"materialSlotControlsUiStatus\": \"" << escapeJson(model.materialSlotControlsUiStatus) << "\",\n";
        f << "  \"metallicSlotSliderStatus\": \"" << escapeJson(model.metallicSlotSliderStatus) << "\",\n";
        f << "  \"roughnessSlotSliderStatus\": \"" << escapeJson(model.roughnessSlotSliderStatus) << "\",\n";
        f << "  \"normalSlotSliderStatus\": \"" << escapeJson(model.normalSlotSliderStatus) << "\",\n";
        f << "  \"aoSlotSliderStatus\": \"" << escapeJson(model.aoSlotSliderStatus) << "\",\n";
        f << "  \"selectedMaterialDebugViewStatus\": \"" << escapeJson(model.selectedMaterialDebugViewStatus) << "\",\n";
        f << "  \"materialOverrideDebugViewStatus\": \"" << escapeJson(model.materialOverrideDebugViewStatus) << "\",\n";
        f << "  \"slotMetallicDebugViewStatus\": \"" << escapeJson(model.slotMetallicDebugViewStatus) << "\",\n";
        f << "  \"slotRoughnessDebugViewStatus\": \"" << escapeJson(model.slotRoughnessDebugViewStatus) << "\",\n";
        f << "  \"slotAoDebugViewStatus\": \"" << escapeJson(model.slotAoDebugViewStatus) << "\",\n";
        f << "  \"perMaterialOverridePerformanceStatus\": \"" << escapeJson(model.perMaterialOverridePerformanceStatus) << "\",\n";
        f << "  \"alphaMaterialStatus\": \"" << escapeJson(model.alphaMaterialStatus) << "\",\n";
        f << "  \"alphaModeSupportStatus\": \"" << escapeJson(model.alphaModeSupportStatus) << "\",\n";
        f << "  \"alphaMaskStatus\": \"" << escapeJson(model.alphaMaskStatus) << "\",\n";
        f << "  \"alphaBlendStatus\": \"" << escapeJson(model.alphaBlendStatus) << "\",\n";
        f << "  \"alphaCutoffStatus\": \"" << escapeJson(model.alphaCutoffStatus) << "\",\n";
        f << "  \"alphaCutoffValue\": " << model.alphaCutoffValue << ",\n";
        f << "  \"alphaDiscardStatus\": \"" << escapeJson(model.alphaDiscardStatus) << "\",\n";
        f << "  \"alphaTextureChannelStatus\": \"" << escapeJson(model.alphaTextureChannelStatus) << "\",\n";
        f << "  \"alphaFallbackStatus\": \"" << escapeJson(model.alphaFallbackStatus) << "\",\n";
        f << "  \"doubleSidedMaterialStatus\": \"" << escapeJson(model.doubleSidedMaterialStatus) << "\",\n";
        f << "  \"doubleSidedMode\": \"" << escapeJson(model.doubleSidedMode) << "\",\n";
        f << "  \"doubleSidedNormalStatus\": \"" << escapeJson(model.doubleSidedNormalStatus) << "\",\n";
        f << "  \"doubleSidedRasterStatus\": \"" << escapeJson(model.doubleSidedRasterStatus) << "\",\n";
        f << "  \"doubleSidedFallbackStatus\": \"" << escapeJson(model.doubleSidedFallbackStatus) << "\",\n";
        f << "  \"thinMaterialPolishStatus\": \"" << escapeJson(model.thinMaterialPolishStatus) << "\",\n";
        f << "  \"cutoutMaterialHintStatus\": \"" << escapeJson(model.cutoutMaterialHintStatus) << "\",\n";
        f << "  \"fabricEdgeStatus\": \"" << escapeJson(model.fabricEdgeStatus) << "\",\n";
        f << "  \"glassMetadataStatus\": \"" << escapeJson(model.glassMetadataStatus) << "\",\n";
        f << "  \"decalMaterialHintStatus\": \"" << escapeJson(model.decalMaterialHintStatus) << "\",\n";
        f << "  \"transparencyDeferredStatus\": \"" << escapeJson(model.transparencyDeferredStatus) << "\",\n";
        f << "  \"alphaUiStatus\": \"" << escapeJson(model.alphaUiStatus) << "\",\n";
        f << "  \"alphaCutoffSliderStatus\": \"" << escapeJson(model.alphaCutoffSliderStatus) << "\",\n";
        f << "  \"alphaDebugViewStatus\": \"" << escapeJson(model.alphaDebugViewStatus) << "\",\n";
        f << "  \"doubleSidedDebugViewStatus\": \"" << escapeJson(model.doubleSidedDebugViewStatus) << "\",\n";
        f << "  \"alphaResetButtonStatus\": \"" << escapeJson(model.alphaResetButtonStatus) << "\",\n";
        f << "  \"alphaUniformUpdateStatus\": \"" << escapeJson(model.alphaUniformUpdateStatus) << "\",\n";
        f << "  \"alphaSliderUpdateMode\": \"" << escapeJson(model.alphaSliderUpdateMode) << "\",\n";
        f << "  \"alphaMaskDebugViewStatus\": \"" << escapeJson(model.alphaMaskDebugViewStatus) << "\",\n";
        f << "  \"alphaModeDebugViewStatus\": \"" << escapeJson(model.alphaModeDebugViewStatus) << "\",\n";
        f << "  \"cutoutHintDebugViewStatus\": \"" << escapeJson(model.cutoutHintDebugViewStatus) << "\",\n";
        f << "  \"transparencyStatusDebugViewStatus\": \"" << escapeJson(model.transparencyStatusDebugViewStatus) << "\",\n";
        f << "  \"alphaPerformanceStatus\": \"" << escapeJson(model.alphaPerformanceStatus) << "\",\n";
        f << "  \"alphaNoNewPassStatus\": \"" << escapeJson(model.alphaNoNewPassStatus) << "\",\n";
        f << "  \"alphaNoTextureRebuildStatus\": \"" << escapeJson(model.alphaNoTextureRebuildStatus) << "\",\n";
        f << "  \"alphaNoModelReuploadStatus\": \"" << escapeJson(model.alphaNoModelReuploadStatus) << "\",\n";
        f << "  \"p20RuntimeWorkflowPreservedStatus\": \"" << escapeJson(model.p20RuntimeWorkflowPreservedStatus) << "\",\n";
        f << "  \"p19SlotControlsPreservedStatus\": \"" << escapeJson(model.p19SlotControlsPreservedStatus) << "\",\n";
        f << "  \"p21AlphaPreservedStatus\": \"" << escapeJson(model.p21AlphaPreservedStatus) << "\",\n";
        f << "  \"p22EmissivePreservedStatus\": \"" << escapeJson(model.p22EmissivePreservedStatus) << "\",\n";
        f << "  \"p22PresetsPreservedStatus\": \"" << escapeJson(model.p22PresetsPreservedStatus) << "\",\n";
        f << "  \"clearcoatStatus\": \"" << escapeJson(model.clearcoatStatus) << "\",\n";
        f << "  \"clearcoatMode\": \"" << escapeJson(model.clearcoatMode) << "\",\n";
        f << "  \"clearcoatIntensity\": " << model.clearcoatIntensity << ",\n";
        f << "  \"clearcoatRoughness\": " << model.clearcoatRoughness << ",\n";
        f << "  \"clearcoatFresnelStatus\": \"" << escapeJson(model.clearcoatFresnelStatus) << "\",\n";
        f << "  \"clearcoatHighlightStatus\": \"" << escapeJson(model.clearcoatHighlightStatus) << "\",\n";
        f << "  \"clearcoatMaterialRoutingStatus\": \"" << escapeJson(model.clearcoatMaterialRoutingStatus) << "\",\n";
        f << "  \"clearcoatOverbrightGuardStatus\": \"" << escapeJson(model.clearcoatOverbrightGuardStatus) << "\",\n";
        f << "  \"clearcoatPerformanceStatus\": \"" << escapeJson(model.clearcoatPerformanceStatus) << "\",\n";
        f << "  \"carPaintLayerStatus\": \"" << escapeJson(model.carPaintLayerStatus) << "\",\n";
        f << "  \"carPaintPresetV2Status\": \"" << escapeJson(model.carPaintPresetV2Status) << "\",\n";
        f << "  \"carPaintClearcoatStatus\": \"" << escapeJson(model.carPaintClearcoatStatus) << "\",\n";
        f << "  \"paintLayerEnergyGuardStatus\": \"" << escapeJson(model.paintLayerEnergyGuardStatus) << "\",\n";
        f << "  \"paintLayerMaterialHintStatus\": \"" << escapeJson(model.paintLayerMaterialHintStatus) << "\",\n";
        f << "  \"clearcoatSliderStatus\": \"" << escapeJson(model.clearcoatSliderStatus) << "\",\n";
        f << "  \"clearcoatSliderValue\": " << model.clearcoatSliderValue << ",\n";
        f << "  \"clearcoatRoughnessSliderStatus\": \"" << escapeJson(model.clearcoatRoughnessSliderStatus) << "\",\n";
        f << "  \"clearcoatRoughnessSliderValue\": " << model.clearcoatRoughnessSliderValue << ",\n";
        f << "  \"clearcoatUniformUpdateStatus\": \"" << escapeJson(model.clearcoatUniformUpdateStatus) << "\",\n";
        f << "  \"clearcoatUiStatus\": \"" << escapeJson(model.clearcoatUiStatus) << "\",\n";
        f << "  \"clearcoatDebugViewStatus\": \"" << escapeJson(model.clearcoatDebugViewStatus) << "\",\n";
        f << "  \"clearcoatHighlightDebugViewStatus\": \"" << escapeJson(model.clearcoatHighlightDebugViewStatus) << "\",\n";
        f << "  \"paintLayerDebugViewStatus\": \"" << escapeJson(model.paintLayerDebugViewStatus) << "\",\n";
        f << "  \"paintEnergyGuardDebugViewStatus\": \"" << escapeJson(model.paintEnergyGuardDebugViewStatus) << "\",\n";
        f << "  \"p23PerformanceStatus\": \"" << escapeJson(model.p23PerformanceStatus) << "\",\n";
        f << "  \"clearcoatNoNewPassStatus\": \"" << escapeJson(model.clearcoatNoNewPassStatus) << "\",\n";
        f << "  \"clearcoatNoTextureRebuildStatus\": \"" << escapeJson(model.clearcoatNoTextureRebuildStatus) << "\",\n";
        f << "  \"clearcoatNoModelReuploadStatus\": \"" << escapeJson(model.clearcoatNoModelReuploadStatus) << "\",\n";
        f << "  \"clearcoatNoTransparentSortingStatus\": \"" << escapeJson(model.clearcoatNoTransparentSortingStatus) << "\",\n";
        f << "  \"fpsCurrent\": " << model.fpsCurrent << ",\n";
        f << "  \"frameTimeMs\": " << model.frameTimeMs << ",\n";
        f << "  \"fpsSource\": \"" << escapeJson(model.fpsSource) << "\",\n";
        f << "  \"fpsLastStable\": " << model.fpsLastStable << ",\n";
        f << "  \"frameTimeLastStableMs\": " << model.frameTimeLastStableMs << ",\n";
        f << "  \"fpsStatus\": \"" << escapeJson(model.fpsStatus) << "\",\n";
        f << "  \"fpsUpdateMode\": \"" << escapeJson(model.fpsUpdateMode) << "\",\n";
        f << "  \"fpsSampleWindowMs\": " << model.fpsSampleWindowMs << ",\n";
        f << "  \"framesRenderedLive\": " << model.framesRenderedLive << ",\n";
        f << "  \"modelUploadRepeatCount\": " << model.modelUploadRepeatCount << ",\n";
        f << "  \"uploadGenerationId\": " << model.uploadGenerationId << ",\n";
        f << "  \"renderLoopAllocationGuardStatus\": \"" << escapeJson(model.renderLoopAllocationGuardStatus) << "\",\n";
        f << "  \"debugZipStatus\": \"" << escapeJson(model.debugZipStatus) << "\",\n";
        f << "  \"debugZipPath\": \"" << escapeJson(model.debugZipPath) << "\",\n";
        f << "  \"debugZipIncludedFiles\": \"" << escapeJson(model.debugZipIncludedFiles) << "\",\n";
        f << "  \"debugZipReason\": \"" << escapeJson(model.debugZipReason) << "\",\n";
        f << "  \"fallbackCubeVisible\": " << (model.fallbackCubeVisible ? "true" : "false") << ",\n";
        f << "  \"fallbackCubeStatus\": \"" << escapeJson(model.fallbackCubeStatus) << "\",\n";
        f << "  \"deviceName\": \"" << escapeJson(gpuName) << "\",\n";
        f << "  \"deviceType\": \"" << escapeJson(gpuType) << "\",\n";
        f << "  \"apiVersion\": \"" << escapeJson(apiVersion) << "\",\n";
        f << "  \"swapchainFormat\": " << (int)swapchainFormat << ",\n";
        f << "  \"extent\": { \"width\": " << extent.width << ", \"height\": " << extent.height << " },\n";
        f << "  \"vertexBufferReady\": " << (vertexBufferReady ? "true" : "false") << ",\n";
        f << "  \"indexBufferReady\": " << (indexBufferReady ? "true" : "false") << ",\n";
        f << "  \"uniformOrPushConstantsReady\": " << (uniformOrPushConstantsReady ? "true" : "false") << ",\n";
        f << "  \"vertexCount\": " << vertexCount << ",\n";
        f << "  \"indexCount\": " << indexCount << ",\n";
        f << "  \"framesRendered\": " << framesRendered << ",\n";
        f << "  \"cubeStatus\": \"" << (cubeReady || !model.fallbackCubeVisible ? "ok" : "failed") << "\",\n";
        f << "  \"depthStatus\": \"" << (depthReady ? "ok" : "failed") << "\",\n";
        f << "  \"cameraStatus\": \"" << (cameraReady ? "ok" : "failed") << "\",\n";
        f << "  \"cameraMvpStatus\": \"" << (cameraMvpReady ? "ok" : "failed") << "\",\n";
        f << "  \"cameraControlsStatus\": \"" << (cameraControlsReady ? "ok" : "not_implemented") << "\",\n";
        f << "  \"cameraYawDeg\": " << camera.yawDeg << ",\n";
        f << "  \"cameraPitchDeg\": " << camera.pitchDeg << ",\n";
        f << "  \"cameraDistance\": " << camera.distance << ",\n";
        f << "  \"materialConstantsReady\": " << (materialConstantsReady ? "true" : "false") << ",\n";
        f << "  \"meshAttributeLayoutReady\": " << (meshAttributeLayoutReady ? "true" : "false") << ",\n";
        f << "  \"vertexLayout\": \"POSITION,NORMAL,TEXCOORD_0,COLOR_0,TANGENT\",\n";
        f << "  \"vertexStrideBytes\": " << vertexStrideBytes << ",\n";
        f << "  \"material\": {\n";
        f << "    \"materialId\": " << material.materialId << ",\n";
        f << "    \"baseColorFactor\": [" << material.baseColorFactor[0] << ", " << material.baseColorFactor[1] << ", " << material.baseColorFactor[2] << ", " << material.baseColorFactor[3] << "],\n";
        f << "    \"metallicFactor\": " << material.metallicFactor << ",\n";
        f << "    \"roughnessFactor\": " << material.roughnessFactor << ",\n";
        f << "    \"normalScale\": " << material.normalScale << ",\n";
        f << "    \"occlusionStrength\": " << material.occlusionStrength << ",\n";
        f << "    \"emissiveFactor\": [" << material.emissiveFactor[0] << ", " << material.emissiveFactor[1] << ", " << material.emissiveFactor[2] << "],\n";
        f << "    \"clearcoatIntensity\": " << material.clearcoatIntensity << ",\n";
        f << "    \"clearcoatRoughness\": " << material.clearcoatRoughness << ",\n";
        f << "    \"alphaMode\": \"OPAQUE\",\n";
        f << "    \"alphaCutoff\": " << material.alphaCutoff << "\n";
        f << "  },\n";
        f << "  \"screenshot\": { \"status\": \"not_available\", \"reason\": \"renderer_readback_not_implemented\" },\n";
        f << "  \"triangleDrawn\": " << (triangleDrawn ? "true" : "false") << ",\n";
        renderLab.writeJsonFields(f);
        f << "\n";
        f << "}\n";
    }
};

} // namespace solum
