#pragma once
#include "render_lab.hpp"
#include "renderer_types.hpp"

namespace solum {

struct RuntimeDiagnostics {
    std::string outputRoot;
    std::string status = "created";
    std::string reason;
    std::string gpuName = "unknown";
    std::string gpuType = "unknown";
    std::string apiVersion = "unknown";
    VkFormat swapchainFormat = VK_FORMAT_UNDEFINED;
    VkExtent2D extent{};
    bool rendererCoreReady = false;
    bool vertexBufferReady = false;
    bool indexBufferReady = false;
    bool cubeReady = false;
    bool depthReady = false;
    bool cameraReady = false;
    bool cameraMvpReady = false;
    bool cameraControlsReady = false;
    bool uniformOrPushConstantsReady = false;
    bool materialConstantsReady = false;
    bool meshAttributeLayoutReady = false;
    bool triangleDrawn = false;
    uint32_t vertexCount = 0;
    uint32_t indexCount = 0;
    uint32_t vertexStrideBytes = 0;
    CameraState camera;
    MaterialConstants material;
    uint64_t framesRendered = 0;
    RenderLabState renderLab;
    ModelRenderState model;

    void write(const std::string& newStatus, const std::string& newReason) {
        status = newStatus;
        reason = newReason;
        std::string dir = reportDirFor(outputRoot);
        ensureDir(dir + "/");
        std::ofstream f(dir + "/runtime_vulkan_caps.json");
        f << "{\n";
        f << "  \"schema\": \"solum.runtime_vulkan_caps\",\n";
        f << "  \"schemaVersion\": 2,\n";
        f << "  \"status\": \"" << escapeJson(status) << "\",\n";
        f << "  \"reason\": \"" << escapeJson(reason) << "\",\n";
        f << "  \"rendererPath\": \"Android Native Vulkan\",\n";
        f << "  \"currentScene\": \"" << renderLab.sceneId() << "\",\n";
        f << "  \"currentLabScene\": \"" << renderLab.sceneId() << "\",\n";
        f << "  \"currentLabSceneName\": \"" << renderLab.sceneName() << "\",\n";
        f << "  \"glassVisualQualityStatus\": \"" << escapeJson(model.glassVisualQualityStatus) << "\",\n";
        f << "  \"glassGreyPlateFixStatus\": \"" << escapeJson(model.glassGreyPlateFixStatus) << "\",\n";
        f << "  \"glassWeakMaterialFallbackStatus\": \"" << escapeJson(model.glassWeakMaterialFallbackStatus) << "\",\n";
        f << "  \"glassNoAssetHardcodeStatus\": \"" << escapeJson(model.glassNoAssetHardcodeStatus) << "\",\n";
        f << "  \"p28dGlassFoundationRepairStatus\": \"" << escapeJson(model.p28dGlassFoundationRepairStatus) << "\",\n";
        f << "  \"glassVisualTruthStatus\": \"" << escapeJson(model.glassVisualTruthStatus) << "\",\n";
        f << "  \"glassFinalShadedFormulaStatus\": \"" << escapeJson(model.glassFinalShadedFormulaStatus) << "\",\n";
        f << "  \"p28bGlassFixStatus\": \"" << escapeJson(model.p28bGlassFixStatus) << "\",\n";
        f << "  \"p28cTransparentRenderFixStatus\": \"" << escapeJson(model.p28cTransparentRenderFixStatus) << "\",\n";
        f << "  \"glassDiscardBypassStatus\": \"" << escapeJson(model.glassDiscardBypassStatus) << "\",\n";
        f << "  \"glassFinalShaderAlphaStatus\": \"" << escapeJson(model.glassFinalShaderAlphaStatus) << "\",\n";
        f << "  \"glassFinalShaderColorStatus\": \"" << escapeJson(model.glassFinalShaderColorStatus) << "\",\n";
        f << "  \"glassFinalUsesLiveUniformsStatus\": \"" << escapeJson(model.glassFinalUsesLiveUniformsStatus) << "\",\n";
        f << "  \"transparentPipelineActuallyUsedStatus\": \"" << escapeJson(model.transparentPipelineActuallyUsedStatus) << "\",\n";
        f << "  \"glassCutoutDisabledForTransparentStatus\": \"" << escapeJson(model.glassCutoutDisabledForTransparentStatus) << "\",\n";
        f << "  \"p21AlphaCutoutPreservedStatus\": \"" << escapeJson(model.p21AlphaCutoutPreservedStatus) << "\",\n";
        f << "  \"selectedSlotDisplay\": \"" << escapeJson(model.selectedSlotDisplay) << "\",\n";
        f << "  \"activeGlassSlotDisplay\": \"" << escapeJson(model.activeGlassSlotDisplay) << "\",\n";
        f << "  \"glassApplyTargetStatus\": \"" << escapeJson(model.glassApplyTargetStatus) << "\",\n";
        f << "  \"selectedVsActiveGlassSlotStatus\": \"" << escapeJson(model.selectedVsActiveGlassSlotStatus) << "\",\n";
        f << "  \"glassDiagnosticsHonestyStatus\": \"" << escapeJson(model.glassDiagnosticsHonestyStatus) << "\",\n";
        f << "  \"glassVisualVerificationStatus\": \"" << escapeJson(model.glassVisualVerificationStatus) << "\",\n";
        f << "  \"cameraHotPathDiagnosticsStatus\": \"" << escapeJson(model.cameraHotPathDiagnosticsStatus) << "\",\n";
        f << "  \"glassSlotsCount\": " << model.glassSlotsCount << ",\n";
        f << "  \"glassSlotsDisplay\": \"" << escapeJson(model.glassSlotsDisplay) << "\",\n";
        f << "  \"opaqueSlotsDisplay\": \"" << escapeJson(model.opaqueSlotsDisplay) << "\",\n";
        f << "  \"cutoutSlotsDisplay\": \"" << escapeJson(model.cutoutSlotsDisplay) << "\",\n";
        f << "  \"transparentGlassSlotLimit\": " << model.transparentGlassSlotLimit << ",\n";
        f << "  \"transparentGlassSlotsRendered\": " << model.transparentGlassSlotsRendered << ",\n";
        f << "  \"glassSingleSlotDrawRemoved\": \"" << escapeJson(model.glassSingleSlotDrawRemoved) << "\",\n";
        f << "  \"glassUsesSlotList\": \"" << escapeJson(model.glassUsesSlotList) << "\",\n";
        f << "  \"glassSlotListStatus\": \"" << escapeJson(model.glassSlotListStatus) << "\",\n";
        f << "  \"glassActiveSlotCount\": " << model.glassActiveSlotCount << ",\n";
        f << "  \"glassActiveSlotList\": \"" << escapeJson(model.glassActiveSlotList) << "\",\n";
        f << "  \"glassLiveOpacity\": " << model.glassLiveOpacity << ",\n";
        f << "  \"glassShaderOpacityInput\": " << model.glassShaderOpacityInput << ",\n";
        f << "  \"glassLiveClarity\": " << model.glassLiveClarity << ",\n";
        f << "  \"glassShaderClarityInput\": " << model.glassShaderClarityInput << ",\n";
        f << "  \"glassLiveThickness\": " << model.glassLiveThickness << ",\n";
        f << "  \"glassShaderThicknessInput\": " << model.glassShaderThicknessInput << ",\n";
        f << "  \"glassPresetMixRemovedStatus\": \"" << escapeJson(model.glassPresetMixRemovedStatus) << "\",\n";
        f << "  \"glassPresetMixInShader\": \"" << escapeJson(model.glassPresetMixInShader) << "\",\n";
        f << "  \"glassUsesNormalMaterialRgb\": \"" << escapeJson(model.glassUsesNormalMaterialRgb) << "\",\n";
        f << "  \"glassFinalVisualVerified\": \"" << escapeJson(model.glassFinalVisualVerified) << "\",\n";
        f << "  \"glassEnabledControlsShaderBranch\": \"" << escapeJson(model.glassEnabledControlsShaderBranch) << "\",\n";
        f << "  \"glassOpacityZeroExpectedCenterClear\": \"" << escapeJson(model.glassOpacityZeroExpectedCenterClear) << "\",\n";
        f << "  \"glassOpacitySixExpectedCenterDense\": \"" << escapeJson(model.glassOpacitySixExpectedCenterDense) << "\",\n";
        f << "  \"glassDebugTruthStatus\": \"" << escapeJson(model.glassDebugTruthStatus) << "\",\n";
        f << "  \"gitCommitContainsP28H\": \"" << escapeJson(model.gitCommitContainsP28H) << "\",\n";
        f << "  \"apkBuiltFromCommittedTree\": \"" << escapeJson(model.apkBuiltFromCommittedTree) << "\",\n";
        f << "  \"glassCpuGpuMismatchRisk\": \"" << escapeJson(model.glassCpuGpuMismatchRisk) << "\",\n";
        f << "  \"glassRuntimeTruthSource\": \"" << escapeJson(model.glassRuntimeTruthSource) << "\",\n";
        f << "  \"glassVisualFormulaVersion\": \"" << escapeJson(model.glassVisualFormulaVersion) << "\",\n";
        f << "  \"glassEffectiveCenterAlpha\": " << model.glassEffectiveCenterAlpha << ",\n";
        f << "  \"glassEffectiveEdgeAlpha\": " << model.glassEffectiveEdgeAlpha << ",\n";
        f << "  \"glassEffectiveLayerCompensation\": " << model.glassEffectiveLayerCompensation << ",\n";
        f << "  \"glassEffectiveTintStrength\": " << model.glassEffectiveTintStrength << ",\n";
        f << "  \"glassVisualVerified\": \"" << escapeJson(model.glassVisualVerified) << "\",\n";
        f << "  \"legacyGlassMaterialReportNotShaderTruth\": \"" << escapeJson(model.legacyGlassMaterialReportNotShaderTruth) << "\",\n";
        f << "  \"glassCandidateScoringStatus\": \"" << escapeJson(model.glassCandidateScoringStatus) << "\",\n";
        f << "  \"glassBestCandidateStatus\": \"" << escapeJson(model.glassBestCandidateStatus) << "\",\n";
        f << "  \"glassUniformAppliedToShaderStatus\": \"" << escapeJson(model.glassUniformAppliedToShaderStatus) << "\",\n";
        f << "  \"glassLiveSliderResponseStatus\": \"" << escapeJson(model.glassLiveSliderResponseStatus) << "\",\n";
        f << "  \"glassPresetLiveApplyStatus\": \"" << escapeJson(model.glassPresetLiveApplyStatus) << "\",\n";
        f << "  \"glassFinalCenterAlpha\": " << model.glassFinalCenterAlpha << ",\n";
        f << "  \"glassFinalEdgeAlpha\": " << model.glassFinalEdgeAlpha << ",\n";
        f << "  \"glassFinalTintColor\": \"" << escapeJson(model.glassFinalTintColor) << "\",\n";
        f << "  \"glassActuallyTransparentStatus\": \"" << escapeJson(model.glassActuallyTransparentStatus) << "\",\n";
        f << "  \"glassGreyPlateStillPossibleStatus\": \"" << escapeJson(model.glassGreyPlateStillPossibleStatus) << "\",\n";
        f << "  \"previousSystemsPreservedStatus\": \"" << escapeJson(model.previousSystemsPreservedStatus) << "\",\n";
        f << "  \"glassOpaqueAlphaModeOverrideStatus\": \"" << escapeJson(model.glassOpaqueAlphaModeOverrideStatus) << "\",\n";
        f << "  \"p28VisualGlassStatus\": \"" << escapeJson(model.p28VisualGlassStatus) << "\",\n";
        f << "  \"glassClarityStatus\": \"" << escapeJson(model.glassClarityStatus) << "\",\n";
        f << "  \"glassCenterTransparencyStatus\": \"" << escapeJson(model.glassCenterTransparencyStatus) << "\",\n";
        f << "  \"glassEdgeHighlightStatus\": \"" << escapeJson(model.glassEdgeReflectionStatus) << "\",\n";
        f << "  \"glassFakeThicknessStatus\": \"" << escapeJson(model.glassFakeThicknessStatus) << "\",\n";
        f << "  \"glassPresetVisualStatus\": \"" << escapeJson(model.glassPresetVisualStatus) << "\",\n";
        f << "  \"glassFallbackMaterialStatus\": \"" << escapeJson(model.glassFallbackMaterialStatus) << "\",\n";
        f << "  \"glassPresetCount\": " << model.glassPresetCount << ",\n";
        f << "  \"activeGlassPreset\": \"" << escapeJson(model.activeGlassPreset) << "\",\n";
        f << "  \"glassPresetClearStatus\": \"" << escapeJson(model.glassPresetClearStatus) << "\",\n";
        f << "  \"glassPresetSmokeStatus\": \"" << escapeJson(model.glassPresetSmokeStatus) << "\",\n";
        f << "  \"glassPresetGreenStatus\": \"" << escapeJson(model.glassPresetGreenStatus) << "\",\n";
        f << "  \"glassPresetCrystalStatus\": \"" << escapeJson(model.glassPresetCrystalStatus) << "\",\n";
        f << "  \"glassPresetWarmStatus\": \"" << escapeJson(model.glassPresetWarmStatus) << "\",\n";
        f << "  \"glassPresetDarkStatus\": \"" << escapeJson(model.glassPresetDarkStatus) << "\",\n";
        f << "  \"glassPresetNoTextureDependencyStatus\": \"" << escapeJson(model.glassPresetNoTextureDependencyStatus) << "\",\n";
        f << "  \"transparentGlassQualityStatus\": \"" << escapeJson(model.transparentGlassQualityStatus) << "\",\n";
        f << "  \"transparentGlassCenterAlphaStatus\": \"" << escapeJson(model.transparentGlassCenterAlphaStatus) << "\",\n";
        f << "  \"transparentGlassEdgeAlphaStatus\": \"" << escapeJson(model.transparentGlassEdgeAlphaStatus) << "\",\n";
        f << "  \"transparentGlassDepthBehaviorStatus\": \"" << escapeJson(model.transparentGlassDepthBehaviorStatus) << "\",\n";
        f << "  \"transparentGlassBackgroundVisibilityStatus\": \"" << escapeJson(model.transparentGlassBackgroundVisibilityStatus) << "\",\n";
        f << "  \"transparentGlassInteriorVisibilityStatus\": \"" << escapeJson(model.transparentGlassInteriorVisibilityStatus) << "\",\n";
        f << "  \"transparentGlassBlendPreservedStatus\": \"" << escapeJson(model.transparentGlassBlendPreservedStatus) << "\",\n";
        f << "  \"transparentGlassPassPreservedStatus\": \"" << escapeJson(model.transparentGlassPassPreservedStatus) << "\",\n";
        f << "  \"transparentGlassWrongSlotGuardStatus\": \"" << escapeJson(model.transparentGlassWrongSlotGuardStatus) << "\",\n";
        f << "  \"glassQualityUiStatus\": \"" << escapeJson(model.glassQualityUiStatus) << "\",\n";
        f << "  \"glassClaritySliderStatus\": \"" << escapeJson(model.glassClaritySliderStatus) << "\",\n";
        f << "  \"glassClarityValue\": " << model.glassClarityValue << ",\n";
        f << "  \"glassThicknessSliderStatus\": \"" << escapeJson(model.glassThicknessSliderStatus) << "\",\n";
        f << "  \"glassThicknessValue\": " << model.glassThicknessValue << ",\n";
        f << "  \"glassQualitySummaryUiStatus\": \"" << escapeJson(model.glassQualitySummaryUiStatus) << "\",\n";
        f << "  \"activeGlassSummaryPreservedStatus\": \"" << escapeJson(model.activeGlassSummaryPreservedStatus) << "\",\n";
        f << "  \"glassCenterAlphaDebugViewStatus\": \"" << escapeJson(model.glassCenterAlphaDebugViewStatus) << "\",\n";
        f << "  \"glassEdgeReflectionDebugViewStatus\": \"" << escapeJson(model.glassEdgeReflectionDebugViewStatus) << "\",\n";
        f << "  \"glassThicknessDebugViewStatus\": \"" << escapeJson(model.glassThicknessDebugViewStatus) << "\",\n";
        f << "  \"glassClarityDebugViewStatus\": \"" << escapeJson(model.glassClarityDebugViewStatus) << "\",\n";
        f << "  \"glassFallbackMaterialDebugViewStatus\": \"" << escapeJson(model.glassFallbackMaterialDebugViewStatus) << "\",\n";
        f << "  \"glassFinalCompositeDebugViewStatus\": \"" << escapeJson(model.glassFinalCompositeDebugViewStatus) << "\",\n";
        f << "  \"glassMissingBaseColorFallbackStatus\": \"" << escapeJson(model.glassMissingBaseColorFallbackStatus) << "\",\n";
        f << "  \"glassMissingRoughnessFallbackStatus\": \"" << escapeJson(model.glassMissingRoughnessFallbackStatus) << "\",\n";
        f << "  \"glassFallbackOpacityStatus\": \"" << escapeJson(model.glassFallbackOpacityStatus) << "\",\n";
        f << "  \"glassFallbackRoughnessStatus\": \"" << escapeJson(model.glassFallbackRoughnessStatus) << "\",\n";
        f << "  \"glassFallbackTintStatus\": \"" << escapeJson(model.glassFallbackTintStatus) << "\",\n";
        f << "  \"p27bRoutingPreservedStatus\": \"" << escapeJson(model.p27bRoutingPreservedStatus) << "\",\n";
        f << "  \"p27TransparentPassPreservedStatus\": \"" << escapeJson(model.p27TransparentPassPreservedStatus) << "\",\n";
        f << "  \"p26GlassPolishPreservedStatus\": \"" << escapeJson(model.p26GlassPolishPreservedStatus) << "\",\n";
        f << "  \"p25GlassPreservedStatus\": \"" << escapeJson(model.p25GlassPreservedStatus) << "\",\n";
        f << "  \"p24ReflectionPreservedStatus\": \"" << escapeJson(model.p24ReflectionPreservedStatus) << "\",\n";
        f << "  \"p23ClearcoatPreservedStatus\": \"" << escapeJson(model.p23ClearcoatPreservedStatus) << "\",\n";
        f << "  \"p22EmissivePreservedStatus\": \"" << escapeJson(model.p22EmissivePreservedStatus) << "\",\n";
        f << "  \"p22PresetsPreservedStatus\": \"" << escapeJson(model.p22PresetsPreservedStatus) << "\",\n";
        f << "  \"p21AlphaPreservedStatus\": \"" << escapeJson(model.p21AlphaPreservedStatus) << "\",\n";
        f << "  \"p20RuntimeWorkflowPreservedStatus\": \"" << escapeJson(model.p20RuntimeWorkflowPreservedStatus) << "\",\n";
        f << "  \"p19SlotControlsPreservedStatus\": \"" << escapeJson(model.p19SlotControlsPreservedStatus) << "\",\n";
        f << "  \"p18IblPreservedStatus\": \"" << escapeJson(model.p18IblPreservedStatus) << "\",\n";
        f << "  \"p28PerformanceStatus\": \"" << escapeJson(model.p28PerformanceStatus) << "\",\n";
        f << "  \"p28NoRaytraceStatus\": \"" << escapeJson(model.p28NoRaytraceStatus) << "\",\n";
        f << "  \"p28NoSsrStatus\": \"" << escapeJson(model.p28NoSsrStatus) << "\",\n";
        f << "  \"p28NoRealMirrorStatus\": \"" << escapeJson(model.p28NoRealMirrorStatus) << "\",\n";
        f << "  \"p28NoRealRefractionStatus\": \"" << escapeJson(model.p28NoRealRefractionStatus) << "\",\n";
        f << "  \"p28NoShadowStatus\": \"" << escapeJson(model.p28NoShadowStatus) << "\",\n";
        f << "  \"p28NoCsmStatus\": \"" << escapeJson(model.p28NoCsmStatus) << "\",\n";
        f << "  \"p28NoOffscreenCubemapStatus\": \"" << escapeJson(model.p28NoOffscreenCubemapStatus) << "\",\n";
        f << "  \"p28NoTextureRebuildStatus\": \"" << escapeJson(model.p28NoTextureRebuildStatus) << "\",\n";
        f << "  \"p28NoModelReuploadStatus\": \"" << escapeJson(model.p28NoModelReuploadStatus) << "\",\n";
        f << "  \"p28NoFrameGlbParseStatus\": \"" << escapeJson(model.p28NoFrameGlbParseStatus) << "\",\n";
        f << "  \"p28NoFrameFileWriteStatus\": \"" << escapeJson(model.p28NoFrameFileWriteStatus) << "\",\n";
        f << "  \"p28UniformOnlyStatus\": \"" << escapeJson(model.p28UniformOnlyStatus) << "\",\n";
        f << "  \"fpsStatus\": \"" << escapeJson(model.fpsStatus) << "\",\n";
        f << "  \"fpsUpdateMode\": \"" << escapeJson(model.fpsUpdateMode) << "\",\n";
        f << "  \"fpsCurrent\": " << model.fpsCurrent << ",\n";
        f << "  \"debugZipStatus\": \"" << escapeJson(model.debugZipStatus) << "\",\n";
        f << "  \"debugZipPath\": \"" << escapeJson(model.debugZipPath) << "\",\n";
        f << "  \"rendererCoreReady\": " << (rendererCoreReady ? "true" : "false") << ",\n";
        f << "  \"assetImportStatus\": \"" << (model.activeModelName == "none" ? "no active model" : "active model") << "\",\n";
        f << "  \"activeModelName\": \"" << escapeJson(model.activeModelName) << "\",\n";
        f << "  \"activeModelPath\": \"" << escapeJson(model.activeModelPath) << "\",\n";
        f << "  \"activePrimitiveIndex\": " << model.activePrimitiveIndex << ",\n";
        f << "  \"gpuUploadStatus\": \"" << escapeJson(model.gpuUploadStatus) << "\",\n";
        f << "  \"drawStatus\": \"" << escapeJson(model.drawStatus) << "\",\n";
        f << "  \"meshDrawStatus\": \"" << escapeJson(model.meshDrawStatus) << "\",\n";
        f << "  \"textureUploadStatus\": \"" << escapeJson(model.textureUploadStatus) << "\",\n";
        f << "  \"baseColorTextureStatus\": \"" << escapeJson(model.baseColorTextureStatus) << "\",\n";
        f << "  \"baseColorTextureName\": \"" << escapeJson(model.baseColorTextureName) << "\",\n";
        f << "  \"baseColorTextureSource\": \"" << escapeJson(model.baseColorTextureSource) << "\",\n";
        f << "  \"baseColorTextureMimeType\": \"" << escapeJson(model.baseColorTextureMimeType) << "\",\n";
        f << "  \"textureWidth\": " << model.textureWidth << ",\n";
        f << "  \"textureHeight\": " << model.textureHeight << ",\n";
        f << "  \"textureBytes\": " << model.textureBytes << ",\n";
        f << "  \"textureFallbackUsed\": " << (model.textureFallbackUsed ? "true" : "false") << ",\n";
        f << "  \"uploadedVertexCount\": " << model.uploadedVertexCount << ",\n";
        f << "  \"uploadedIndexCount\": " << model.uploadedIndexCount << ",\n";
        f << "  \"modelVertexLayout\": \"" << model.modelVertexLayout << "\",\n";
        f << "  \"modelBoundsMin\": [" << model.boundsMin[0] << ", " << model.boundsMin[1] << ", " << model.boundsMin[2] << "],\n";
        f << "  \"modelBoundsMax\": [" << model.boundsMax[0] << ", " << model.boundsMax[1] << ", " << model.boundsMax[2] << "],\n";
        f << "  \"modelBoundsCenter\": [" << model.boundsCenter[0] << ", " << model.boundsCenter[1] << ", " << model.boundsCenter[2] << "],\n";
        f << "  \"modelScale\": " << model.modelScale << ",\n";
        f << "  \"modelRenderMode\": \"" << model.modelRenderMode << "\",\n";
        f << "  \"primitiveCountTotal\": " << model.primitiveCountTotal << ",\n";
        f << "  \"primitiveCountRendered\": " << model.primitiveCountRendered << ",\n";
        f << "  \"primitiveCountSkipped\": " << model.primitiveCountSkipped << ",\n";
        f << "  \"unsupportedPrimitiveCount\": " << model.unsupportedPrimitiveCount << ",\n";
        f << "  \"materialSlotCount\": " << model.materialSlotCount << ",\n";
        f << "  \"materialSlotCountRendered\": " << model.materialSlotCountRendered << ",\n";
        f << "  \"textureSlotCount\": " << model.textureSlotCount << ",\n";
        f << "  \"uploadedTextureCount\": " << model.uploadedTextureCount << ",\n";
        f << "  \"textureFallbackCount\": " << model.textureFallbackCount << ",\n";
        f << "  \"skippedTextureCount\": " << model.skippedTextureCount << ",\n";
        f << "  \"textureSlotLimit\": " << model.textureSlotLimit << ",\n";
        f << "  \"pbrMapsStatus\": \"" << escapeJson(model.pbrMapsStatus) << "\",\n";
        f << "  \"metallicRoughnessStatus\": \"" << escapeJson(model.metallicRoughnessStatus) << "\",\n";
        f << "  \"normalMapStatus\": \"" << escapeJson(model.normalMapStatus) << "\",\n";
        f << "  \"normalMapAppliedStatus\": \"" << escapeJson(model.normalMapAppliedStatus) << "\",\n";
        f << "  \"occlusionMapStatus\": \"" << escapeJson(model.occlusionMapStatus) << "\",\n";
        f << "  \"tangentStatus\": \"" << escapeJson(model.tangentStatus) << "\",\n";
        f << "  \"tangentSource\": \"" << escapeJson(model.tangentSource) << "\",\n";
        f << "  \"tangentGeneratedCount\": " << model.tangentGeneratedCount << ",\n";
        f << "  \"tangentFallbackGeneratedCount\": " << model.tangentFallbackGeneratedCount << ",\n";
        f << "  \"tangentMissingCount\": " << model.tangentMissingCount << ",\n";
        f << "  \"tangentDegenerateTriangleCount\": " << model.tangentDegenerateTriangleCount << ",\n";
        f << "  \"tangentFallbackReason\": \"" << escapeJson(model.tangentFallbackReason) << "\",\n";
        f << "  \"tangentBuildMode\": \"" << escapeJson(model.tangentBuildMode) << "\",\n";
        f << "  \"metallicFactor\": " << model.metallicFactor << ",\n";
        f << "  \"roughnessFactor\": " << model.roughnessFactor << ",\n";
        f << "  \"normalScale\": " << model.normalScale << ",\n";
        f << "  \"occlusionStrength\": " << model.occlusionStrength << ",\n";
        f << "  \"pbrTextureSlotCount\": " << model.pbrTextureSlotCount << ",\n";
        f << "  \"uploadedPbrTextureCount\": " << model.uploadedPbrTextureCount << ",\n";
        f << "  \"skippedPbrTextureCount\": " << model.skippedPbrTextureCount << ",\n";
        f << "  \"pbrTextureFallbackCount\": " << model.pbrTextureFallbackCount << ",\n";
        f << "  \"materialSlotDiagnostics\": " << (model.materialSlotDiagnostics.empty() ? "[]" : model.materialSlotDiagnostics) << ",\n";
        f << "  \"lightingStatus\": \"" << escapeJson(model.lightingStatus) << "\",\n";
        f << "  \"lightingControlStatus\": \"" << escapeJson(model.lightingControlStatus) << "\",\n";
        f << "  \"lightingUiMode\": \"" << escapeJson(model.lightingUiMode) << "\",\n";
        f << "  \"sunDirection\": [" << model.sunDirection[0] << ", " << model.sunDirection[1] << ", " << model.sunDirection[2] << "],\n";
        f << "  \"sunColor\": [" << model.sunColor[0] << ", " << model.sunColor[1] << ", " << model.sunColor[2] << "],\n";
        f << "  \"sunIntensity\": " << model.sunIntensity << ",\n";
        f << "  \"ambientColor\": [" << model.ambientColor[0] << ", " << model.ambientColor[1] << ", " << model.ambientColor[2] << "],\n";
        f << "  \"ambientIntensity\": " << model.ambientIntensity << ",\n";
        f << "  \"lightPreset\": \"" << escapeJson(model.lightPreset) << "\",\n";
        f << "  \"specularBoost\": " << model.specularBoost << ",\n";
        f << "  \"specularBoostStatus\": \"" << escapeJson(model.specularBoostStatus) << "\",\n";
        f << "  \"reflectionIntensity\": " << model.reflectionIntensity << ",\n";
        f << "  \"iblStatus\": \"" << escapeJson(model.iblStatus) << "\",\n";
        f << "  \"iblMode\": \"" << escapeJson(model.iblMode) << "\",\n";
        f << "  \"environmentIblStatus\": \"" << escapeJson(model.environmentIblStatus) << "\",\n";
        f << "  \"environmentIblMode\": \"" << escapeJson(model.environmentIblMode) << "\",\n";
        f << "  \"environmentSourceStatus\": \"" << escapeJson(model.environmentSourceStatus) << "\",\n";
        f << "  \"environmentSourceType\": \"" << escapeJson(model.environmentSourceType) << "\",\n";
        f << "  \"environmentSkyColorStatus\": \"" << escapeJson(model.environmentSkyColorStatus) << "\",\n";
        f << "  \"environmentGroundColorStatus\": \"" << escapeJson(model.environmentGroundColorStatus) << "\",\n";
        f << "  \"environmentHorizonStatus\": \"" << escapeJson(model.environmentHorizonStatus) << "\",\n";
        f << "  \"environmentPerformanceStatus\": \"" << escapeJson(model.environmentPerformanceStatus) << "\",\n";
        f << "  \"iblDiffuseStatus\": \"" << escapeJson(model.iblDiffuseStatus) << "\",\n";
        f << "  \"iblSpecularStatus\": \"" << escapeJson(model.iblSpecularStatus) << "\",\n";
        f << "  \"iblRoughnessResponseStatus\": \"" << escapeJson(model.iblRoughnessResponseStatus) << "\",\n";
        f << "  \"iblMetallicResponseStatus\": \"" << escapeJson(model.iblMetallicResponseStatus) << "\",\n";
        f << "  \"iblDielectricResponseStatus\": \"" << escapeJson(model.iblDielectricResponseStatus) << "\",\n";
        f << "  \"iblFabricPreserveStatus\": \"" << escapeJson(model.iblFabricPreserveStatus) << "\",\n";
        f << "  \"iblOverbrightGuardStatus\": \"" << escapeJson(model.iblOverbrightGuardStatus) << "\",\n";
        f << "  \"environmentUiStatus\": \"" << escapeJson(model.environmentUiStatus) << "\",\n";
        f << "  \"environmentPreset\": \"" << escapeJson(model.environmentPreset) << "\",\n";
        f << "  \"environmentIntensity\": " << model.environmentIntensity << ",\n";
        f << "  \"environmentSliderStatus\": \"" << escapeJson(model.environmentSliderStatus) << "\",\n";
        f << "  \"skyPresetStatus\": \"" << escapeJson(model.skyPresetStatus) << "\",\n";
        f << "  \"horizonControlStatus\": \"" << escapeJson(model.horizonControlStatus) << "\",\n";
        f << "  \"environmentUniformUpdateStatus\": \"" << escapeJson(model.environmentUniformUpdateStatus) << "\",\n";
        f << "  \"environmentDebugViewStatus\": \"" << escapeJson(model.environmentDebugViewStatus) << "\",\n";
        f << "  \"reflectionDirectionDebugViewStatus\": \"" << escapeJson(model.reflectionDirectionDebugViewStatus) << "\",\n";
        f << "  \"environmentColorDebugViewStatus\": \"" << escapeJson(model.environmentColorDebugViewStatus) << "\",\n";
        f << "  \"iblPerformanceStatus\": \"" << escapeJson(model.iblPerformanceStatus) << "\",\n";
        f << "  \"reflectionFoundationStatus\": \"" << escapeJson(model.reflectionFoundationStatus) << "\",\n";
        f << "  \"reflectionMode\": \"" << escapeJson(model.reflectionMode) << "\",\n";
        f << "  \"environmentReflectionStatus\": \"" << escapeJson(model.environmentReflectionStatus) << "\",\n";
        f << "  \"environmentReflectionMode\": \"" << escapeJson(model.environmentReflectionMode) << "\",\n";
        f << "  \"environmentSource\": \"" << escapeJson(model.environmentSource) << "\",\n";
        f << "  \"reflectionColorStatus\": \"" << escapeJson(model.reflectionColorStatus) << "\",\n";
        f << "  \"reflectionRoughnessResponseStatus\": \"" << escapeJson(model.reflectionRoughnessResponseStatus) << "\",\n";
        f << "  \"metallicReflectionStatus\": \"" << escapeJson(model.metallicReflectionStatus) << "\",\n";
        f << "  \"dielectricReflectionStatus\": \"" << escapeJson(model.dielectricReflectionStatus) << "\",\n";
        f << "  \"reflectionPerformanceStatus\": \"" << escapeJson(model.reflectionPerformanceStatus) << "\",\n";
        f << "  \"inspectorUiStatus\": \"" << escapeJson(model.inspectorUiStatus) << "\",\n";
        f << "  \"inspectorUiMode\": \"" << escapeJson(model.inspectorUiMode) << "\",\n";
        f << "  \"activeInspectorTab\": \"" << escapeJson(model.activeInspectorTab) << "\",\n";
        f << "  \"assetsTabStatus\": \"" << escapeJson(model.assetsTabStatus) << "\",\n";
        f << "  \"cameraTabStatus\": \"" << escapeJson(model.cameraTabStatus) << "\",\n";
        f << "  \"lightingTabStatus\": \"" << escapeJson(model.lightingTabStatus) << "\",\n";
        f << "  \"materialTabStatus\": \"" << escapeJson(model.materialTabStatus) << "\",\n";
        f << "  \"debugTabStatus\": \"" << escapeJson(model.debugTabStatus) << "\",\n";
        f << "  \"contactGroundingStatus\": \"" << escapeJson(model.contactGroundingStatus) << "\",\n";
        f << "  \"contactShadowStatus\": \"" << escapeJson(model.contactShadowStatus) << "\",\n";
        f << "  \"contactShadowMode\": \"" << escapeJson(model.contactShadowMode) << "\",\n";
        f << "  \"contactShadowIntensity\": " << model.contactShadowIntensity << ",\n";
        f << "  \"contactShadowPerformanceStatus\": \"" << escapeJson(model.contactShadowPerformanceStatus) << "\",\n";
        f << "  \"groundingUsesModelBounds\": \"" << escapeJson(model.groundingUsesModelBounds) << "\",\n";
        f << "  \"groundingUniformUpdateStatus\": \"" << escapeJson(model.groundingUniformUpdateStatus) << "\",\n";
        f << "  \"groundSliderStatus\": \"" << escapeJson(model.groundSliderStatus) << "\",\n";
        f << "  \"contactGroundingSliderStatus\": \"" << escapeJson(model.contactGroundingSliderStatus) << "\",\n";
        f << "  \"lightingUniformUpdateStatus\": \"" << escapeJson(model.lightingUniformUpdateStatus) << "\",\n";
        f << "  \"sliderUpdateMode\": \"" << escapeJson(model.sliderUpdateMode) << "\",\n";
        f << "  \"sliderTouchStatus\": \"" << escapeJson(model.sliderTouchStatus) << "\",\n";
        f << "  \"sunSliderStatus\": \"" << escapeJson(model.sunSliderStatus) << "\",\n";
        f << "  \"ambientSliderStatus\": \"" << escapeJson(model.ambientSliderStatus) << "\",\n";
        f << "  \"exposureSliderStatus\": \"" << escapeJson(model.exposureSliderStatus) << "\",\n";
        f << "  \"specularSliderStatus\": \"" << escapeJson(model.specularSliderStatus) << "\",\n";
        f << "  \"reflectionSliderStatus\": \"" << escapeJson(model.reflectionSliderStatus) << "\",\n";
        f << "  \"materialResponseStatus\": \"" << escapeJson(model.materialResponseStatus) << "\",\n";
        f << "  \"toneMappingStatus\": \"" << escapeJson(model.toneMappingStatus) << "\",\n";
        f << "  \"toneMappingMode\": \"" << escapeJson(model.toneMappingMode) << "\",\n";
        f << "  \"exposureStatus\": \"" << escapeJson(model.exposureStatus) << "\",\n";
        f << "  \"exposureValue\": " << model.exposureValue << ",\n";
        f << "  \"ambientFloor\": " << model.ambientFloor << ",\n";
        f << "  \"brightnessPreset\": \"" << escapeJson(model.brightnessPreset) << "\",\n";
        f << "  \"activeDebugView\": \"" << escapeJson(model.activeDebugView) << "\",\n";
        f << "  \"debugViewStatus\": \"" << escapeJson(model.debugViewStatus) << "\",\n";
        f << "  \"normalDebugViewStatus\": \"" << escapeJson(model.normalDebugViewStatus) << "\",\n";
        f << "  \"ndotlDebugViewStatus\": \"" << escapeJson(model.ndotlDebugViewStatus) << "\",\n";
        f << "  \"diffuseDebugViewStatus\": \"" << escapeJson(model.diffuseDebugViewStatus) << "\",\n";
        f << "  \"specularDebugViewStatus\": \"" << escapeJson(model.specularDebugViewStatus) << "\",\n";
        f << "  \"f0DebugViewStatus\": \"" << escapeJson(model.f0DebugViewStatus) << "\",\n";
        f << "  \"reflectionDebugViewStatus\": \"" << escapeJson(model.reflectionDebugViewStatus) << "\",\n";
        f << "  \"iblDiffuseDebugViewStatus\": \"" << escapeJson(model.iblDiffuseDebugViewStatus) << "\",\n";
        f << "  \"iblSpecularDebugViewStatus\": \"" << escapeJson(model.iblSpecularDebugViewStatus) << "\",\n";
        f << "  \"brdfStatusDebugViewStatus\": \"" << escapeJson(model.brdfStatusDebugViewStatus) << "\",\n";
        f << "  \"groundingDebugViewStatus\": \"" << escapeJson(model.groundingDebugViewStatus) << "\",\n";
        f << "  \"materialCalibrationStatus\": \"" << escapeJson(model.materialCalibrationStatus) << "\",\n";
        f << "  \"materialCalibrationMode\": \"" << escapeJson(model.materialCalibrationMode) << "\",\n";
        f << "  \"albedoEnergyStatus\": \"" << escapeJson(model.albedoEnergyStatus) << "\",\n";
        f << "  \"albedoClampStatus\": \"" << escapeJson(model.albedoClampStatus) << "\",\n";
        f << "  \"diffuseClampStatus\": \"" << escapeJson(model.diffuseClampStatus) << "\",\n";
        f << "  \"luminanceGuardStatus\": \"" << escapeJson(model.luminanceGuardStatus) << "\",\n";
        f << "  \"aoCalibrationStatus\": \"" << escapeJson(model.aoCalibrationStatus) << "\",\n";
        f << "  \"roughnessRemapStatus\": \"" << escapeJson(model.roughnessRemapStatus) << "\",\n";
        f << "  \"metallicRoughnessClampStatus\": \"" << escapeJson(model.metallicRoughnessClampStatus) << "\",\n";
        f << "  \"emissiveGuardStatus\": \"" << escapeJson(model.emissiveGuardStatus) << "\",\n";
        f << "  \"fabricMattePreserveStatus\": \"" << escapeJson(model.fabricMattePreserveStatus) << "\",\n";
        f << "  \"paintMaterialCalibrationStatus\": \"" << escapeJson(model.paintMaterialCalibrationStatus) << "\",\n";
        f << "  \"metalMaterialCalibrationStatus\": \"" << escapeJson(model.metalMaterialCalibrationStatus) << "\",\n";
        f << "  \"materialTypeHintStatus\": \"" << escapeJson(model.materialTypeHintStatus) << "\",\n";
        f << "  \"materialSlotCalibrationStatus\": \"" << escapeJson(model.materialSlotCalibrationStatus) << "\",\n";
        f << "  \"calibrationUiStatus\": \"" << escapeJson(model.calibrationUiStatus) << "\",\n";
        f << "  \"calibrationPreset\": \"" << escapeJson(model.calibrationPreset) << "\",\n";
        f << "  \"calibrationSliderStatus\": \"" << escapeJson(model.calibrationSliderStatus) << "\",\n";
        f << "  \"calibrationSliderValue\": " << model.calibrationSliderValue << ",\n";
        f << "  \"calibrationUniformUpdateStatus\": \"" << escapeJson(model.calibrationUniformUpdateStatus) << "\",\n";
        f << "  \"calibratedAlbedoDebugViewStatus\": \"" << escapeJson(model.calibratedAlbedoDebugViewStatus) << "\",\n";
        f << "  \"materialTypeDebugViewStatus\": \"" << escapeJson(model.materialTypeDebugViewStatus) << "\",\n";
        f << "  \"aoInfluenceDebugViewStatus\": \"" << escapeJson(model.aoInfluenceDebugViewStatus) << "\",\n";
        f << "  \"luminanceGuardDebugViewStatus\": \"" << escapeJson(model.luminanceGuardDebugViewStatus) << "\",\n";
        f << "  \"calibrationVisualStrength\": " << model.calibrationVisualStrength << ",\n";
        f << "  \"calibrationAffectsAlbedo\": \"" << escapeJson(model.calibrationAffectsAlbedo) << "\",\n";
        f << "  \"calibrationAffectsAo\": \"" << escapeJson(model.calibrationAffectsAo) << "\",\n";
        f << "  \"calibrationAffectsRoughness\": \"" << escapeJson(model.calibrationAffectsRoughness) << "\",\n";
        f << "  \"calibrationVisibleResponseStatus\": \"" << escapeJson(model.calibrationVisibleResponseStatus) << "\",\n";
        f << "  \"materialCalibrationPerformanceStatus\": \"" << escapeJson(model.materialCalibrationPerformanceStatus) << "\",\n";
        f << "  \"specularGlossStatus\": \"" << escapeJson(model.specularGlossStatus) << "\",\n";
        f << "  \"specularGlossMode\": \"" << escapeJson(model.specularGlossMode) << "\",\n";
        f << "  \"specularResponseStatus\": \"" << escapeJson(model.specularResponseStatus) << "\",\n";
        f << "  \"glossResponseStatus\": \"" << escapeJson(model.glossResponseStatus) << "\",\n";
        f << "  \"roughnessRemapV2Status\": \"" << escapeJson(model.roughnessRemapV2Status) << "\",\n";
        f << "  \"metallicSpecularBoostStatus\": \"" << escapeJson(model.metallicSpecularBoostStatus) << "\",\n";
        f << "  \"dielectricGlossStatus\": \"" << escapeJson(model.dielectricGlossStatus) << "\",\n";
        f << "  \"fabricSpecularSuppressStatus\": \"" << escapeJson(model.fabricSpecularSuppressStatus) << "\",\n";
        f << "  \"specularOverbrightGuardStatus\": \"" << escapeJson(model.specularOverbrightGuardStatus) << "\",\n";
        f << "  \"viewDependentHighlightStatus\": \"" << escapeJson(model.viewDependentHighlightStatus) << "\",\n";
        f << "  \"paintGlossLiteStatus\": \"" << escapeJson(model.paintGlossLiteStatus) << "\",\n";
        f << "  \"paintGlossLiteMode\": \"" << escapeJson(model.paintGlossLiteMode) << "\",\n";
        f << "  \"paintGlossIntensity\": " << model.paintGlossIntensity << ",\n";
        f << "  \"paintGlossRoughness\": " << model.paintGlossRoughness << ",\n";
        f << "  \"paintGlossMaterialHintStatus\": \"" << escapeJson(model.paintGlossMaterialHintStatus) << "\",\n";
        f << "  \"paintGlossPerformanceStatus\": \"" << escapeJson(model.paintGlossPerformanceStatus) << "\",\n";
        f << "  \"paintGlossTargetStatus\": \"" << escapeJson(model.paintGlossTargetStatus) << "\",\n";
        f << "  \"paintGlossAppliedMaterialCount\": " << model.paintGlossAppliedMaterialCount << ",\n";
        f << "  \"paintGlossSkippedFabricCount\": " << model.paintGlossSkippedFabricCount << ",\n";
        f << "  \"paintGlossFallbackRouting\": \"" << escapeJson(model.paintGlossFallbackRouting) << "\",\n";
        f << "  \"paintGlossVisibleResponseStatus\": \"" << escapeJson(model.paintGlossVisibleResponseStatus) << "\",\n";
        f << "  \"glossSliderStatus\": \"" << escapeJson(model.glossSliderStatus) << "\",\n";
        f << "  \"glossSliderValue\": " << model.glossSliderValue << ",\n";
        f << "  \"paintGlossSliderStatus\": \"" << escapeJson(model.paintGlossSliderStatus) << "\",\n";
        f << "  \"paintGlossSliderValue\": " << model.paintGlossSliderValue << ",\n";
        f << "  \"glossUniformUpdateStatus\": \"" << escapeJson(model.glossUniformUpdateStatus) << "\",\n";
        f << "  \"glossResponseDebugViewStatus\": \"" << escapeJson(model.glossResponseDebugViewStatus) << "\",\n";
        f << "  \"specularGuardDebugViewStatus\": \"" << escapeJson(model.specularGuardDebugViewStatus) << "\",\n";
        f << "  \"paintGlossDebugViewStatus\": \"" << escapeJson(model.paintGlossDebugViewStatus) << "\",\n";
        f << "  \"metalResponseDebugViewStatus\": \"" << escapeJson(model.metalResponseDebugViewStatus) << "\",\n";
        f << "  \"paintTargetDebugViewStatus\": \"" << escapeJson(model.paintTargetDebugViewStatus) << "\",\n";
        f << "  \"calibrationResponseDebugViewStatus\": \"" << escapeJson(model.calibrationResponseDebugViewStatus) << "\",\n";
        f << "  \"materialTypeSpecularRoutingStatus\": \"" << escapeJson(model.materialTypeSpecularRoutingStatus) << "\",\n";
        f << "  \"paintMaterialGlossStatus\": \"" << escapeJson(model.paintMaterialGlossStatus) << "\",\n";
        f << "  \"metalMaterialGlossStatus\": \"" << escapeJson(model.metalMaterialGlossStatus) << "\",\n";
        f << "  \"rubberMaterialGlossStatus\": \"" << escapeJson(model.rubberMaterialGlossStatus) << "\",\n";
        f << "  \"specularGlossPerformanceStatus\": \"" << escapeJson(model.specularGlossPerformanceStatus) << "\",\n";
        f << "  \"glossVisibleResponseStatus\": \"" << escapeJson(model.glossVisibleResponseStatus) << "\",\n";
        f << "  \"glossAffectsSpecularLobe\": \"" << escapeJson(model.glossAffectsSpecularLobe) << "\",\n";
        f << "  \"glossAffectsReflectionWeight\": \"" << escapeJson(model.glossAffectsReflectionWeight) << "\",\n";
        f << "  \"materialSlotEditorStatus\": \"" << escapeJson(model.materialSlotEditorStatus) << "\",\n";
        f << "  \"selectedMaterialSlot\": " << model.selectedMaterialSlot << ",\n";
        f << "  \"selectedMaterialSlotCount\": " << model.selectedMaterialSlotCount << ",\n";
        f << "  \"selectedMaterialTypeHint\": \"" << escapeJson(model.selectedMaterialTypeHint) << "\",\n";
        f << "  \"selectedMaterialName\": \"" << escapeJson(model.selectedMaterialName) << "\",\n";
        f << "  \"selectedMaterialSummaryStatus\": \"" << escapeJson(model.selectedMaterialSummaryStatus) << "\",\n";
        f << "  \"materialSlotSelectionUiStatus\": \"" << escapeJson(model.materialSlotSelectionUiStatus) << "\",\n";
        f << "  \"perMaterialOverrideStatus\": \"" << escapeJson(model.perMaterialOverrideStatus) << "\",\n";
        f << "  \"perMaterialOverrideMode\": \"" << escapeJson(model.perMaterialOverrideMode) << "\",\n";
        f << "  \"selectedSlotMetallicOverride\": " << model.selectedSlotMetallicOverride << ",\n";
        f << "  \"selectedSlotRoughnessOverride\": " << model.selectedSlotRoughnessOverride << ",\n";
        f << "  \"selectedSlotNormalScaleOverride\": " << model.selectedSlotNormalScaleOverride << ",\n";
        f << "  \"selectedSlotAoOverride\": " << model.selectedSlotAoOverride << ",\n";
        f << "  \"selectedSlotGlossOverride\": " << model.selectedSlotGlossOverride << ",\n";
        f << "  \"selectedSlotCoatOverride\": " << model.selectedSlotCoatOverride << ",\n";
        f << "  \"selectedSlotOverrideApplied\": \"" << escapeJson(model.selectedSlotOverrideApplied) << "\",\n";
        f << "  \"selectedSlotResetStatus\": \"" << escapeJson(model.selectedSlotResetStatus) << "\",\n";
        f << "  \"perMaterialUniformUpdateStatus\": \"" << escapeJson(model.perMaterialUniformUpdateStatus) << "\",\n";
        f << "  \"materialSlotControlsUiStatus\": \"" << escapeJson(model.materialSlotControlsUiStatus) << "\",\n";
        f << "  \"metallicSlotSliderStatus\": \"" << escapeJson(model.metallicSlotSliderStatus) << "\",\n";
        f << "  \"roughnessSlotSliderStatus\": \"" << escapeJson(model.roughnessSlotSliderStatus) << "\",\n";
        f << "  \"normalSlotSliderStatus\": \"" << escapeJson(model.normalSlotSliderStatus) << "\",\n";
        f << "  \"aoSlotSliderStatus\": \"" << escapeJson(model.aoSlotSliderStatus) << "\",\n";
        f << "  \"selectedMaterialDebugViewStatus\": \"" << escapeJson(model.selectedMaterialDebugViewStatus) << "\",\n";
        f << "  \"materialOverrideDebugViewStatus\": \"" << escapeJson(model.materialOverrideDebugViewStatus) << "\",\n";
        f << "  \"slotMetallicDebugViewStatus\": \"" << escapeJson(model.slotMetallicDebugViewStatus) << "\",\n";
        f << "  \"slotRoughnessDebugViewStatus\": \"" << escapeJson(model.slotRoughnessDebugViewStatus) << "\",\n";
        f << "  \"slotAoDebugViewStatus\": \"" << escapeJson(model.slotAoDebugViewStatus) << "\",\n";
        f << "  \"perMaterialOverridePerformanceStatus\": \"" << escapeJson(model.perMaterialOverridePerformanceStatus) << "\",\n";
        f << "  \"alphaMaterialStatus\": \"" << escapeJson(model.alphaMaterialStatus) << "\",\n";
        f << "  \"alphaModeSupportStatus\": \"" << escapeJson(model.alphaModeSupportStatus) << "\",\n";
        f << "  \"alphaMaskStatus\": \"" << escapeJson(model.alphaMaskStatus) << "\",\n";
        f << "  \"alphaBlendStatus\": \"" << escapeJson(model.alphaBlendStatus) << "\",\n";
        f << "  \"alphaCutoffStatus\": \"" << escapeJson(model.alphaCutoffStatus) << "\",\n";
        f << "  \"alphaCutoffValue\": " << model.alphaCutoffValue << ",\n";
        f << "  \"alphaDiscardStatus\": \"" << escapeJson(model.alphaDiscardStatus) << "\",\n";
        f << "  \"alphaTextureChannelStatus\": \"" << escapeJson(model.alphaTextureChannelStatus) << "\",\n";
        f << "  \"alphaFallbackStatus\": \"" << escapeJson(model.alphaFallbackStatus) << "\",\n";
        f << "  \"doubleSidedMaterialStatus\": \"" << escapeJson(model.doubleSidedMaterialStatus) << "\",\n";
        f << "  \"doubleSidedMode\": \"" << escapeJson(model.doubleSidedMode) << "\",\n";
        f << "  \"doubleSidedNormalStatus\": \"" << escapeJson(model.doubleSidedNormalStatus) << "\",\n";
        f << "  \"doubleSidedRasterStatus\": \"" << escapeJson(model.doubleSidedRasterStatus) << "\",\n";
        f << "  \"doubleSidedFallbackStatus\": \"" << escapeJson(model.doubleSidedFallbackStatus) << "\",\n";
        f << "  \"thinMaterialPolishStatus\": \"" << escapeJson(model.thinMaterialPolishStatus) << "\",\n";
        f << "  \"cutoutMaterialHintStatus\": \"" << escapeJson(model.cutoutMaterialHintStatus) << "\",\n";
        f << "  \"fabricEdgeStatus\": \"" << escapeJson(model.fabricEdgeStatus) << "\",\n";
        f << "  \"glassMetadataStatus\": \"" << escapeJson(model.glassMetadataStatus) << "\",\n";
        f << "  \"decalMaterialHintStatus\": \"" << escapeJson(model.decalMaterialHintStatus) << "\",\n";
        f << "  \"transparencyDeferredStatus\": \"" << escapeJson(model.transparencyDeferredStatus) << "\",\n";
        f << "  \"alphaUiStatus\": \"" << escapeJson(model.alphaUiStatus) << "\",\n";
        f << "  \"alphaCutoffSliderStatus\": \"" << escapeJson(model.alphaCutoffSliderStatus) << "\",\n";
        f << "  \"alphaDebugViewStatus\": \"" << escapeJson(model.alphaDebugViewStatus) << "\",\n";
        f << "  \"doubleSidedDebugViewStatus\": \"" << escapeJson(model.doubleSidedDebugViewStatus) << "\",\n";
        f << "  \"alphaResetButtonStatus\": \"" << escapeJson(model.alphaResetButtonStatus) << "\",\n";
        f << "  \"alphaUniformUpdateStatus\": \"" << escapeJson(model.alphaUniformUpdateStatus) << "\",\n";
        f << "  \"alphaSliderUpdateMode\": \"" << escapeJson(model.alphaSliderUpdateMode) << "\",\n";
        f << "  \"alphaMaskDebugViewStatus\": \"" << escapeJson(model.alphaMaskDebugViewStatus) << "\",\n";
        f << "  \"alphaModeDebugViewStatus\": \"" << escapeJson(model.alphaModeDebugViewStatus) << "\",\n";
        f << "  \"cutoutHintDebugViewStatus\": \"" << escapeJson(model.cutoutHintDebugViewStatus) << "\",\n";
        f << "  \"transparencyStatusDebugViewStatus\": \"" << escapeJson(model.transparencyStatusDebugViewStatus) << "\",\n";
        f << "  \"alphaPerformanceStatus\": \"" << escapeJson(model.alphaPerformanceStatus) << "\",\n";
        f << "  \"alphaNoNewPassStatus\": \"" << escapeJson(model.alphaNoNewPassStatus) << "\",\n";
        f << "  \"alphaNoTextureRebuildStatus\": \"" << escapeJson(model.alphaNoTextureRebuildStatus) << "\",\n";
        f << "  \"alphaNoModelReuploadStatus\": \"" << escapeJson(model.alphaNoModelReuploadStatus) << "\",\n";
        f << "  \"p20RuntimeWorkflowPreservedStatus\": \"" << escapeJson(model.p20RuntimeWorkflowPreservedStatus) << "\",\n";
        f << "  \"p19SlotControlsPreservedStatus\": \"" << escapeJson(model.p19SlotControlsPreservedStatus) << "\",\n";
        f << "  \"p21AlphaPreservedStatus\": \"" << escapeJson(model.p21AlphaPreservedStatus) << "\",\n";
        f << "  \"p22EmissivePreservedStatus\": \"" << escapeJson(model.p22EmissivePreservedStatus) << "\",\n";
        f << "  \"p22PresetsPreservedStatus\": \"" << escapeJson(model.p22PresetsPreservedStatus) << "\",\n";
        f << "  \"clearcoatStatus\": \"" << escapeJson(model.clearcoatStatus) << "\",\n";
        f << "  \"clearcoatMode\": \"" << escapeJson(model.clearcoatMode) << "\",\n";
        f << "  \"clearcoatIntensity\": " << model.clearcoatIntensity << ",\n";
        f << "  \"clearcoatRoughness\": " << model.clearcoatRoughness << ",\n";
        f << "  \"clearcoatFresnelStatus\": \"" << escapeJson(model.clearcoatFresnelStatus) << "\",\n";
        f << "  \"clearcoatHighlightStatus\": \"" << escapeJson(model.clearcoatHighlightStatus) << "\",\n";
        f << "  \"clearcoatMaterialRoutingStatus\": \"" << escapeJson(model.clearcoatMaterialRoutingStatus) << "\",\n";
        f << "  \"clearcoatOverbrightGuardStatus\": \"" << escapeJson(model.clearcoatOverbrightGuardStatus) << "\",\n";
        f << "  \"clearcoatPerformanceStatus\": \"" << escapeJson(model.clearcoatPerformanceStatus) << "\",\n";
        f << "  \"carPaintLayerStatus\": \"" << escapeJson(model.carPaintLayerStatus) << "\",\n";
        f << "  \"carPaintPresetV2Status\": \"" << escapeJson(model.carPaintPresetV2Status) << "\",\n";
        f << "  \"carPaintClearcoatStatus\": \"" << escapeJson(model.carPaintClearcoatStatus) << "\",\n";
        f << "  \"paintLayerEnergyGuardStatus\": \"" << escapeJson(model.paintLayerEnergyGuardStatus) << "\",\n";
        f << "  \"paintLayerMaterialHintStatus\": \"" << escapeJson(model.paintLayerMaterialHintStatus) << "\",\n";
        f << "  \"clearcoatSliderStatus\": \"" << escapeJson(model.clearcoatSliderStatus) << "\",\n";
        f << "  \"clearcoatSliderValue\": " << model.clearcoatSliderValue << ",\n";
        f << "  \"clearcoatRoughnessSliderStatus\": \"" << escapeJson(model.clearcoatRoughnessSliderStatus) << "\",\n";
        f << "  \"clearcoatRoughnessSliderValue\": " << model.clearcoatRoughnessSliderValue << ",\n";
        f << "  \"clearcoatUniformUpdateStatus\": \"" << escapeJson(model.clearcoatUniformUpdateStatus) << "\",\n";
        f << "  \"clearcoatUiStatus\": \"" << escapeJson(model.clearcoatUiStatus) << "\",\n";
        f << "  \"clearcoatDebugViewStatus\": \"" << escapeJson(model.clearcoatDebugViewStatus) << "\",\n";
        f << "  \"clearcoatHighlightDebugViewStatus\": \"" << escapeJson(model.clearcoatHighlightDebugViewStatus) << "\",\n";
        f << "  \"paintLayerDebugViewStatus\": \"" << escapeJson(model.paintLayerDebugViewStatus) << "\",\n";
        f << "  \"paintEnergyGuardDebugViewStatus\": \"" << escapeJson(model.paintEnergyGuardDebugViewStatus) << "\",\n";
        f << "  \"p23PerformanceStatus\": \"" << escapeJson(model.p23PerformanceStatus) << "\",\n";
        f << "  \"clearcoatNoNewPassStatus\": \"" << escapeJson(model.clearcoatNoNewPassStatus) << "\",\n";
        f << "  \"clearcoatNoTextureRebuildStatus\": \"" << escapeJson(model.clearcoatNoTextureRebuildStatus) << "\",\n";
        f << "  \"clearcoatNoModelReuploadStatus\": \"" << escapeJson(model.clearcoatNoModelReuploadStatus) << "\",\n";
        f << "  \"clearcoatNoTransparentSortingStatus\": \"" << escapeJson(model.clearcoatNoTransparentSortingStatus) << "\",\n";
        f << "  \"fakeCubemapStatus\": \"" << escapeJson(model.fakeCubemapStatus) << "\",\n";
        f << "  \"fakeCubemapMode\": \"" << escapeJson(model.fakeCubemapMode) << "\",\n";
        f << "  \"fakeCubemapSourceStatus\": \"" << escapeJson(model.fakeCubemapSourceStatus) << "\",\n";
        f << "  \"environmentZoneStatus\": \"" << escapeJson(model.environmentZoneStatus) << "\",\n";
        f << "  \"skyZoneStatus\": \"" << escapeJson(model.skyZoneStatus) << "\",\n";
        f << "  \"horizonZoneStatus\": \"" << escapeJson(model.horizonZoneStatus) << "\",\n";
        f << "  \"groundZoneStatus\": \"" << escapeJson(model.groundZoneStatus) << "\",\n";
        f << "  \"sideReflectionZoneStatus\": \"" << escapeJson(model.sideReflectionZoneStatus) << "\",\n";
        f << "  \"fakeCubemapPerformanceStatus\": \"" << escapeJson(model.fakeCubemapPerformanceStatus) << "\",\n";
        f << "  \"reflectionQualityStatus\": \"" << escapeJson(model.reflectionQualityStatus) << "\",\n";
        f << "  \"reflectionContrastStatus\": \"" << escapeJson(model.reflectionContrastStatus) << "\",\n";
        f << "  \"reflectionContrastValue\": " << model.reflectionContrastValue << ",\n";
        f << "  \"reflectionSaturationStatus\": \"" << escapeJson(model.reflectionSaturationStatus) << "\",\n";
        f << "  \"reflectionSaturationValue\": " << model.reflectionSaturationValue << ",\n";
        f << "  \"roughnessReflectionBlurStatus\": \"" << escapeJson(model.roughnessReflectionBlurStatus) << "\",\n";
        f << "  \"clearcoatReflectionBoostStatus\": \"" << escapeJson(model.clearcoatReflectionBoostStatus) << "\",\n";
        f << "  \"metalReflectionTintStatus\": \"" << escapeJson(model.metalReflectionTintStatus) << "\",\n";
        f << "  \"fabricReflectionSuppressStatus\": \"" << escapeJson(model.fabricReflectionSuppressStatus) << "\",\n";
        f << "  \"reflectionEnergyGuardStatus\": \"" << escapeJson(model.reflectionEnergyGuardStatus) << "\",\n";
        f << "  \"reflectionOverbrightGuardStatus\": \"" << escapeJson(model.reflectionOverbrightGuardStatus) << "\",\n";
        f << "  \"reflectionQualityUiStatus\": \"" << escapeJson(model.reflectionQualityUiStatus) << "\",\n";
        f << "  \"reflectionContrastSliderStatus\": \"" << escapeJson(model.reflectionContrastSliderStatus) << "\",\n";
        f << "  \"reflectionSaturationSliderStatus\": \"" << escapeJson(model.reflectionSaturationSliderStatus) << "\",\n";
        f << "  \"environmentZonePresetStatus\": \"" << escapeJson(model.environmentZonePresetStatus) << "\",\n";
        f << "  \"environmentZonePreset\": \"" << escapeJson(model.environmentZonePreset) << "\",\n";
        f << "  \"reflectionUniformUpdateStatus\": \"" << escapeJson(model.reflectionUniformUpdateStatus) << "\",\n";
        f << "  \"motionPerformanceGuardStatus\": \"" << escapeJson(model.motionPerformanceGuardStatus) << "\",\n";
        f << "  \"cameraMotionStatus\": \"" << escapeJson(model.cameraMotionStatus) << "\",\n";
        f << "  \"cameraMotionSpeed\": " << model.cameraMotionSpeed << ",\n";
        f << "  \"cameraMotionQualityTier\": \"" << escapeJson(model.cameraMotionQualityTier) << "\",\n";
        f << "  \"cameraMotionQualityBlend\": " << model.cameraMotionQualityBlend << ",\n";
        f << "  \"motionReflectionScale\": " << model.motionReflectionScale << ",\n";
        f << "  \"motionClearcoatScale\": " << model.motionClearcoatScale << ",\n";
        f << "  \"motionDiagnosticsThrottleStatus\": \"" << escapeJson(model.motionDiagnosticsThrottleStatus) << "\",\n";
        f << "  \"motionQualityRestoreStatus\": \"" << escapeJson(model.motionQualityRestoreStatus) << "\",\n";
        f << "  \"motionQualityTransitionMs\": " << model.motionQualityTransitionMs << ",\n";
        f << "  \"cameraMovingFpsLast\": " << model.cameraMovingFpsLast << ",\n";
        f << "  \"cameraStillFpsLast\": " << model.cameraStillFpsLast << ",\n";
        f << "  \"targetMovingFps\": " << model.targetMovingFps << ",\n";
        f << "  \"movingFpsGuardStatus\": \"" << escapeJson(model.movingFpsGuardStatus) << "\",\n";
        f << "  \"carPaintReflectionStatus\": \"" << escapeJson(model.carPaintReflectionStatus) << "\",\n";
        f << "  \"metalReflectionStatus\": \"" << escapeJson(model.metalReflectionStatus) << "\",\n";
        f << "  \"plasticReflectionStatus\": \"" << escapeJson(model.plasticReflectionStatus) << "\",\n";
        f << "  \"rubberReflectionStatus\": \"" << escapeJson(model.rubberReflectionStatus) << "\",\n";
        f << "  \"glassMetadataReflectionStatus\": \"" << escapeJson(model.glassMetadataReflectionStatus) << "\",\n";
        f << "  \"materialPresetReflectionStatus\": \"" << escapeJson(model.materialPresetReflectionStatus) << "\",\n";
        f << "  \"fakeCubemapDebugViewStatus\": \"" << escapeJson(model.fakeCubemapDebugViewStatus) << "\",\n";
        f << "  \"reflectionZonesDebugViewStatus\": \"" << escapeJson(model.reflectionZonesDebugViewStatus) << "\",\n";
        f << "  \"reflectionContrastDebugViewStatus\": \"" << escapeJson(model.reflectionContrastDebugViewStatus) << "\",\n";
        f << "  \"reflectionEnergyGuardDebugViewStatus\": \"" << escapeJson(model.reflectionEnergyGuardDebugViewStatus) << "\",\n";
        f << "  \"clearcoatReflectionDebugViewStatus\": \"" << escapeJson(model.clearcoatReflectionDebugViewStatus) << "\",\n";
        f << "  \"motionQualityDebugViewStatus\": \"" << escapeJson(model.motionQualityDebugViewStatus) << "\",\n";
        f << "  \"p23ClearcoatPreservedStatus\": \"" << escapeJson(model.p23ClearcoatPreservedStatus) << "\",\n";
        f << "  \"p24PerformanceStatus\": \"" << escapeJson(model.p24PerformanceStatus) << "\",\n";
        f << "  \"fakeCubemapNoTextureStatus\": \"" << escapeJson(model.fakeCubemapNoTextureStatus) << "\",\n";
        f << "  \"fakeCubemapNoNewPassStatus\": \"" << escapeJson(model.fakeCubemapNoNewPassStatus) << "\",\n";
        f << "  \"reflectionNoTextureRebuildStatus\": \"" << escapeJson(model.reflectionNoTextureRebuildStatus) << "\",\n";
        f << "  \"reflectionNoModelReuploadStatus\": \"" << escapeJson(model.reflectionNoModelReuploadStatus) << "\",\n";
        f << "  \"noFrameFileWriteStatus\": \"" << escapeJson(model.noFrameFileWriteStatus) << "\",\n";
        f << "  \"noFrameGlbParseStatus\": \"" << escapeJson(model.noFrameGlbParseStatus) << "\",\n";
        f << "  \"glassPolishStatus\": \"" << escapeJson(model.glassPolishStatus) << "\",\n";
        f << "  \"glassPolishMode\": \"" << escapeJson(model.glassPolishMode) << "\",\n";
        f << "  \"glassReadabilityStatus\": \"" << escapeJson(model.glassReadabilityStatus) << "\",\n";
        f << "  \"glassStillFakeTransparencyStatus\": \"" << escapeJson(model.glassStillFakeTransparencyStatus) << "\",\n";
        f << "  \"glassPresetPolishStatus\": \"" << escapeJson(model.glassPresetPolishStatus) << "\",\n";
        f << "  \"activeGlassPreset\": \"" << escapeJson(model.activeGlassPreset) << "\",\n";
        f << "  \"clearcoatPolishStatus\": \"" << escapeJson(model.clearcoatPolishStatus) << "\",\n";
        f << "  \"carPaintPolishStatus\": \"" << escapeJson(model.carPaintPolishStatus) << "\",\n";
        f << "  \"p26ReflectionPolishStatus\": \"" << escapeJson(model.p26ReflectionPolishStatus) << "\",\n";
        f << "  \"p25GlassPreservedStatus\": \"" << escapeJson(model.p25GlassPreservedStatus) << "\",\n";
        f << "  \"p26NoRealRefractionStatus\": \"" << escapeJson(model.p26NoRealRefractionStatus) << "\",\n";
        f << "  \"transparentGlassPassStatus\": \"" << escapeJson(model.transparentGlassPassStatus) << "\",\n";
        f << "  \"transparentGlassPassMode\": \"" << escapeJson(model.transparentGlassPassMode) << "\",\n";
        f << "  \"transparentGlassBlendStatus\": \"" << escapeJson(model.transparentGlassBlendStatus) << "\",\n";
        f << "  \"transparentGlassRefractionStatus\": \"" << escapeJson(model.transparentGlassRefractionStatus) << "\",\n";
        f << "  \"transparentGlassSortingStatus\": \"" << escapeJson(model.transparentGlassSortingStatus) << "\",\n";
        f << "  \"p26GlassPolishPreservedStatus\": \"" << escapeJson(model.p26GlassPolishPreservedStatus) << "\",\n";
        f << "  \"fakeGlassFallbackStatus\": \"" << escapeJson(model.fakeGlassFallbackStatus) << "\",\n";
        f << "  \"activeGlassRenderMode\": \"" << escapeJson(model.activeGlassRenderMode) << "\",\n";
        f << "  \"p27PerformanceStatus\": \"" << escapeJson(model.p27PerformanceStatus) << "\",\n";
        f << "  \"p27NoShadowStatus\": \"" << escapeJson(model.p27NoShadowStatus) << "\",\n";
        f << "  \"p27NoRaytraceStatus\": \"" << escapeJson(model.p27NoRaytraceStatus) << "\",\n";
        f << "  \"p27NoSsrStatus\": \"" << escapeJson(model.p27NoSsrStatus) << "\",\n";
        f << "  \"p27NoRealMirrorStatus\": \"" << escapeJson(model.p27NoRealMirrorStatus) << "\",\n";
        f << "  \"p27NoScreenRefractionStatus\": \"" << escapeJson(model.p27NoScreenRefractionStatus) << "\",\n";
        f << "  \"p27NoTextureRebuildStatus\": \"" << escapeJson(model.p27NoTextureRebuildStatus) << "\",\n";
        f << "  \"p27NoModelReuploadStatus\": \"" << escapeJson(model.p27NoModelReuploadStatus) << "\",\n";
        f << "  \"fpsCurrent\": " << model.fpsCurrent << ",\n";
        f << "  \"frameTimeMs\": " << model.frameTimeMs << ",\n";
        f << "  \"fpsSource\": \"" << escapeJson(model.fpsSource) << "\",\n";
        f << "  \"fpsLastStable\": " << model.fpsLastStable << ",\n";
        f << "  \"frameTimeLastStableMs\": " << model.frameTimeLastStableMs << ",\n";
        f << "  \"fpsStatus\": \"" << escapeJson(model.fpsStatus) << "\",\n";
        f << "  \"fpsUpdateMode\": \"" << escapeJson(model.fpsUpdateMode) << "\",\n";
        f << "  \"fpsSampleWindowMs\": " << model.fpsSampleWindowMs << ",\n";
        f << "  \"framesRenderedLive\": " << model.framesRenderedLive << ",\n";
        f << "  \"modelUploadRepeatCount\": " << model.modelUploadRepeatCount << ",\n";
        f << "  \"uploadGenerationId\": " << model.uploadGenerationId << ",\n";
        f << "  \"renderLoopAllocationGuardStatus\": \"" << escapeJson(model.renderLoopAllocationGuardStatus) << "\",\n";
        f << "  \"debugZipStatus\": \"" << escapeJson(model.debugZipStatus) << "\",\n";
        f << "  \"debugZipPath\": \"" << escapeJson(model.debugZipPath) << "\",\n";
        f << "  \"debugZipIncludedFiles\": \"" << escapeJson(model.debugZipIncludedFiles) << "\",\n";
        f << "  \"debugZipReason\": \"" << escapeJson(model.debugZipReason) << "\",\n";
        f << "  \"fallbackCubeVisible\": " << (model.fallbackCubeVisible ? "true" : "false") << ",\n";
        f << "  \"fallbackCubeStatus\": \"" << escapeJson(model.fallbackCubeStatus) << "\",\n";
        f << "  \"deviceName\": \"" << escapeJson(gpuName) << "\",\n";
        f << "  \"deviceType\": \"" << escapeJson(gpuType) << "\",\n";
        f << "  \"apiVersion\": \"" << escapeJson(apiVersion) << "\",\n";
        f << "  \"swapchainFormat\": " << (int)swapchainFormat << ",\n";
        f << "  \"extent\": { \"width\": " << extent.width << ", \"height\": " << extent.height << " },\n";
        f << "  \"vertexBufferReady\": " << (vertexBufferReady ? "true" : "false") << ",\n";
        f << "  \"indexBufferReady\": " << (indexBufferReady ? "true" : "false") << ",\n";
        f << "  \"uniformOrPushConstantsReady\": " << (uniformOrPushConstantsReady ? "true" : "false") << ",\n";
        f << "  \"vertexCount\": " << vertexCount << ",\n";
        f << "  \"indexCount\": " << indexCount << ",\n";
        f << "  \"framesRendered\": " << framesRendered << ",\n";
        f << "  \"cubeStatus\": \"" << (cubeReady || !model.fallbackCubeVisible ? "ok" : "failed") << "\",\n";
        f << "  \"depthStatus\": \"" << (depthReady ? "ok" : "failed") << "\",\n";
        f << "  \"cameraStatus\": \"" << (cameraReady ? "ok" : "failed") << "\",\n";
        f << "  \"cameraMvpStatus\": \"" << (cameraMvpReady ? "ok" : "failed") << "\",\n";
        f << "  \"cameraControlsStatus\": \"" << (cameraControlsReady ? "ok" : "not_implemented") << "\",\n";
        f << "  \"cameraYawDeg\": " << camera.yawDeg << ",\n";
        f << "  \"cameraPitchDeg\": " << camera.pitchDeg << ",\n";
        f << "  \"cameraDistance\": " << camera.distance << ",\n";
        f << "  \"materialConstantsReady\": " << (materialConstantsReady ? "true" : "false") << ",\n";
        f << "  \"meshAttributeLayoutReady\": " << (meshAttributeLayoutReady ? "true" : "false") << ",\n";
        f << "  \"vertexLayout\": \"POSITION,NORMAL,TEXCOORD_0,COLOR_0,TANGENT\",\n";
        f << "  \"vertexStrideBytes\": " << vertexStrideBytes << ",\n";
        f << "  \"material\": {\n";
        f << "    \"materialId\": " << material.materialId << ",\n";
        f << "    \"baseColorFactor\": [" << material.baseColorFactor[0] << ", " << material.baseColorFactor[1] << ", " << material.baseColorFactor[2] << ", " << material.baseColorFactor[3] << "],\n";
        f << "    \"metallicFactor\": " << material.metallicFactor << ",\n";
        f << "    \"roughnessFactor\": " << material.roughnessFactor << ",\n";
        f << "    \"normalScale\": " << material.normalScale << ",\n";
        f << "    \"occlusionStrength\": " << material.occlusionStrength << ",\n";
        f << "    \"emissiveFactor\": [" << material.emissiveFactor[0] << ", " << material.emissiveFactor[1] << ", " << material.emissiveFactor[2] << "],\n";
        f << "    \"clearcoatIntensity\": " << material.clearcoatIntensity << ",\n";
        f << "    \"clearcoatRoughness\": " << material.clearcoatRoughness << ",\n";
        f << "    \"reflectionContrast\": " << material.reflectionContrast << ",\n";
        f << "    \"reflectionSaturation\": " << material.reflectionSaturation << ",\n";
        f << "    \"motionReflectionScale\": " << material.motionReflectionScale << ",\n";
        f << "    \"motionClearcoatScale\": " << material.motionClearcoatScale << ",\n";
        f << "    \"glassClarity\": " << material.glassClarity << ",\n";
        f << "    \"glassThickness\": " << material.glassThickness << ",\n";
        f << "    \"alphaMode\": \"OPAQUE\",\n";
        f << "    \"alphaCutoff\": " << material.alphaCutoff << "\n";
        f << "  },\n";
        f << "  \"screenshot\": { \"status\": \"not_available\", \"reason\": \"renderer_readback_not_implemented\" },\n";
        f << "  \"triangleDrawn\": " << (triangleDrawn ? "true" : "false") << ",\n";
        renderLab.writeJsonFields(f);
        f << "\n";
        f << "}\n";
    }
};

} // namespace solum
